/**
 * PixelColorSwatch's Vue examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import type { Meta, StoryObj } from '@storybook/vue3-vite';
import { PixelColorSwatch } from '@pxlkit/ui-kit-vue';
import DefaultExample from '../../examples/data/PixelColorSwatch/Default.vue';
import PaletteExample from '../../examples/data/PixelColorSwatch/Palette.vue';
import SurfacesExample from '../../examples/data/PixelColorSwatch/Surfaces.vue';
import SurfaceTokensExample from '../../examples/data/PixelColorSwatch/SurfaceTokens.vue';

const meta: Meta = {
  title: 'UI Kit / Data / PixelColorSwatch',
  component: PixelColorSwatch,
  tags: ['autodocs', 'status-stable', 'cat-data'],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Design-token preview tile that renders a CSS custom property as a color sample alongside its human name and variable identifier.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => DefaultExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <PixelColorSwatch name="cyan" css-var="--color-retro-cyan" />\n</template>' },
    },
  },
};

/** Palette */
export const Palette: Story = {
  name: 'Palette',
  tags: ['example-palette'],
  render: () => PaletteExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-xl">\n    <PixelColorSwatch name="green" css-var="--color-retro-green" />\n    <PixelColorSwatch name="cyan" css-var="--color-retro-cyan" />\n    <PixelColorSwatch name="gold" css-var="--color-retro-gold" />\n    <PixelColorSwatch name="purple" css-var="--color-retro-purple" />\n    <PixelColorSwatch name="red" css-var="--color-retro-red" />\n    <PixelColorSwatch name="pink" css-var="--color-retro-pink" />\n  </div>\n</template>' },
    },
  },
};

/** Surfaces */
export const Surfaces: Story = {
  name: 'Surfaces',
  tags: ['example-surfaces'],
  render: () => SurfacesExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <div class="flex flex-col gap-4">\n    <PixelColorSwatch name="cyan" css-var="--color-retro-cyan" surface="pixel" />\n    <PixelColorSwatch name="cyan" css-var="--color-retro-cyan" surface="linear" />\n  </div>\n</template>' },
    },
  },
};

/** Surface Tokens */
export const SurfaceTokens: Story = {
  name: 'Surface Tokens',
  tags: ['example-surface-tokens'],
  render: () => SurfaceTokensExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <div class="grid grid-cols-2 gap-3 max-w-md">\n    <PixelColorSwatch name="surface" css-var="--color-retro-surface" />\n    <PixelColorSwatch name="border" css-var="--color-retro-border" />\n    <PixelColorSwatch name="text" css-var="--color-retro-text" />\n    <PixelColorSwatch name="muted" css-var="--color-retro-muted" />\n  </div>\n</template>' },
    },
  },
};
