/**
 * PixelColorSwatch's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Palette as PaletteExample,
  Surfaces as SurfacesExample,
  SurfaceTokens as SurfaceTokensExample,
} from '../../examples/data/pixel-color-swatch.examples';

const meta: Meta = {
  title: 'UI Kit / Data / PixelColorSwatch',
  tags: ['autodocs', 'status-stable', 'cat-data'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Design-token preview tile that renders a CSS custom property as a color sample alongside its human name and variable identifier.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelColorSwatch],\n  template: `<pxl-color-swatch name="cyan" cssVar="--color-retro-cyan" />`,\n})\nexport class Default {}' },
    },
  },
};

/** Palette */
export const Palette: Story = {
  name: 'Palette',
  tags: ['example-palette'],
  render: () => ({ props: { example: PaletteExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelColorSwatch],\n  template: `\n    <div class="grid grid-cols-2 sm:grid-cols-4 gap-3 max-w-xl">\n      <pxl-color-swatch name="green" cssVar="--color-retro-green" />\n      <pxl-color-swatch name="cyan" cssVar="--color-retro-cyan" />\n      <pxl-color-swatch name="gold" cssVar="--color-retro-gold" />\n      <pxl-color-swatch name="purple" cssVar="--color-retro-purple" />\n      <pxl-color-swatch name="red" cssVar="--color-retro-red" />\n      <pxl-color-swatch name="pink" cssVar="--color-retro-pink" />\n    </div>\n  `,\n})\nexport class Palette {}' },
    },
  },
};

/** Surfaces */
export const Surfaces: Story = {
  name: 'Surfaces',
  tags: ['example-surfaces'],
  render: () => ({ props: { example: SurfacesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelColorSwatch],\n  template: `\n    <div class="flex flex-col gap-4">\n      <pxl-color-swatch name="cyan" cssVar="--color-retro-cyan" surface="pixel" />\n      <pxl-color-swatch name="cyan" cssVar="--color-retro-cyan" surface="linear" />\n    </div>\n  `,\n})\nexport class Surfaces {}' },
    },
  },
};

/** Surface Tokens */
export const SurfaceTokens: Story = {
  name: 'Surface Tokens',
  tags: ['example-surface-tokens'],
  render: () => ({ props: { example: SurfaceTokensExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelColorSwatch } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelColorSwatch],\n  template: `\n    <div class="grid grid-cols-2 gap-3 max-w-md">\n      <pxl-color-swatch name="surface" cssVar="--color-retro-surface" />\n      <pxl-color-swatch name="border" cssVar="--color-retro-border" />\n      <pxl-color-swatch name="text" cssVar="--color-retro-text" />\n      <pxl-color-swatch name="muted" cssVar="--color-retro-muted" />\n    </div>\n  `,\n})\nexport class SurfaceTokens {}' },
    },
  },
};
