import type { ParityScenario, ParityStep } from '../interact';

const day = '[role="gridcell"]';
const tabStop = '[role="gridcell"][tabindex="0"]';
const trigger = 'button[aria-haspopup="dialog"]';
const combobox = '[role="combobox"]';
const option = '[role="option"]';
const search = 'input[type="text"]';
const previous = '[aria-label="Previous month"]';
const next = '[aria-label="Next month"]';
const preset = '[role="dialog"] .flex-wrap button';
const swatch = '[aria-label="Color presets"] button';
const clearRange = 'button[aria-label="Clear range"]';
const clearSelection = 'button[aria-label="Clear selection"]';
// A multi-select's field: the chips and the combobox, then the clear button and the chevron.
const field = 'div:has(> span > [role="combobox"])';
const chevron = `${field} > span:last-child > svg`;
const remove = (label: string) => `button[aria-label="Remove ${label}"]`;
const chipLabel = (label: string) => `span:has(+ ${remove(label)})`;
// The steps' keys do not click a focused button, as a browser's do: Enter on
// a native button plays as the key, then the click it causes.
const pressEnter = (target: string): ParityStep[] => [
  { action: 'focus', target },
  { action: 'keydown', key: 'Enter' },
  { action: 'click', target },
];

export const scenarios: ParityScenario[] = [
  // PixelCalendarGrid — the APG date grid, inline.
  {
    component: 'PixelCalendarGrid',
    example: 'Default',
    name: 'moves the focus by day and week, to the ends of the week and by month and year, then picks with Enter and Space',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'PageDown', shiftKey: true },
      { action: 'keydown', key: 'PageUp', shiftKey: true },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'Default',
    name: 'crosses into the next and previous months with the arrows, following the focus',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'Default',
    name: 'pages the months with its buttons, keeping a day of the month on show in the tab order, and picks with a click',
    steps: [
      { action: 'click', target: next },
      { action: 'click', target: next },
      { action: 'click', target: previous },
      { action: 'focus', target: tabStop },
      { action: 'click', target: day, nth: 17 },
      { action: 'click', target: day, nth: 40 },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'WithSelectedDate',
    name: 'starts the tab stop on the selected day and picks another one with Space',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'WithMinMax',
    name: 'keeps the focus within this month, where the bounds are, and ignores days outside them',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'PageDown', shiftKey: true },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: day, nth: 0 },
      { action: 'click', target: day, nth: 41 },
      { action: 'click', target: next },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'WithDisabledWeekends',
    name: 'moves the focus past the weekends and keeps it on weekdays',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: day, nth: 6 },
    ],
  },
  {
    component: 'PixelCalendarGrid',
    example: 'RangePreview',
    name: 'keeps the range preview as the focus moves through it',
    steps: [
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Enter' },
    ],
  },

  // PixelDatePicker — the grid in a popover dialog.
  {
    component: 'PixelDatePicker',
    example: 'Default',
    name: 'opens with focus on today, picks with Enter and focuses the trigger again, then reopens on the picked day',
    steps: [
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelDatePicker',
    example: 'Default',
    name: 'pages months and years with the keys and the buttons, and closes on Escape with focus back on the trigger',
    steps: [
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'PageDown', shiftKey: true },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'click', target: previous },
      { action: 'click', target: next },
      { action: 'click', target: next },
      { action: 'focus', target: tabStop },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDatePicker',
    example: 'Default',
    name: 'closes on a press outside, where focus follows the pointer',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: day, nth: 15 },
      { action: 'click', target: trigger },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelDatePicker',
    example: 'WithPresets',
    name: 'picks a preset, reopens on it and clears it',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: preset, nth: 1 },
      { action: 'click', target: trigger },
      { action: 'click', target: '[role="dialog"] .justify-end button' },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: trigger },
      { action: 'click', target: preset, nth: 2 },
    ],
  },
  {
    component: 'PixelDatePicker',
    example: 'WithMinMax',
    name: 'keeps the focus within the bounds and picks the last day allowed',
    steps: [
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'PageUp', shiftKey: true },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
    ],
  },

  // PixelDateRangePicker — two picks make a range.
  {
    component: 'PixelDateRangePicker',
    example: 'Default',
    name: 'starts a range on the first click, previews the end on hover both ways and completes it on the second click',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: day, nth: 17 },
      { action: 'hover', target: day, nth: 24 },
      { action: 'hover', target: day, nth: 10 },
      { action: 'hover', target: day, nth: 60 },
      { action: 'click', target: day, nth: 9 },
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'Default',
    name: 'picks a range from the keyboard across both months, the view following the focus',
    steps: [
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'Default',
    name: 'pages the months with the keys and the buttons and closes on a press outside',
    steps: [
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'PageUp', shiftKey: true },
      { action: 'keydown', key: 'Home' },
      { action: 'click', target: next },
      { action: 'click', target: previous },
      { action: 'click', target: previous },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'WithPresets',
    name: 'picks a preset, then clears it with the button over the trigger, focusing the trigger, and from the popover',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: preset, nth: 1 },
      { action: 'click', target: clearRange },
      { action: 'click', target: trigger },
      { action: 'click', target: preset, nth: 2 },
      { action: 'click', target: trigger },
      { action: 'click', target: day, nth: 3 },
      { action: 'click', target: '[role="dialog"] .justify-end button' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'WithPresets',
    name: 'clears from the keyboard with the button over the trigger, focusing the trigger without opening the popover',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: preset, nth: 0 },
      ...pressEnter(clearRange),
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'SingleMonth',
    name: 'closes the open popover when the button over the trigger clears the range, focusing the trigger',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: day, nth: 10 },
      { action: 'click', target: day, nth: 12 },
      { action: 'click', target: trigger },
      { action: 'click', target: clearRange },
      { action: 'click', target: trigger },
      { action: 'click', target: day, nth: 15 },
      { action: 'focus', target: clearRange },
      { action: 'click', target: clearRange },
    ],
  },
  {
    component: 'PixelDateRangePicker',
    example: 'SingleMonth',
    name: 'pages its one month with both buttons and picks a range backwards',
    steps: [
      { action: 'click', target: trigger },
      { action: 'click', target: next },
      { action: 'click', target: day, nth: 20 },
      { action: 'click', target: previous },
      { action: 'click', target: day, nth: 30 },
      { action: 'click', target: trigger },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'Escape' },
    ],
  },

  // PixelCombobox — APG combobox with a filterable listbox.
  {
    component: 'PixelCombobox',
    example: 'Default',
    name: 'opens with focus in the search field, filters as you type, wraps the highlight round the ends and selects with Enter',
    steps: [
      { action: 'click', target: combobox },
      { action: 'input', target: search, value: 'e' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'Default',
    name: 'highlights on hover, selects on click and closes on Escape or a press outside',
    steps: [
      { action: 'click', target: combobox },
      { action: 'hover', target: option, nth: 3 },
      { action: 'click', target: option, nth: 3 },
      { action: 'click', target: combobox },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: combobox },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'NotSearchable',
    name: 'opens from the trigger with Enter, ArrowDown or ArrowUp and selects without leaving it',
    steps: [
      { action: 'focus', target: combobox },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'focus', target: '[role="listbox"]' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'Grouped',
    name: 'lists the matching options under their group headings',
    steps: [
      { action: 'click', target: combobox },
      { action: 'input', target: search, value: 'an' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'input', target: search, value: 'a' },
      { action: 'click', target: option, nth: 4 },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'CustomEmptyMessage',
    name: 'shows its empty message when nothing matches, and the options again once the search is cleared',
    steps: [
      { action: 'click', target: combobox },
      { action: 'input', target: search, value: 'xyz' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'input', target: search, value: '' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'Controlled',
    name: 'reports the selection to its controller',
    steps: [
      { action: 'click', target: combobox },
      { action: 'click', target: option, nth: 5 },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'WithFormName',
    name: 'submits the selected value',
    steps: [
      { action: 'focus', target: combobox },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'Disabled',
    name: 'stays closed while disabled',
    steps: [
      { action: 'click', target: combobox },
      { action: 'keydown', key: 'ArrowDown', target: combobox },
    ],
  },
  {
    component: 'PixelCombobox',
    example: 'WithError',
    name: 'describes the trigger with the error it shows, open or closed',
    steps: [
      { action: 'click', target: combobox },
      { action: 'keydown', key: 'Escape' },
    ],
  },

  // PixelMultiSelect — chips in a combobox, a multi-selectable listbox.
  {
    component: 'PixelMultiSelect',
    example: 'Default',
    name: 'toggles options with clicks, ignoring the disabled one, and closes on a press outside',
    steps: [
      { action: 'click', target: combobox },
      { action: 'hover', target: option, nth: 2 },
      { action: 'click', target: option, nth: 2 },
      { action: 'click', target: option, nth: 4 },
      { action: 'click', target: option, nth: 0 },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'Default',
    name: 'opens and toggles from the trigger with the keyboard, and removes the last chip with Backspace',
    steps: [
      { action: 'focus', target: combobox },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Backspace' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'Backspace' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'Searchable',
    name: 'filters in a focused search field, toggles with Enter, keeps Space for typing and clears the chips',
    steps: [
      { action: 'click', target: combobox },
      { action: 'input', target: search, value: 's' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: ' ' },
      { action: 'input', target: search, value: 'xyz' },
      { action: 'keydown', key: 'Enter' },
      { action: 'input', target: search, value: '' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Backspace' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: '[aria-label="Clear selection"]' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'WithMax',
    name: 'adds nothing past its cap, and frees a place when a chip is removed',
    steps: [
      { action: 'click', target: combobox },
      { action: 'click', target: option, nth: 2 },
      { action: 'keydown', key: 'ArrowDown', target: combobox },
      { action: 'keydown', key: 'ArrowDown', target: combobox },
      { action: 'keydown', key: 'Enter', target: combobox },
      { action: 'click', target: '[data-pxl-chip-remove]', nth: 0 },
      { action: 'click', target: option, nth: 2 },
      { action: 'click', target: clearSelection },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'WithMax',
    name: "removes chips and clears with their buttons, the listbox staying open and each button handing its focus on to the next chip's button, then to the combobox",
    steps: [
      { action: 'click', target: combobox },
      { action: 'click', target: remove('React') },
      { action: 'click', target: remove('Vue') },
      { action: 'click', target: option, nth: 0 },
      { action: 'click', target: option, nth: 3 },
      { action: 'click', target: remove('Solid') },
      { action: 'click', target: clearSelection },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'WithMax',
    name: "removes chips and clears from the keyboard, focus moving on to the next chip's button, then to the combobox",
    steps: [
      ...pressEnter(remove('React')),
      // Keys on a remove button stay there.
      { action: 'keydown', key: 'Backspace' },
      ...pressEnter(remove('Vue')),
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Escape' },
      ...pressEnter(remove('Vue')),
      ...pressEnter(clearSelection),
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'Default',
    name: 'opens and closes the listbox from a press anywhere on the field, focusing the combobox',
    steps: [
      { action: 'click', target: field },
      { action: 'pointerdown', target: field },
      { action: 'click', target: option, nth: 1 },
      { action: 'click', target: chevron },
      { action: 'blur', target: combobox },
      { action: 'click', target: chipLabel('React') },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelMultiSelect',
    example: 'Searchable',
    name: 'hands focus back to the combobox when Escape closes the listbox from the search field',
    steps: [
      { action: 'click', target: combobox },
      { action: 'input', target: search, value: 'v' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Escape' },
    ],
  },

  // PixelColorInput — a picker dialog with a preset grid.
  {
    component: 'PixelColorInput',
    example: 'Default',
    name: "opens with focus on the browser's picker, then moves through the presets with the arrows and picks with Enter",
    steps: [
      { action: 'click', target: 'button' },
      { action: 'focus', target: `${swatch}[tabindex="0"]` },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelColorInput',
    example: 'Default',
    name: 'commits a hex colour typed in full, keeps a partial one until the field is left, and closes on a press outside',
    steps: [
      { action: 'click', target: 'button' },
      { action: 'focus', target: '[aria-label="Hex value"]' },
      { action: 'input', target: '[aria-label="Hex value"]', value: '#12' },
      { action: 'blur', target: '[aria-label="Hex value"]' },
      { action: 'input', target: '[aria-label="Hex value"]', value: 'A1B2C3' },
      { action: 'input', target: '[aria-label="Hex value"]', value: '#fff' },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelColorInput',
    example: 'RgbFormat',
    name: "writes a picked preset and the browser picker's colour as rgb()",
    steps: [
      { action: 'click', target: 'button' },
      { action: 'click', target: swatch, nth: 12 },
      { action: 'input', target: 'input[type="color"]', value: '#123456' },
      { action: 'input', target: '[aria-label="Hex value"]', value: '#abc' },
    ],
  },
  {
    component: 'PixelColorInput',
    example: 'CustomPresets',
    name: 'rings the preset in use and stops the arrows at the ends of its grid',
    steps: [
      { action: 'click', target: 'button' },
      { action: 'focus', target: swatch, nth: 2 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelColorInput',
    example: 'WithError',
    name: 'opens on a value that is not a colour and replaces it with a preset',
    steps: [
      { action: 'click', target: 'button' },
      { action: 'click', target: swatch, nth: 9 },
      { action: 'keydown', key: 'Escape' },
    ],
  },
];
