import type { ParityScenario } from '../interact';

const radio = '[role="radio"]';
const pressable = 'button[aria-pressed]';
const thumb = '[role="slider"]';
const cell = (index: number) => `input[data-pxl-otp-index="${index}"]`;
const dropzone = '[data-pxl-dropzone]';

export const scenarios: ParityScenario[] = [
  {
    component: 'PixelToggleGroup',
    example: 'Default',
    name: 'presses one alignment at a time, and unsets the pressed one when it is pressed again',
    steps: [
      { action: 'click', target: radio, nth: 1 },
      { action: 'click', target: radio, nth: 1 },
      { action: 'click', target: radio, nth: 2 },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'Default',
    name: 'moves focus with the arrow keys, Home and End, stopping at the ends without loop',
    steps: [
      { action: 'focus', target: radio },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'a' },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'Multiple',
    name: 'adds and removes pressed toggles in any order',
    steps: [
      { action: 'click', target: pressable, nth: 1 },
      { action: 'click', target: pressable, nth: 0 },
      { action: 'click', target: pressable, nth: 2 },
      { action: 'click', target: pressable, nth: 1 },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'RovingFocus',
    name: 'keeps a single tab stop that the arrow keys move, wrapping round',
    steps: [
      { action: 'focus', target: radio },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'RovingFocus',
    name: 'presses a toggle without moving the tab stop',
    steps: [
      { action: 'click', target: radio, nth: 2 },
      { action: 'click', target: radio, nth: 1 },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'Variants',
    name: 'repaints the pressed toggle in each variant',
    steps: [
      { action: 'click', target: '[aria-label="Outline"] [role="radio"]', nth: 1 },
      { action: 'click', target: '[aria-label="Ghost"] [role="radio"]', nth: 2 },
      { action: 'click', target: '[aria-label="Solid"] [role="radio"]' },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'Sizes',
    name: 'presses toggles of every size',
    steps: [
      { action: 'click', target: '[aria-label="Large"] [role="radio"]', nth: 2 },
      { action: 'click', target: '[aria-label="Small"] [role="radio"]', nth: 1 },
    ],
  },
  {
    component: 'PixelToggleGroup',
    example: 'Surfaces',
    name: 'presses toggles on both surfaces',
    steps: [
      { action: 'click', target: '[aria-label="Linear surface"] [role="radio"]', nth: 1 },
      { action: 'click', target: '[aria-label="Pixel surface"] [role="radio"]', nth: 1 },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Default',
    name: 'steps with the arrows, pages ten steps and jumps to the ends, never past them',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Range',
    name: 'moves each thumb of a range, stopping it at the other',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'focus', target: thumb, nth: 1 },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'End' },
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'Home' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'WithMinMax',
    name: 'steps by its own step within its own bounds',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'WithTicks',
    name: 'steps from tick to tick',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'End' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'TooltipOnDrag',
    name: 'shows the value above the thumb while it has focus',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'PageUp' },
      { action: 'blur', target: thumb },
      { action: 'keydown', key: 'ArrowRight', target: thumb },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'WithTooltip',
    name: 'keeps the value above the thumb whether focused or not',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'blur', target: thumb },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'RangeWithMarks',
    name: 'shows both values over a range, each following its thumb',
    steps: [
      { action: 'focus', target: thumb, nth: 1 },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'keydown', key: 'PageDown' },
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'End' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Disabled',
    name: 'ignores the keys while disabled',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'End' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Required',
    name: 'submits the value it moves to',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Tones',
    name: 'moves the slider of each tone on its own',
    steps: [
      { action: 'focus', target: thumb, nth: 3 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'focus', target: thumb, nth: 6 },
      { action: 'keydown', key: 'Home' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'Surfaces',
    name: 'moves the slider on either surface',
    steps: [
      { action: 'focus', target: thumb, nth: 1 },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelSlider',
    example: 'WithMarks',
    name: 'moves over its marks',
    steps: [
      { action: 'focus', target: thumb },
      { action: 'keydown', key: 'PageUp' },
      { action: 'keydown', key: 'PageUp' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Default',
    name: 'fills a cell and moves on as the code is typed, keeping focus on the last cell',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: '1' },
      { action: 'input', target: cell(1), value: '2' },
      { action: 'input', target: cell(2), value: '3' },
      { action: 'input', target: cell(3), value: '4' },
      { action: 'input', target: cell(4), value: '5' },
      { action: 'input', target: cell(5), value: '6' },
      { action: 'input', target: cell(5), value: '67' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Default',
    name: 'turns letters away from a numeric code, and keeps the last character typed over another',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: 'a' },
      { action: 'input', target: cell(0), value: '4' },
      { action: 'input', target: cell(0), value: '45' },
      { action: 'input', target: cell(1), value: 'x' },
      { action: 'input', target: cell(0), value: 'b' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Default',
    name: 'Backspace empties the cell, or goes back and empties the one before',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: '1' },
      { action: 'input', target: cell(1), value: '2' },
      { action: 'input', target: cell(2), value: '3' },
      { action: 'keydown', key: 'Backspace' },
      { action: 'keydown', key: 'Backspace' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Backspace' },
      { action: 'keydown', key: 'Backspace' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Default',
    name: 'moves between the cells with the arrows, Home and End',
    steps: [
      { action: 'focus', target: cell(2) },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Tab' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Default',
    name: 'closes up the code when a later cell is typed into or a middle one emptied',
    steps: [
      { action: 'focus', target: cell(3) },
      { action: 'input', target: cell(3), value: '9' },
      { action: 'input', target: cell(1), value: '8' },
      { action: 'input', target: cell(2), value: '7' },
      { action: 'focus', target: cell(1) },
      { action: 'keydown', key: 'Backspace' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Numeric4',
    name: 'takes a four-digit code',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: '7' },
      { action: 'input', target: cell(1), value: '3' },
      { action: 'input', target: cell(2), value: '9' },
      { action: 'input', target: cell(3), value: '1' },
      { action: 'keydown', key: 'Backspace' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Alphanumeric',
    name: 'takes letters and digits, and turns other characters away',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: 'a' },
      { action: 'input', target: cell(1), value: 'B' },
      { action: 'input', target: cell(2), value: '-' },
      { action: 'input', target: cell(2), value: '3' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'Masked',
    name: 'keeps the code in masked cells',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: '5' },
      { action: 'input', target: cell(1), value: '6' },
      { action: 'keydown', key: 'Backspace' },
    ],
  },
  {
    component: 'PixelOTPInput',
    example: 'WithSeparator',
    name: 'moves across the separators',
    steps: [
      { action: 'focus', target: cell(0) },
      { action: 'input', target: cell(0), value: '1' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelFileUpload',
    example: 'Default',
    name: 'opens the file picker from the dropzone, by a click, Enter or Space',
    steps: [
      { action: 'click', target: dropzone },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'a' },
      { action: 'blur', target: dropzone },
    ],
  },
  {
    component: 'PixelFileUpload',
    example: 'ButtonMode',
    name: 'opens the file picker from the button that stands in for the dropzone, a label of the file input',
    steps: [
      { action: 'click', target: 'input[type="file"] + label' },
      { action: 'focus', target: 'input[type="file"]' },
    ],
  },
  {
    component: 'PixelFileUpload',
    example: 'WithError',
    name: 'opens the file picker from its label',
    steps: [
      { action: 'click', target: 'label' },
      { action: 'focus', target: dropzone },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelForm',
    example: 'Default',
    name: 'shows no error while fields are typed in or left before the first submission',
    steps: [
      { action: 'focus', target: 'input' },
      { action: 'input', target: 'input', value: 'p' },
      { action: 'input', target: 'input', value: '' },
      { action: 'blur', target: 'input' },
      { action: 'focus', target: 'input', nth: 1 },
      { action: 'input', target: 'input', nth: 1, value: 'not-an-email' },
      { action: 'blur', target: 'input', nth: 1 },
      { action: 'click', target: 'label' },
    ],
  },
];
