import type { ParityScenario } from '../interact';

// PixelNavigationMenu: its links and buttons, the links of an open panel, the landmark.
const navItem = 'li > :first-child';
const panelLink = 'li > div a';
const nav = '[aria-label="Main navigation"]';

export const scenarios: ParityScenario[] = [
  {
    component: 'PixelTabs',
    example: 'Default',
    name: 'selects on click and moves focus with arrows, Home and End (automatic activation)',
    steps: [
      { action: 'click', target: '[role="tab"]', nth: 1 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelTabs',
    example: 'Vertical',
    name: 'navigates with up and down arrows when vertical',
    steps: [
      { action: 'focus', target: '[role="tab"]' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowUp' },
    ],
  },
  {
    component: 'PixelTabs',
    example: 'ManualActivation',
    name: 'moves focus without selecting until Enter or Space (manual activation)',
    steps: [
      { action: 'focus', target: '[role="tab"]' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelTabs',
    example: 'Controlled',
    name: 'reports the active tab to its controller',
    steps: [{ action: 'click', target: '[role="tab"]', nth: 2 }],
  },
  {
    component: 'PixelTabs',
    example: 'KeepMounted',
    name: 'keeps every panel mounted, hiding the inactive ones',
    steps: [{ action: 'click', target: '[role="tab"]', nth: 1 }],
  },
  {
    component: 'PixelTabs',
    example: 'Compositional',
    name: 'composed tabs select and navigate like the shorthand',
    steps: [
      { action: 'click', target: '[role="tab"]', nth: 2 },
      { action: 'keydown', key: 'ArrowRight' },
    ],
  },
  {
    component: 'PixelBreadcrumb',
    example: 'WithOnClick',
    name: 'button crumbs take focus and run their handler on click',
    steps: [
      { action: 'click', target: 'li button', nth: 0 },
      { action: 'click', target: 'li button', nth: 1 },
    ],
  },
  {
    component: 'PixelBreadcrumb',
    example: 'Default',
    name: 'link crumbs are focusable; the current page is not',
    steps: [
      { action: 'focus', target: 'li a', nth: 0 },
      { action: 'focus', target: 'li a', nth: 2 },
      { action: 'focus', target: '[aria-current="page"]' },
    ],
  },
  {
    component: 'PixelPagination',
    example: 'Default',
    name: 'pages by number, Prev and Next, disabled at either end',
    steps: [
      { action: 'click', target: 'button[aria-label="Prev"]' },
      { action: 'click', target: 'button', nth: 2 },
      { action: 'click', target: 'button[aria-label="Next"]' },
      { action: 'click', target: 'button[aria-label="Next"]' },
      { action: 'click', target: 'button[aria-label="Prev"]' },
      { action: 'click', target: 'button', nth: 1 },
      { action: 'click', target: 'button', nth: 3 },
      { action: 'click', target: 'button[aria-label="Next"]' },
    ],
  },
  {
    component: 'PixelPagination',
    example: 'MidWindow',
    name: 'the window follows the page and the picked button keeps focus',
    steps: [
      { action: 'click', target: 'button', nth: 2 },
      { action: 'click', target: 'button', nth: 4 },
      { action: 'click', target: 'button', nth: 1 },
    ],
  },
  {
    component: 'PixelPagination',
    example: 'MoreSiblings',
    name: 'two siblings on each side, up to the last page',
    steps: [
      { action: 'click', target: 'button', nth: 6 },
      { action: 'click', target: 'button', nth: 7 },
      { action: 'click', target: 'button[aria-label="Prev"]' },
    ],
  },
  {
    component: 'PixelPagination',
    example: 'LocalisedLabels',
    name: 'localised Prev and Next move the page',
    steps: [
      { action: 'click', target: 'button[aria-label="Siguiente"]' },
      { action: 'click', target: 'button[aria-label="Anterior"]' },
      { action: 'click', target: 'button[aria-label="Anterior"]' },
    ],
  },
  {
    component: 'PixelPagination',
    example: 'LastPage',
    name: 'Next is disabled on the last page',
    steps: [{ action: 'click', target: 'button[aria-label="Next"]' }],
  },
  {
    component: 'PixelAccordion',
    example: 'Default',
    name: 'one item open at a time: opening another closes it, pressing it again closes it',
    steps: [
      { action: 'click', target: 'button[aria-expanded]', nth: 1 },
      { action: 'click', target: 'button[aria-expanded]', nth: 1 },
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
      { action: 'click', target: 'button[aria-expanded]', nth: 0 },
    ],
  },
  {
    component: 'PixelAccordion',
    example: 'AllowMultiple',
    name: 'several items stay open together and close one by one',
    steps: [
      { action: 'click', target: 'button[aria-expanded]', nth: 1 },
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
      { action: 'click', target: 'button[aria-expanded]', nth: 0 },
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
    ],
  },
  {
    component: 'PixelAccordion',
    example: 'CollapsedByDefault',
    name: 'starts closed and opens the item pressed',
    steps: [
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
    ],
  },
  {
    component: 'PixelAccordion',
    example: 'Surfaces',
    name: 'two accordions keep their own state and ids',
    steps: [
      { action: 'click', target: 'button[aria-expanded]', nth: 4 },
      { action: 'click', target: 'button[aria-expanded]', nth: 2 },
    ],
  },
  {
    component: 'PixelAccordion',
    example: 'RichContent',
    name: 'a panel with markup opens in place of the first',
    steps: [{ action: 'click', target: 'button[aria-expanded]', nth: 1 }],
  },
  {
    component: 'PixelSidebar',
    example: 'Collapsible',
    name: 'the toggle collapses the rail to named icons and expands it again',
    steps: [
      { action: 'click', target: 'button[aria-expanded]' },
      { action: 'focus', target: 'li > button', nth: 1 },
      { action: 'click', target: 'button[aria-expanded]' },
    ],
  },
  {
    component: 'PixelSidebar',
    example: 'Nested',
    name: 'items and nested items take focus on click',
    steps: [
      { action: 'click', target: 'li > button', nth: 2 },
      { action: 'click', target: 'li > button', nth: 4 },
    ],
  },
  {
    component: 'PixelStepper',
    example: 'Interactive',
    name: 'steps up to the active one take focus from the arrows, Home and End, without wrapping, and activate with Enter or Space',
    steps: [
      { action: 'click', target: 'button', nth: 1 },
      { action: 'click', target: 'button', nth: 1 },
      { action: 'focus', target: '[data-pxl-step]', nth: 0 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelStepper',
    example: 'Interactive',
    name: 'a step after the active one ignores clicks and keys; Back and Next move the active step',
    steps: [
      { action: 'click', target: '[data-pxl-step]', nth: 2 },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'click', target: 'button', nth: 1 },
      { action: 'click', target: '[data-pxl-step]', nth: 0 },
      { action: 'click', target: 'button', nth: 0 },
    ],
  },
  {
    component: 'PixelStepper',
    example: 'AllowNextStepsSelect',
    name: 'every step is clickable when later steps are allowed',
    steps: [
      { action: 'click', target: '[data-pxl-step]', nth: 3 },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: ' ' },
    ],
  },
  {
    component: 'PixelStepper',
    example: 'Default',
    name: 'without a step handler, steps stay out of the tab order and ignore keys',
    steps: [
      { action: 'focus', target: '[data-pxl-step]', nth: 1 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: '[data-pxl-step]', nth: 2 },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'a mouse pointing at an item opens its panel in the shared viewport; another item or leaving the menu closes it',
    steps: [
      { action: 'hover', target: navItem, nth: 1 },
      { action: 'hover', target: navItem, nth: 2 },
      { action: 'hover', target: navItem, nth: 1 },
      { action: 'unhover', target: nav },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'a click toggles a panel, which neither focus opens nor the pointer closes',
    steps: [
      { action: 'focus', target: navItem, nth: 1 },
      { action: 'click', target: navItem, nth: 1 },
      { action: 'unhover', target: nav },
      { action: 'hover', target: navItem, nth: 2 },
      { action: 'click', target: navItem, nth: 1 },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'a click keeps open the panel the mouse opened, until the next click',
    steps: [
      { action: 'hover', target: navItem, nth: 1 },
      { action: 'click', target: navItem, nth: 1 },
      { action: 'unhover', target: nav },
      { action: 'click', target: navItem, nth: 1 },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'arrows wrap round the items, Home and End jump, and Enter and Space are left to the browser',
    steps: [
      { action: 'focus', target: navItem, nth: 1 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: ' ' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'ArrowDown moves into the open panel and Escape closes it, focus back on its button or left on another item',
    steps: [
      { action: 'click', target: navItem, nth: 1 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'click', target: navItem, nth: 1 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Default',
    name: 'a panel the mouse opened hands focus inside it back to its button as the pointer leaves the menu',
    steps: [
      { action: 'hover', target: navItem, nth: 1 },
      { action: 'focus', target: panelLink, nth: 1 },
      { action: 'unhover', target: nav },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'InlinePanels',
    name: 'panels open under their own item, and Escape inside one returns focus to its button',
    steps: [
      { action: 'hover', target: navItem, nth: 1 },
      { action: 'click', target: navItem, nth: 1 },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: navItem, nth: 1 },
      { action: 'focus', target: panelLink, nth: 0 },
      { action: 'keydown', key: 'Escape' },
      { action: 'hover', target: navItem, nth: 0 },
    ],
  },
  {
    component: 'PixelNavigationMenu',
    example: 'Vertical',
    name: 'up and down arrows move round a vertical menu',
    steps: [
      { action: 'focus', target: navItem, nth: 0 },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Home' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'a click opens a menu that takes focus; arrows wrap round its enabled items, Home and End jump, Escape returns focus',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'disabled items and separators are skipped',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Home' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'a submenu opens from the keyboard on its first item; Left and Escape close it back to its item',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'Left and Right switch menus, wrapping round, from the focused button while every menu is closed',
    steps: [
      { action: 'focus', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowLeft' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowLeft' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'Down and Up on a closed menu button open its menu on the first or last item',
    steps: [
      { action: 'focus', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'Enter and Space choose the highlighted item; the menu closes with focus on its button; so does Tab',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 2 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'click', target: 'button[aria-haspopup]', nth: 2 },
      { action: 'keydown', key: ' ' },
      { action: 'click', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'keydown', key: 'Tab' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'keeps its one tab stop on the button that last had focus or a menu open',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 2 },
      { action: 'keydown', key: 'Escape' },
      { action: 'focus', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Tab' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'pointing at another button switches menus, items under the pointer are highlighted, a click chooses one',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'hover', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'hover', target: '[role="menu"] > .relative', nth: 2 },
      { action: 'hover', target: '[role="menu"] > .relative', nth: 1 },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'click', target: '[role="menu"] [role="menuitem"]', nth: 1 },
      { action: 'click', target: '[role="menu"] [role="menuitem"]', nth: 4 },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'a submenu opens under the pointer, which highlights and chooses its items',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'hover', target: '[role="menu"] > .relative', nth: 2 },
      { action: 'hover', target: '[role="menu"] [role="menu"] [role="menuitem"]', nth: 1 },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'click', target: '[role="menu"] [role="menu"] [role="menuitem"]', nth: 1 },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'Default',
    name: 'the open menu button toggles its menu, and a press outside closes it',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'click', target: 'button[aria-haspopup]', nth: 1 },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelMenubar',
    example: 'WithSubmenus',
    name: 'items with submenus: Right and Enter enter them, Right from inside switches menus, Home and End move inside',
    steps: [
      { action: 'click', target: 'button[aria-haspopup]', nth: 0 },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowRight' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: ' ' },
    ],
  },
];
