import type { ParityScenario } from '../interact';

const opener = '[data-parity-root] button';
const closeButton = '[role="dialog"] button[aria-label]';
const backdrop = '[data-pxl-overlay-backdrop]';
const alertButton = '[role="alertdialog"] button';
const dialogButton = '[role="dialog"] button';
const combobox = '[role="combobox"]';
const option = '[role="option"]';
// The wrapper a tooltip anchors to, and the trigger inside it.
const anchor = '[data-parity-root] span.relative';
const anchorButton = '[data-parity-root] button';
const menuTrigger = '[data-parity-root] button[aria-haspopup="menu"]';
// Any item of a menu: plain, checkbox or radio.
const menuItem = '[role^="menuitem"]';

export const scenarios: ParityScenario[] = [
  {
    component: 'PixelModal',
    example: 'Default',
    name: 'opens with focus inside, keeps Tab inside and closes on Escape, returning focus',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelModal',
    example: 'Default',
    name: 'closes from the close button and from the backdrop',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: closeButton },
      { action: 'click', target: opener },
      { action: 'click', target: backdrop },
    ],
  },
  {
    component: 'PixelModal',
    example: 'WithFooter',
    name: 'cycles focus through the footer actions and closes from one',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'click', target: '[role="dialog"] button', nth: 2 },
    ],
  },
  {
    component: 'PixelModal',
    example: 'AsyncClose',
    name: 'shows a busy close button until asyncClose settles',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: closeButton },
      { action: 'keydown', key: 'Escape' },
      { action: 'wait', ms: 900 },
    ],
  },
  {
    component: 'PixelModal',
    example: 'Sizes',
    name: 'renders each size',
    steps: [
      { action: 'click', target: opener, nth: 2 },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: opener, nth: 4 },
    ],
  },
  {
    component: 'PixelModal',
    example: 'Surfaces',
    name: 'renders the linear card and the pixel window',
    steps: [
      { action: 'click', target: opener, nth: 1 },
      { action: 'click', target: closeButton },
      { action: 'click', target: opener },
    ],
  },
  {
    component: 'PixelModal',
    example: 'WithDescription',
    name: 'describes the dialog with its description',
    steps: [{ action: 'click', target: opener }],
  },
  {
    component: 'PixelModal',
    example: 'CustomCloseLabel',
    name: 'labels the close button as asked',
    steps: [{ action: 'click', target: opener }],
  },
  {
    component: 'PixelAlertDialog',
    example: 'Default',
    name: 'opens with focus on Cancel, keeps Tab inside and closes on Escape, returning focus',
    steps: [
      { action: 'click', target: opener },
      // Cancel takes focus a task after opening.
      { action: 'wait', ms: 10 },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelAlertDialog',
    example: 'Default',
    name: 'closes from Cancel, from the backdrop and after the action',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: alertButton },
      { action: 'click', target: opener },
      { action: 'click', target: backdrop },
      { action: 'click', target: opener },
      { action: 'click', target: alertButton, nth: 1 },
    ],
  },
  {
    component: 'PixelAlertDialog',
    example: 'Destructive',
    name: 'accents a destructive action and confirms it',
    steps: [
      { action: 'click', target: opener },
      { action: 'wait', ms: 10 },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'click', target: alertButton, nth: 1 },
    ],
  },
  {
    component: 'PixelAlertDialog',
    example: 'AsyncAction',
    name: 'stays open and busy until the action settles, ignoring Escape and the backdrop meanwhile',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: alertButton, nth: 1 },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: backdrop },
      { action: 'click', target: alertButton },
      { action: 'wait', ms: 800 },
    ],
  },
  {
    component: 'PixelDrawer',
    example: 'Default',
    name: 'opens with focus inside, keeps Tab inside and closes on Escape, returning focus',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDrawer',
    example: 'Default',
    name: 'closes from the backdrop and from the actions in its header and footer',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: backdrop },
      { action: 'click', target: opener },
      { action: 'click', target: dialogButton },
      { action: 'click', target: opener },
      { action: 'click', target: dialogButton, nth: 1 },
    ],
  },
  {
    component: 'PixelDrawer',
    example: 'LeftSide',
    name: 'focuses the panel itself when it holds nothing focusable',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDrawer',
    example: 'BottomSheet',
    name: 'names and describes the bottom drawer and closes from its footer',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'click', target: dialogButton },
    ],
  },
  {
    component: 'PixelSheet',
    example: 'Default',
    name: 'opens with focus inside, keeps Tab inside and closes on Escape, returning focus',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Tab', shiftKey: true },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelSheet',
    example: 'Default',
    name: 'closes from the backdrop and from an action inside',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: backdrop },
      { action: 'click', target: opener },
      { action: 'click', target: dialogButton },
    ],
  },
  {
    component: 'PixelSheet',
    example: 'WithDragHandle',
    name: 'draws the drag handle and focuses the panel itself when it holds nothing focusable',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'Tab' },
      { action: 'click', target: backdrop },
    ],
  },
  {
    component: 'PixelSheet',
    example: 'TopFull',
    name: 'docks a full-height sheet to the top, named by its aria-label',
    steps: [
      { action: 'click', target: opener },
      { action: 'click', target: dialogButton },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'Default',
    name: 'opens with focus in the search field and moves the highlight with wrapping arrows, Home and End',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'Tab' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'Default',
    name: 'filters by label and keywords, shows the empty message and starts over on reopening',
    steps: [
      { action: 'click', target: opener },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'input', target: combobox, value: 'go' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'input', target: combobox, value: 'prefer' },
      { action: 'input', target: combobox, value: 'zzz' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: opener },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'Default',
    name: 'highlights an option on hover, runs one on click and closes on the backdrop',
    steps: [
      { action: 'click', target: opener },
      { action: 'hover', target: option, nth: 3 },
      { action: 'click', target: option, nth: 1 },
      { action: 'click', target: opener },
      { action: 'click', target: backdrop },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'Default',
    name: 'toggles with its shortcut, on Cmd or Ctrl, and only with its exact modifiers',
    steps: [
      { action: 'keydown', key: 'k' },
      { action: 'keydown', key: 'k', ctrlKey: true },
      { action: 'keydown', key: 'k', metaKey: true },
      { action: 'keydown', key: 'K', ctrlKey: true, shiftKey: true },
      { action: 'keydown', key: 'k', metaKey: true },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'WithCustomShortcut',
    name: 'opens with its own shortcut only',
    steps: [
      { action: 'keydown', key: 'k', ctrlKey: true },
      { action: 'keydown', key: 'P', ctrlKey: true, shiftKey: true },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelCommand',
    example: 'LinearSurface',
    name: 'renders the linear palette and its own empty message',
    steps: [
      { action: 'click', target: opener },
      { action: 'input', target: combobox, value: 'nothing' },
      { action: 'input', target: combobox, value: 'sprint' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'opens after the hover delay and closes after the leave delay',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
      { action: 'unhover', target: anchor },
      { action: 'wait', ms: 200 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'opens on focus and closes on blur, after the delays',
    steps: [
      { action: 'focus', target: anchorButton },
      { action: 'wait', ms: 300 },
      { action: 'blur', target: anchorButton },
      { action: 'wait', ms: 200 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'stays closed when the pointer leaves before the delay',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'unhover', target: anchor },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'closes on Escape and stays closed until the pointer leaves and comes back',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
      { action: 'keydown', key: 'Escape' },
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
      { action: 'unhover', target: anchor },
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'drops a pending open on Escape',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'keydown', key: 'Escape' },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Default',
    name: 'describes the focused trigger while open, and closes on Escape until focus leaves and comes back',
    steps: [
      { action: 'focus', target: anchorButton },
      { action: 'wait', ms: 300 },
      { action: 'keydown', key: 'Escape' },
      { action: 'wait', ms: 300 },
      { action: 'blur', target: anchorButton },
      { action: 'focus', target: anchorButton },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Positions',
    name: 'opens on the side it asks for',
    steps: [
      { action: 'hover', target: anchor, nth: 1 },
      { action: 'hover', target: anchor, nth: 2 },
      { action: 'hover', target: anchor, nth: 3 },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Triggers',
    name: 'opens the focus tooltip on focus only and toggles the click one, closing it on Escape and on a press outside',
    steps: [
      { action: 'hover', target: anchor, nth: 1 },
      { action: 'wait', ms: 300 },
      { action: 'focus', target: anchorButton, nth: 1 },
      { action: 'wait', ms: 300 },
      { action: 'click', target: anchorButton, nth: 2 },
      { action: 'wait', ms: 200 },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: anchorButton, nth: 2 },
      { action: 'click', target: anchorButton, nth: 2 },
      { action: 'click', target: anchorButton, nth: 2 },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Triggers',
    name: 'closes the focus tooltip on Escape until focus leaves and comes back',
    steps: [
      { action: 'focus', target: anchorButton, nth: 1 },
      { action: 'wait', ms: 300 },
      { action: 'keydown', key: 'Escape' },
      { action: 'wait', ms: 300 },
      { action: 'blur', target: anchorButton, nth: 1 },
      { action: 'focus', target: anchorButton, nth: 1 },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Surfaces',
    name: 'draws the tooltip for each surface',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'hover', target: anchor, nth: 1 },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'RichContent',
    name: 'renders rich content',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'CustomDelay',
    name: 'opens and closes at once without delays, and waits for a slow open',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'unhover', target: anchor },
      { action: 'hover', target: anchor, nth: 1 },
      { action: 'wait', ms: 300 },
      { action: 'wait', ms: 450 },
      { action: 'unhover', target: anchor, nth: 1 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Controlled',
    name: 'reports hover to its parent and follows the open state it gets back',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'wait', ms: 300 },
      { action: 'click', target: anchorButton, nth: 1 },
      { action: 'click', target: anchorButton, nth: 1 },
      { action: 'unhover', target: anchor },
      { action: 'wait', ms: 200 },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'Uncontrolled',
    name: 'starts open and toggles on click, staying open on a press inside it',
    steps: [
      { action: 'click', target: anchorButton },
      { action: 'click', target: anchorButton },
      { action: 'keydown', key: 'Escape' },
      { action: 'click', target: anchorButton },
      { action: 'pointerdown', target: '[role="tooltip"]' },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelTooltip',
    example: 'SideOffset',
    name: 'keeps the distance it asks for',
    steps: [
      { action: 'hover', target: anchor },
      { action: 'hover', target: anchor, nth: 1 },
      { action: 'wait', ms: 300 },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'opens from the trigger with focus in the menu, whose active descendant follows the arrows, Home and End, then activates it with Enter, focusing the trigger again',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Home' },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'opens on its first item from ArrowDown and on its last from ArrowUp on the trigger, closes on Escape and activates with Space, focusing the trigger again each time',
    steps: [
      { action: 'focus', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: ' ' },
      { action: 'click', target: menuTrigger },
      { action: 'click', target: menuTrigger },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'highlights an item on hover, activates one on click focusing the trigger again, and closes on a press outside, focus following the pointer',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'hover', target: menuItem, nth: 2 },
      { action: 'click', target: menuItem, nth: 1 },
      { action: 'click', target: menuTrigger },
      { action: 'pointerdown', target: 'body' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'closes on Tab and Shift+Tab with focus back on the trigger',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Tab' },
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'Tab', shiftKey: true },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'moves into the open menu from its trigger with an arrow key',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'focus', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'focus', target: menuTrigger },
      { action: 'keydown', key: 'ArrowUp' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Default',
    name: 'jumps to an item by typing its label, starting over after a pause',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'a' },
      { action: 'keydown', key: 'd' },
      { action: 'wait', ms: 700 },
      { action: 'keydown', key: 'd' },
      { action: 'keydown', key: 'u' },
      { action: 'wait', ms: 700 },
      { action: 'keydown', key: 'e' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'DisabledItems',
    name: 'skips disabled items with the keyboard and ignores them under the pointer',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'End' },
      { action: 'hover', target: menuItem, nth: 4 },
      { action: 'click', target: menuItem, nth: 1 },
      { action: 'keydown', key: 'p' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'DisabledItems',
    name: 'opens from the trigger on its first and last enabled items, past disabled ones',
    steps: [
      { action: 'focus', target: menuTrigger },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'keydown', key: 'Escape' },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'HeadersAndSeparators',
    name: 'moves past headers and separators to the items',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'v' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'CheckboxAndRadio',
    name: 'marks checked checkbox and radio items, exposed with their roles and checked state, and activates one',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'End' },
      { action: 'keydown', key: 'ArrowUp' },
      { action: 'click', target: menuItem, nth: 1 },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'WithIconsAndShortcuts',
    name: 'shows the shortcuts of its items',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Tones',
    name: 'opens one menu at a time, closing the other on the press outside it',
    steps: [
      { action: 'click', target: menuTrigger, nth: 3 },
      { action: 'click', target: menuTrigger, nth: 1 },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Surfaces',
    name: 'draws the menu for each surface',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'click', target: menuTrigger, nth: 1 },
      { action: 'keydown', key: 'ArrowDown' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'Disabled',
    name: 'does not open from a disabled trigger',
    steps: [{ action: 'click', target: menuTrigger }],
  },
  {
    component: 'PixelDropdown',
    example: 'Composition',
    name: 'composes header, items, shortcut and separator, and activates by typing',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 's' },
      { action: 'keydown', key: 'Enter' },
    ],
  },
  {
    component: 'PixelDropdown',
    example: 'ControlledOpen',
    name: 'follows the open state its parent holds',
    steps: [
      { action: 'click', target: menuTrigger },
      { action: 'click', target: menuItem, nth: 1 },
      { action: 'focus', target: menuTrigger },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'ArrowDown' },
      { action: 'keydown', key: 'Escape' },
    ],
  },
];
