/**
 * PixelRotate's Vue examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import type { Meta, StoryObj } from '@storybook/vue3-vite';
import { PixelRotate } from '@pxlkit/ui-kit-vue';
import DefaultExample from '../../examples/animations/PixelRotate/Default.vue';
import ReverseDirectionExample from '../../examples/animations/PixelRotate/ReverseDirection.vue';
import HoverTriggerExample from '../../examples/animations/PixelRotate/HoverTrigger.vue';

const meta: Meta = {
  title: 'UI Kit / Animations / PixelRotate',
  component: PixelRotate,
  tags: ['autodocs', 'status-stable', 'cat-animations'],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Full 360° rotation loop with configurable direction, duration, and trigger.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => DefaultExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelRotate } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <PixelRotate>\n    <span>Rotate</span>\n  </PixelRotate>\n</template>' },
    },
  },
};

/** Reverse Direction */
export const ReverseDirection: Story = {
  name: 'Reverse Direction',
  tags: ['example-reverse-direction'],
  render: () => ReverseDirectionExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelRotate } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <PixelRotate direction="reverse" :duration="2400">\n    <span>Reverse</span>\n  </PixelRotate>\n</template>' },
    },
  },
};

/** Hover Trigger */
export const HoverTrigger: Story = {
  name: 'Hover Trigger',
  tags: ['example-hover-trigger'],
  render: () => HoverTriggerExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { PixelRotate } from \'@pxlkit/ui-kit-vue\';\n</script>\n\n<template>\n  <PixelRotate trigger="hover" :repeat="1" :duration="900">\n    <span>Hover me</span>\n  </PixelRotate>\n</template>' },
    },
  },
};
