/**
 * PixelFadeIn's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Delayed as DelayedExample,
  OnHover as OnHoverExample,
} from '../../examples/animations/pixel-fade-in.examples';

const meta: Meta = {
  title: 'UI Kit / Animations / PixelFadeIn',
  tags: ['autodocs', 'status-stable', 'cat-animations'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Fades children from opacity 0 to 1 with configurable duration, delay, easing, and trigger.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelFadeIn } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelFadeIn],\n  template: `\n    <pxl-fade-in>\n      <div style="padding: 16px; background: #111; color: #fff">Fades in on mount</div>\n    </pxl-fade-in>\n  `,\n})\nexport class Default {}' },
    },
  },
};

/** Delayed */
export const Delayed: Story = {
  name: 'Delayed',
  tags: ['example-delayed'],
  render: () => ({ props: { example: DelayedExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelFadeIn } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelFadeIn],\n  template: `\n    <pxl-fade-in [duration]="600" [delay]="200" easing="ease-out">\n      <div style="padding: 16px; background: #0EA5E9; color: #000">Delayed fade-in</div>\n    </pxl-fade-in>\n  `,\n})\nexport class Delayed {}' },
    },
  },
};

/** On Hover */
export const OnHover: Story = {
  name: 'On Hover',
  tags: ['example-on-hover'],
  render: () => ({ props: { example: OnHoverExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelFadeIn } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelFadeIn],\n  template: `\n    <pxl-fade-in trigger="hover" [duration]="300">\n      <div style="padding: 16px; background: #222; color: #0EA5E9">Hover to fade in</div>\n    </pxl-fade-in>\n  `,\n})\nexport class OnHover {}' },
    },
  },
};
