/**
 * PixelSpinner's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Sizes as SizesExample,
  Tones as TonesExample,
  PixelSurface as PixelSurfaceExample,
  Decorative as DecorativeExample,
} from '../../examples/feedback/pixel-spinner.examples';

const meta: Meta = {
  title: 'UI Kit / Feedback / PixelSpinner',
  tags: ['autodocs', 'status-stable', 'cat-feedback'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Compact loading indicator with surface-aware animation (stepped on pixel, smooth on linear) and tone-driven color.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelSpinner } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelSpinner],\n  template: `<pxl-spinner />`,\n})\nexport class Default {}' },
    },
  },
};

/** Sizes */
export const Sizes: Story = {
  name: 'Sizes',
  tags: ['example-sizes'],
  render: () => ({ props: { example: SizesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelSpinner } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelSpinner],\n  template: `\n    <div class="flex items-center gap-4">\n      <pxl-spinner size="xs" />\n      <pxl-spinner size="sm" />\n      <pxl-spinner size="md" />\n      <pxl-spinner size="lg" />\n    </div>\n  `,\n})\nexport class Sizes {}' },
    },
  },
};

/** Tones */
export const Tones: Story = {
  name: 'Tones',
  tags: ['example-tones'],
  render: () => ({ props: { example: TonesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelSpinner } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelSpinner],\n  template: `\n    <div class="flex items-center gap-4">\n      <pxl-spinner tone="neutral" />\n      <pxl-spinner tone="green" />\n      <pxl-spinner tone="cyan" />\n      <pxl-spinner tone="gold" />\n      <pxl-spinner tone="red" />\n      <pxl-spinner tone="purple" />\n      <pxl-spinner tone="pink" />\n    </div>\n  `,\n})\nexport class Tones {}' },
    },
  },
};

/** Pixel surface */
export const PixelSurface: Story = {
  name: 'Pixel surface',
  tags: ['example-pixel-surface'],
  render: () => ({ props: { example: PixelSurfaceExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelSpinner } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelSpinner],\n  template: `<pxl-spinner surface="pixel" size="lg" tone="cyan" />`,\n})\nexport class PixelSurface {}' },
    },
  },
};

/** Decorative (inside aria-busy parent) */
export const Decorative: Story = {
  name: 'Decorative (inside aria-busy parent)',
  tags: ['example-decorative'],
  render: () => ({ props: { example: DecorativeExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelSpinner } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelSpinner],\n  template: `\n    <button type="button" aria-busy="true" class="inline-flex items-center gap-2">\n      <pxl-spinner decorative size="sm" />\n      <span>Saving…</span>\n    </button>\n  `,\n})\nexport class Decorative {}' },
    },
  },
};
