/**
 * PxlKitToastProvider's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Tones as TonesExample,
  BottomRight as BottomRightExample,
  TopCenter as TopCenterExample,
  Stacked as StackedExample,
  Flat as FlatExample,
  PixelSurface as PixelSurfaceExample,
  LinearSurface as LinearSurfaceExample,
  Loading as LoadingExample,
  PromiseFlow as PromiseFlowExample,
  PromiseRejected as PromiseRejectedExample,
  MaxLimit as MaxLimitExample,
  WithAction as WithActionExample,
} from '../../examples/feedback/pxl-kit-toast-provider.examples';

const meta: Meta = {
  title: 'UI Kit / Feedback / PxlKitToastProvider',
  tags: ['autodocs', 'status-stable', 'cat-feedback'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'App-root toast provider that hosts the toast queue, viewport portal, and stacked/expanded visual mode — paired with useToast() (injectToast() in Angular) for imperative push/update/dismiss/promise APIs.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="toaster.toast({ title: \'Saved\', message: \'Your changes were persisted.\' })">\n          Push toast\n        </button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class Default {}' },
    },
  },
};

/** Tones */
export const Tones: Story = {
  name: 'Tones',
  tags: ['example-tones'],
  render: () => ({ props: { example: TonesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" tone="green" (click)="toaster.toast.success(\'Saved\', \'Changes persisted.\')">Success</button>\n        <button pxlButton size="sm" tone="cyan" (click)="toaster.toast.info(\'Heads up\', \'New release available.\')">Info</button>\n        <button pxlButton size="sm" tone="gold" (click)="toaster.toast.warning(\'Careful\', \'Storage almost full.\')">Warning</button>\n        <button pxlButton size="sm" tone="red" (click)="toaster.toast.error(\'Failed\', \'Upload could not finish.\')">Error</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class Tones {}' },
    },
  },
};

/** Bottom Right */
export const BottomRight: Story = {
  name: 'Bottom Right',
  tags: ['example-bottom-right'],
  render: () => ({ props: { example: BottomRightExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster position="bottom-right">\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="toaster.toast({ title: \'Bottom-right toast\' })">Push to bottom-right</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class BottomRight {}' },
    },
  },
};

/** Top Center */
export const TopCenter: Story = {
  name: 'Top Center',
  tags: ['example-top-center'],
  render: () => ({ props: { example: TopCenterExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster position="top-center">\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="toaster.toast({ title: \'Bottom-right toast\' })">Push to bottom-right</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class TopCenter {}' },
    },
  },
};

/** Stacked */
export const Stacked: Story = {
  name: 'Stacked',
  tags: ['example-stacked'],
  render: () => ({ props: { example: StackedExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster stacked [stackVisible]="2">\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="pushThree(toaster.toast)">Push three</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class Stacked {\n  pushThree(toast: ToastFn): void {\n    toast({ title: \'First\', message: \'Oldest of the stack.\' });\n    toast({ title: \'Second\', message: \'In the middle.\' });\n    toast({ title: \'Third\', message: \'Newest in front.\' });\n  }\n}' },
    },
  },
};

/** Flat */
export const Flat: Story = {
  name: 'Flat',
  tags: ['example-flat'],
  render: () => ({ props: { example: FlatExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster [stacked]="false">\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="pushThree(toaster.toast)">Push three</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class Flat {\n  pushThree(toast: ToastFn): void {\n    toast({ title: \'First\', message: \'Oldest of the stack.\' });\n    toast({ title: \'Second\', message: \'In the middle.\' });\n    toast({ title: \'Third\', message: \'Newest in front.\' });\n  }\n}' },
    },
  },
};

/** Pixel Surface */
export const PixelSurface: Story = {
  name: 'Pixel Surface',
  tags: ['example-pixel-surface'],
  render: () => ({ props: { example: PixelSurfaceExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster surface="pixel">\n      <div class="flex flex-wrap gap-2">\n        <button\n          pxlButton\n          size="sm"\n          (click)="toaster.toast({ title: \'Pixel surface\', message: \'HP-bar accent on the left edge.\', tone: \'cyan\' })"\n        >\n          Push pixel toast\n        </button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class PixelSurface {}' },
    },
  },
};

/** Linear Surface */
export const LinearSurface: Story = {
  name: 'Linear Surface',
  tags: ['example-linear-surface'],
  render: () => ({ props: { example: LinearSurfaceExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster surface="linear">\n      <div class="flex flex-wrap gap-2">\n        <button\n          pxlButton\n          size="sm"\n          (click)="toaster.toast({ title: \'Pixel surface\', message: \'HP-bar accent on the left edge.\', tone: \'cyan\' })"\n        >\n          Push pixel toast\n        </button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class LinearSurface {}' },
    },
  },
};

/** Loading → Success */
export const Loading: Story = {
  name: 'Loading → Success',
  tags: ['example-loading'],
  render: () => ({ props: { example: LoadingExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="runUpload(toaster.toast)">Run loading → success</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class Loading {\n  runUpload(toast: ToastFn): void {\n    const id = toast.loading(\'Uploading…\', \'Hang tight.\');\n    setTimeout(() => {\n      toast.update(id, {\n        title: \'Uploaded\',\n        message: \'File is ready.\',\n        tone: \'green\',\n        loading: false,\n        duration: 4500,\n      });\n    }, 1000);\n  }\n}' },
    },
  },
};

/** Promise Flow */
export const PromiseFlow: Story = {
  name: 'Promise Flow',
  tags: ['example-promise-flow'],
  render: () => ({ props: { example: PromiseFlowExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="runSave(toaster.toast)">Run promise</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class PromiseFlow {\n  runSave(toast: ToastFn): Promise<string> {\n    return toast.promise(() => new Promise<string>((resolve) => setTimeout(() => resolve(\'ok\'), 1000)), {\n      loading: { title: \'Saving…\' },\n      success: { title: \'Saved\', message: \'All set.\' },\n      error: { title: \'Failed\', message: \'Try again.\' },\n    });\n  }\n}' },
    },
  },
};

/** Promise Rejected */
export const PromiseRejected: Story = {
  name: 'Promise Rejected',
  tags: ['example-promise-rejected'],
  render: () => ({ props: { example: PromiseRejectedExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" tone="red" (click)="runFailingSave(toaster.toast)">Run failing promise</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class PromiseRejected {\n  runFailingSave(toast: ToastFn): void {\n    toast\n      .promise(() => new Promise<string>((_resolve, reject) => setTimeout(() => reject(new Error(\'Network down\')), 1000)), {\n        loading: { title: \'Saving…\' },\n        success: { title: \'Saved\', message: \'All set.\' },\n        error: { title: \'Failed\', message: \'Try again.\' },\n      })\n      // The error toast tells the user; the rejection needs no other handling.\n      .catch(() => {});\n  }\n}' },
    },
  },
};

/** Max Limit */
export const MaxLimit: Story = {
  name: 'Max Limit',
  tags: ['example-max-limit'],
  render: () => ({ props: { example: MaxLimitExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider, type ToastApi } from \'@pxlkit/ui-kit-angular\';\n\ntype ToastFn = ToastApi[\'toast\'];\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster [max]="2">\n      <div class="flex flex-wrap gap-2">\n        <button pxlButton size="sm" (click)="pushFive(toaster.toast)">Push five (max 2)</button>\n      </div>\n    </pxl-toast-provider>\n  `,\n})\nexport class MaxLimit {\n  pushFive(toast: ToastFn): void {\n    for (let i = 1; i <= 5; i += 1) {\n      toast({ title: `Toast ${i}`, message: \'Only the latest two stay.\' });\n    }\n  }\n}' },
    },
  },
};

/** With Action */
export const WithAction: Story = {
  name: 'With Action',
  tags: ['example-with-action'],
  render: () => ({ props: { example: WithActionExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PxlKitToastProvider } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PxlKitToastProvider],\n  template: `\n    <pxl-toast-provider #toaster>\n      <div class="flex flex-wrap gap-2">\n        <button\n          pxlButton\n          size="sm"\n          tone="red"\n          (click)="toaster.toast({ tone: \'red\', title: \'File deleted\', message: \'You can still restore it.\', action: undo })"\n        >\n          Push with action\n        </button>\n      </div>\n    </pxl-toast-provider>\n    <ng-template #undo><button pxlButton size="sm" tone="red" variant="outline">Undo</button></ng-template>\n  `,\n})\nexport class WithAction {}' },
    },
  },
};
