/**
 * PixelToggleGroup's Vue examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import type { Meta, StoryObj } from '@storybook/vue3-vite';
import { PixelToggleGroup } from '@pxlkit/ui-kit-vue';
import DefaultExample from '../../examples/forms/PixelToggleGroup/Default.vue';
import MultipleExample from '../../examples/forms/PixelToggleGroup/Multiple.vue';
import VariantsExample from '../../examples/forms/PixelToggleGroup/Variants.vue';
import SizesExample from '../../examples/forms/PixelToggleGroup/Sizes.vue';
import RovingFocusExample from '../../examples/forms/PixelToggleGroup/RovingFocus.vue';
import SurfacesExample from '../../examples/forms/PixelToggleGroup/Surfaces.vue';

const meta: Meta = {
  title: 'UI Kit / Forms / PixelToggleGroup',
  component: PixelToggleGroup as unknown as Meta['component'],
  tags: ['autodocs', 'status-stable', 'cat-forms'],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Grouped pressable toggles with single- or multi-select semantics, roving focus, and surface-aware styling.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => DefaultExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst value = ref(\'left\');\n</script>\n\n<template>\n  <PixelToggleGroup v-model="value" type="single" aria-label="Text alignment">\n    <PixelToggle value="left">Left</PixelToggle>\n    <PixelToggle value="center">Center</PixelToggle>\n    <PixelToggle value="right">Right</PixelToggle>\n  </PixelToggleGroup>\n</template>' },
    },
  },
};

/** Multiple */
export const Multiple: Story = {
  name: 'Multiple',
  tags: ['example-multiple'],
  render: () => MultipleExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst value = ref([\'bold\']);\n</script>\n\n<template>\n  <PixelToggleGroup v-model="value" type="multiple" aria-label="Text formatting">\n    <PixelToggle value="bold">Bold</PixelToggle>\n    <PixelToggle value="italic">Italic</PixelToggle>\n    <PixelToggle value="underline">Underline</PixelToggle>\n  </PixelToggleGroup>\n</template>' },
    },
  },
};

/** Variants */
export const Variants: Story = {
  name: 'Variants',
  tags: ['example-variants'],
  render: () => VariantsExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst a = ref(\'one\');\nconst b = ref(\'one\');\nconst c = ref(\'one\');\nconst d = ref(\'one\');\n</script>\n\n<template>\n  <div class="space-y-3">\n    <PixelToggleGroup v-model="a" type="single" variant="soft" aria-label="Soft">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n      <PixelToggle value="three">Three</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="b" type="single" variant="solid" aria-label="Solid">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n      <PixelToggle value="three">Three</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="c" type="single" variant="outline" aria-label="Outline">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n      <PixelToggle value="three">Three</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="d" type="single" variant="ghost" aria-label="Ghost">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n      <PixelToggle value="three">Three</PixelToggle>\n    </PixelToggleGroup>\n  </div>\n</template>' },
    },
  },
};

/** Sizes */
export const Sizes: Story = {
  name: 'Sizes',
  tags: ['example-sizes'],
  render: () => SizesExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst sm = ref(\'a\');\nconst md = ref(\'a\');\nconst lg = ref(\'a\');\n</script>\n\n<template>\n  <div class="space-y-3">\n    <PixelToggleGroup v-model="sm" type="single" size="sm" aria-label="Small">\n      <PixelToggle value="a">A</PixelToggle>\n      <PixelToggle value="b">B</PixelToggle>\n      <PixelToggle value="c">C</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="md" type="single" size="md" aria-label="Medium">\n      <PixelToggle value="a">A</PixelToggle>\n      <PixelToggle value="b">B</PixelToggle>\n      <PixelToggle value="c">C</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="lg" type="single" size="lg" aria-label="Large">\n      <PixelToggle value="a">A</PixelToggle>\n      <PixelToggle value="b">B</PixelToggle>\n      <PixelToggle value="c">C</PixelToggle>\n    </PixelToggleGroup>\n  </div>\n</template>' },
    },
  },
};

/** Roving focus */
export const RovingFocus: Story = {
  name: 'Roving focus',
  tags: ['example-roving-focus'],
  render: () => RovingFocusExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst value = ref(\'list\');\n</script>\n\n<template>\n  <PixelToggleGroup v-model="value" type="single" roving-focus loop aria-label="View mode">\n    <PixelToggle value="list">List</PixelToggle>\n    <PixelToggle value="grid">Grid</PixelToggle>\n    <PixelToggle value="board">Board</PixelToggle>\n  </PixelToggleGroup>\n</template>' },
    },
  },
};

/** Surfaces */
export const Surfaces: Story = {
  name: 'Surfaces',
  tags: ['example-surfaces'],
  render: () => SurfacesExample,
  parameters: {
    docs: {
      source: { language: 'html', code: '<script setup lang="ts">\nimport { ref } from \'vue\';\nimport { PixelToggle, PixelToggleGroup } from \'@pxlkit/ui-kit-vue\';\n\nconst pixel = ref(\'one\');\nconst linear = ref(\'one\');\n</script>\n\n<template>\n  <div class="space-y-3">\n    <PixelToggleGroup v-model="pixel" type="single" surface="pixel" aria-label="Pixel surface">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n    </PixelToggleGroup>\n    <PixelToggleGroup v-model="linear" type="single" surface="linear" aria-label="Linear surface">\n      <PixelToggle value="one">One</PixelToggle>\n      <PixelToggle value="two">Two</PixelToggle>\n    </PixelToggleGroup>\n  </div>\n</template>' },
    },
  },
};
