/**
 * Unit tests for generate-readme-package.
 *
 * Strategy: use a temp repo on disk so we exercise filesystem discovery
 * (packages/* dirs, package.json parsing, README.generated.md writes) without
 * touching the real monorepo.
 */

import fs from "fs-extra";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  generateReadmePackage,
  renderPackageReadme,
  renderComponentsBlock,
  fillComponentsBlock,
  COMPONENTS_START_MARKER,
  COMPONENTS_END_MARKER,
  GenerateReadmePackageGenerator,
  type PackageReadmeInput,
} from "../generate-readme-package";
import type { ManifestRecord } from "../_lib/generator-base";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeManifest(
  pkg: string,
  name: string,
  overrides: Partial<ManifestRecord["manifest"]> = {},
): ManifestRecord {
  const tsx = `/tmp/${pkg}/src/${name}.tsx`;
  return {
    package: pkg,
    sourceFile: tsx,
    manifestFile: tsx.replace(/\.tsx$/, ".manifest.ts"),
    manifest: {
      name,
      description: `description for ${name}`,
      category: "actions",
      status: "stable",
      since: "1.0.0",
      ...overrides,
    },
  };
}

async function makeTempRepo(): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "pxl-readme-test-"));
  await fs.ensureDir(path.join(dir, "packages"));
  return dir;
}

async function makePkg(
  repoRoot: string,
  dirName: string,
  pkgJson: Record<string, unknown>,
  extras: { license?: boolean; changelog?: boolean } = {},
): Promise<string> {
  const pkgDir = path.join(repoRoot, "packages", dirName);
  await fs.ensureDir(pkgDir);
  await fs.writeJson(path.join(pkgDir, "package.json"), pkgJson, { spaces: 2 });
  if (extras.license) {
    await fs.writeFile(path.join(pkgDir, "LICENSE"), "MIT", "utf8");
  }
  if (extras.changelog) {
    await fs.writeFile(
      path.join(pkgDir, "CHANGELOG.md"),
      "# changelog\n",
      "utf8",
    );
  }
  return pkgDir;
}

// ---------------------------------------------------------------------------
// renderPackageReadme (pure)
// ---------------------------------------------------------------------------

describe("renderPackageReadme", () => {
  const input: PackageReadmeInput = {
    packageName: "@pxlkit/ui-kit",
    packageDir: "/tmp/repo/packages/ui-kit",
    packageJson: {
      name: "@pxlkit/ui-kit",
      version: "1.9.0",
      description: "Retro pixel art UI kit",
      license: "MIT",
      homepage: "https://pxlkit.xyz",
      repository: "https://github.com/joangel/pxlkit",
    },
    manifests: [
      makeManifest("@pxlkit/ui-kit", "PixelButton"),
      makeManifest("@pxlkit/ui-kit", "PixelCard", {
        status: "beta",
        category: "cards",
      }),
    ],
  };

  it("renders a title with the package name", () => {
    const md = renderPackageReadme(input);
    expect(md.startsWith("# @pxlkit/ui-kit")).toBe(true);
  });

  it("includes a generator notice comment", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain(
      "<!-- generated by scripts/build-docs/generate-readme-package.ts -->",
    );
  });

  it("emits npm + bundle + license badges", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain("img.shields.io/npm/v/");
    expect(md).toContain("img.shields.io/bundlephobia/minzip/");
    expect(md).toContain("img.shields.io/badge/license-MIT-blue.svg");
  });

  it("renders the package description verbatim", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain("Retro pixel art UI kit");
  });

  it("includes install snippets for npm/pnpm/yarn", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain("npm install @pxlkit/ui-kit");
    expect(md).toContain("pnpm add @pxlkit/ui-kit");
    expect(md).toContain("yarn add @pxlkit/ui-kit");
  });

  it("synthesises a quick start from the first stable component", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain('import { PixelButton } from "@pxlkit/ui-kit";');
    expect(md).toContain("<PixelButton />");
  });

  it("renders a components table sorted by name", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain(
      "| Component | Status | Since | Category | Description |",
    );
    const buttonIdx = md.indexOf("PixelButton");
    const cardIdx = md.indexOf("PixelCard");
    expect(buttonIdx).toBeGreaterThan(0);
    expect(cardIdx).toBeGreaterThan(buttonIdx);
  });

  it("escapes pipe characters inside descriptions", () => {
    const md = renderPackageReadme({
      ...input,
      manifests: [
        makeManifest("@pxlkit/ui-kit", "Weird", {
          description: "has a | pipe in it",
        }),
      ],
    });
    expect(md).toContain("has a \\| pipe in it");
  });

  it("emits an api stability commitment section", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain("## API stability");
  });

  it("emits a links section with homepage and repo", () => {
    const md = renderPackageReadme(input);
    expect(md).toContain("[Homepage](https://pxlkit.xyz)");
    expect(md).toContain("[Repository](https://github.com/joangel/pxlkit)");
  });

  it("handles repository as an object with url", () => {
    const md = renderPackageReadme({
      ...input,
      packageJson: {
        ...input.packageJson,
        repository: { type: "git", url: "https://example.com/repo.git" },
      },
    });
    expect(md).toContain("[Repository](https://example.com/repo.git)");
  });

  it("falls back to a generic quick start when there are no manifests", () => {
    const md = renderPackageReadme({ ...input, manifests: [] });
    expect(md).toContain("_No components registered yet._");
    expect(md).toContain('import * as pxlkitUiKit from "@pxlkit/ui-kit";');
  });
});

// ---------------------------------------------------------------------------
// renderComponentsBlock / fillComponentsBlock (pure, marker contract)
// ---------------------------------------------------------------------------

describe("renderComponentsBlock", () => {
  const manifests = [
    makeManifest("@pxlkit/ui-kit", "PixelCard", { status: "beta", category: "cards" }),
    makeManifest("@pxlkit/ui-kit", "PixelButton"),
  ];

  it("renders one backticked row per manifest, sorted by name", () => {
    const block = renderComponentsBlock(manifests);
    expect(block).toContain("| Component | Status | Since | Category |");
    expect(block).toContain("| `PixelButton` | stable | 1.0.0 | actions |");
    expect(block).toContain("| `PixelCard` | beta | 1.0.0 | cards |");
    expect(block.indexOf("`PixelButton`")).toBeLessThan(block.indexOf("`PixelCard`"));
  });

  it("does not leak free-text descriptions into the block", () => {
    // Descriptions are free text and could contain backticked PascalCase
    // tokens that would violate the coverage/consistency gates.
    const block = renderComponentsBlock(manifests);
    expect(block).not.toContain("description for");
  });
});

describe("fillComponentsBlock", () => {
  const manifests = [
    makeManifest("@pxlkit/ui-kit", "PixelButton"),
    makeManifest("@pxlkit/ui-kit", "PixelCard"),
  ];

  it("returns null when the markers are absent", () => {
    expect(fillComponentsBlock("# plain readme\n", manifests)).toBeNull();
  });

  it("returns null when only the start marker is present", () => {
    const readme = `# x\n\n${COMPONENTS_START_MARKER}\nstuff\n`;
    expect(fillComponentsBlock(readme, manifests)).toBeNull();
  });

  it("returns null when END precedes START", () => {
    const readme = `# x\n\n${COMPONENTS_END_MARKER}\n${COMPONENTS_START_MARKER}\n`;
    expect(fillComponentsBlock(readme, manifests)).toBeNull();
  });

  it("replaces only the content between the markers", () => {
    const readme = [
      "# pkg",
      "",
      "## Components",
      "",
      COMPONENTS_START_MARKER,
      "old hand list",
      COMPONENTS_END_MARKER,
      "",
      "## After",
      "tail",
    ].join("\n");
    const out = fillComponentsBlock(readme, manifests);
    expect(out).not.toBeNull();
    expect(out!).not.toContain("old hand list");
    expect(out!).toContain("`PixelButton`");
    expect(out!).toContain("`PixelCard`");
    // markers stay, prefix and suffix preserved byte-for-byte
    expect(out!.startsWith(`# pkg\n\n## Components\n\n${COMPONENTS_START_MARKER}`)).toBe(true);
    expect(out!.endsWith(`${COMPONENTS_END_MARKER}\n\n## After\ntail`)).toBe(true);
  });

  it("is idempotent", () => {
    const readme = [
      "# pkg",
      "",
      COMPONENTS_START_MARKER,
      "old",
      COMPONENTS_END_MARKER,
      "",
    ].join("\n");
    const once = fillComponentsBlock(readme, manifests)!;
    const twice = fillComponentsBlock(once, manifests)!;
    expect(twice).toBe(once);
  });

  it("preserves CRLF line endings", () => {
    const readme = [
      "# pkg",
      "",
      COMPONENTS_START_MARKER,
      "old",
      COMPONENTS_END_MARKER,
      "",
    ].join("\r\n");
    const out = fillComponentsBlock(readme, manifests)!;
    expect(out).toContain(`${COMPONENTS_START_MARKER}\r\n`);
    expect(out).toContain("| `PixelButton` | stable | 1.0.0 | actions |\r\n");
    expect(out).not.toMatch(/[^\r]\n/);
  });
});

// ---------------------------------------------------------------------------
// generateReadmePackage (integration with temp fs)
// ---------------------------------------------------------------------------

describe("generateReadmePackage", () => {
  let tmp: string;

  beforeEach(async () => {
    tmp = await makeTempRepo();
  });

  afterEach(async () => {
    await fs.remove(tmp);
  });

  it("writes one README.generated.md per package with manifests", async () => {
    await makePkg(
      tmp,
      "ui-kit",
      { name: "@pxlkit/ui-kit", version: "1.0.0", license: "MIT" },
      { license: true, changelog: true },
    );
    await makePkg(tmp, "core", {
      name: "@pxlkit/core",
      version: "1.0.0",
      license: "MIT",
    });

    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [
        makeManifest("@pxlkit/ui-kit", "PixelButton"),
        makeManifest("@pxlkit/core", "PixelIcon"),
      ],
    });

    expect(result.outputs).toHaveLength(2);
    const paths = result.outputs.map((o) => o.path);
    expect(paths.some((p) => p.endsWith("packages/ui-kit/README.generated.md"))).toBe(
      true,
    );
    expect(paths.some((p) => p.endsWith("packages/core/README.generated.md"))).toBe(
      true,
    );

    const written = await fs.readFile(
      path.join(tmp, "packages", "ui-kit", "README.generated.md"),
      "utf8",
    );
    expect(written).toContain("# @pxlkit/ui-kit");
  });

  it("never overwrites a hand-authored README.md", async () => {
    const pkgDir = await makePkg(tmp, "ui-kit", {
      name: "@pxlkit/ui-kit",
      version: "1.0.0",
      license: "MIT",
    });
    const handAuthored = "# hand-authored — do not touch\n";
    await fs.writeFile(path.join(pkgDir, "README.md"), handAuthored, "utf8");

    await generateReadmePackage({
      repoRoot: tmp,
      manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
    });

    const after = await fs.readFile(path.join(pkgDir, "README.md"), "utf8");
    expect(after).toBe(handAuthored);
    expect(
      await fs.pathExists(path.join(pkgDir, "README.generated.md")),
    ).toBe(true);
  });

  it("fills the marker block in place when README.md declares it", async () => {
    const pkgDir = await makePkg(tmp, "ui-kit", {
      name: "@pxlkit/ui-kit",
      version: "1.0.0",
      license: "MIT",
    });
    const readme = [
      "# hand-authored title",
      "",
      "## Components",
      "",
      COMPONENTS_START_MARKER,
      "stale hand list",
      COMPONENTS_END_MARKER,
      "",
      "## License",
      "MIT",
      "",
    ].join("\n");
    await fs.writeFile(path.join(pkgDir, "README.md"), readme, "utf8");

    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
    });

    expect(result.outputs).toHaveLength(1);
    expect(result.outputs[0]!.path.endsWith("packages/ui-kit/README.md")).toBe(true);

    const after = await fs.readFile(path.join(pkgDir, "README.md"), "utf8");
    expect(after).toContain("# hand-authored title");
    expect(after).toContain("## License");
    expect(after).toContain(COMPONENTS_START_MARKER);
    expect(after).toContain(COMPONENTS_END_MARKER);
    expect(after).toContain("`PixelButton`");
    expect(after).not.toContain("stale hand list");
    // no sibling emitted in marker mode
    expect(await fs.pathExists(path.join(pkgDir, "README.generated.md"))).toBe(false);
  });

  it("falls back to the sibling when README.md has no markers", async () => {
    const pkgDir = await makePkg(tmp, "ui-kit", {
      name: "@pxlkit/ui-kit",
      version: "1.0.0",
      license: "MIT",
    });
    await fs.writeFile(path.join(pkgDir, "README.md"), "# no markers here\n", "utf8");

    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
    });

    expect(result.outputs).toHaveLength(1);
    expect(result.outputs[0]!.path.endsWith("README.generated.md")).toBe(true);
    const untouched = await fs.readFile(path.join(pkgDir, "README.md"), "utf8");
    expect(untouched).toBe("# no markers here\n");
  });

  it("skips packages that have no manifests", async () => {
    await makePkg(tmp, "ui-kit", {
      name: "@pxlkit/ui-kit",
      version: "1.0.0",
      license: "MIT",
    });
    await makePkg(tmp, "core", {
      name: "@pxlkit/core",
      version: "1.0.0",
      license: "MIT",
    });

    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
    });
    expect(result.outputs).toHaveLength(1);
    expect(result.skippedPackages).toContain("@pxlkit/core");
  });

  it("records packages with no/invalid package.json as failed", async () => {
    const broken = path.join(tmp, "packages", "broken");
    await fs.ensureDir(broken);
    // no package.json at all

    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [],
    });
    expect(result.failedPackages.some((p) => p.endsWith("packages/broken"))).toBe(
      true,
    );
  });

  it("dryRun=true returns outputs but writes nothing", async () => {
    const pkgDir = await makePkg(tmp, "ui-kit", {
      name: "@pxlkit/ui-kit",
      version: "1.0.0",
      license: "MIT",
    });
    const result = await generateReadmePackage({
      repoRoot: tmp,
      manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
      dryRun: true,
    });
    expect(result.outputs).toHaveLength(1);
    expect(
      await fs.pathExists(path.join(pkgDir, "README.generated.md")),
    ).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Generator base wrapper
// ---------------------------------------------------------------------------

describe("GenerateReadmePackageGenerator", () => {
  it("is a Generator with the expected name", () => {
    const g = new GenerateReadmePackageGenerator();
    expect(g.name).toBe("generate-readme-package");
  });

  it("returns writes from the context manifests (dry-run)", async () => {
    const tmp = await makeTempRepo();
    try {
      await makePkg(tmp, "ui-kit", {
        name: "@pxlkit/ui-kit",
        version: "1.0.0",
        license: "MIT",
      });
      const g = new GenerateReadmePackageGenerator();
      const res = await g.run({
        repoRoot: tmp,
        manifests: [makeManifest("@pxlkit/ui-kit", "PixelButton")],
        outputs: new Map<string, string>(),
        logger: {
          info: () => {},
          warn: () => {},
          error: () => {},
          success: () => {},
          table: () => {},
        },
      });
      expect(res.writes).toHaveLength(1);
      expect(res.writes[0]!.path.endsWith("README.generated.md")).toBe(true);
      // dry-run: nothing written to disk
      expect(
        await fs.pathExists(
          path.join(tmp, "packages", "ui-kit", "README.generated.md"),
        ),
      ).toBe(false);
    } finally {
      await fs.remove(tmp);
    }
  });
});
