/**
 * PixelCombobox's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Uncontrolled as UncontrolledExample,
  Controlled as ControlledExample,
  Grouped as GroupedExample,
  NotSearchable as NotSearchableExample,
  Sizes as SizesExample,
  Surfaces as SurfacesExample,
  Disabled as DisabledExample,
  WithError as WithErrorExample,
  WithFormName as WithFormNameExample,
  CustomEmptyMessage as CustomEmptyMessageExample,
} from '../../examples/forms/pixel-combobox.examples';

const meta: Meta = {
  title: 'UI Kit / Forms / PixelCombobox',
  tags: ['autodocs', 'status-stable', 'cat-forms'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Searchable single-value combobox built on a button trigger + listbox popover with type-to-filter, optional grouping, and full keyboard navigation.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Fruit" [options]="fruits" placeholder="Pick a fruit" hint="Type to filter" />`,\n})\nexport class Default {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Uncontrolled */
export const Uncontrolled: Story = {
  name: 'Uncontrolled',
  tags: ['example-uncontrolled'],
  render: () => ({ props: { example: UncontrolledExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Fruit" [options]="fruits" defaultValue="banana" />`,\n})\nexport class Uncontrolled {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Controlled */
export const Controlled: Story = {
  name: 'Controlled',
  tags: ['example-controlled'],
  render: () => ({ props: { example: ControlledExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component, signal } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Controlled fruit" [options]="fruits" [(value)]="value" />`,\n})\nexport class Controlled {\n  readonly fruits = FRUITS;\n  readonly value = signal(\'cherry\');\n}' },
    },
  },
};

/** Grouped options */
export const Grouped: Story = {
  name: 'Grouped options',
  tags: ['example-grouped'],
  render: () => ({ props: { example: GroupedExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst GROUPED = [\n  { value: \'us\', label: \'United States\', group: \'Americas\' },\n  { value: \'ve\', label: \'Venezuela\', group: \'Americas\' },\n  { value: \'mx\', label: \'Mexico\', group: \'Americas\' },\n  { value: \'es\', label: \'Spain\', group: \'Europe\' },\n  { value: \'fr\', label: \'France\', group: \'Europe\' },\n  { value: \'de\', label: \'Germany\', group: \'Europe\' },\n  { value: \'jp\', label: \'Japan\', group: \'Asia\' },\n  { value: \'kr\', label: \'South Korea\', group: \'Asia\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Country" [options]="countries" placeholder="Pick a country" />`,\n})\nexport class Grouped {\n  readonly countries = GROUPED;\n}' },
    },
  },
};

/** Without search */
export const NotSearchable: Story = {
  name: 'Without search',
  tags: ['example-not-searchable'],
  render: () => ({ props: { example: NotSearchableExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Fruit" [options]="fruits" [searchable]="false" placeholder="No filter" />`,\n})\nexport class NotSearchable {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Sizes */
export const Sizes: Story = {
  name: 'Sizes',
  tags: ['example-sizes'],
  render: () => ({ props: { example: SizesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `\n    <div class="flex flex-col gap-3">\n      <pxl-combobox label="Small" [options]="fruits" size="sm" placeholder="sm" />\n      <pxl-combobox label="Medium" [options]="fruits" size="md" placeholder="md" />\n      <pxl-combobox label="Large" [options]="fruits" size="lg" placeholder="lg" />\n    </div>\n  `,\n})\nexport class Sizes {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Surfaces */
export const Surfaces: Story = {
  name: 'Surfaces',
  tags: ['example-surfaces'],
  render: () => ({ props: { example: SurfacesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `\n    <div class="flex flex-col gap-3">\n      <pxl-combobox label="Pixel" [options]="fruits" surface="pixel" placeholder="pixel surface" />\n      <pxl-combobox label="Linear" [options]="fruits" surface="linear" placeholder="linear surface" />\n    </div>\n  `,\n})\nexport class Surfaces {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Disabled */
export const Disabled: Story = {
  name: 'Disabled',
  tags: ['example-disabled'],
  render: () => ({ props: { example: DisabledExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Disabled" [options]="fruits" defaultValue="apple" disabled />`,\n})\nexport class Disabled {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** With error */
export const WithError: Story = {
  name: 'With error',
  tags: ['example-with-error'],
  render: () => ({ props: { example: WithErrorExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `<pxl-combobox label="Fruit" [options]="fruits" placeholder="Pick one" error="Please choose a fruit" />`,\n})\nexport class WithError {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** With form name */
export const WithFormName: Story = {
  name: 'With form name',
  tags: ['example-with-form-name'],
  render: () => ({ props: { example: WithFormNameExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `\n    <form>\n      <pxl-combobox\n        label="Fruit"\n        [options]="fruits"\n        name="fruit"\n        defaultValue="cherry"\n        hint="Value participates in native form submission"\n      />\n    </form>\n  `,\n})\nexport class WithFormName {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};

/** Custom empty message */
export const CustomEmptyMessage: Story = {
  name: 'Custom empty message',
  tags: ['example-custom-empty-message'],
  render: () => ({ props: { example: CustomEmptyMessageExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelCombobox } from \'@pxlkit/ui-kit-angular\';\n\nconst FRUITS = [\n  { value: \'apple\', label: \'Apple\' },\n  { value: \'banana\', label: \'Banana\' },\n  { value: \'cherry\', label: \'Cherry\' },\n  { value: \'date\', label: \'Date\' },\n  { value: \'elderberry\', label: \'Elderberry\' },\n  { value: \'fig\', label: \'Fig\' },\n  { value: \'grape\', label: \'Grape\' },\n];\n\n@Component({\n  imports: [PixelCombobox],\n  template: `\n    <pxl-combobox label="Fruit" [options]="fruits" placeholder="Type \'xyz\'" emptyMessage="No fruits match your filter" />\n  `,\n})\nexport class CustomEmptyMessage {\n  readonly fruits = FRUITS;\n}' },
    },
  },
};
