/**
 * PixelTooltip's Angular examples as stories, under the React
 * Storybook's titles and names. Generated by
 * scripts/build-docs/generate-port-stories.ts (`npm run docs:build`):
 * edit the examples, not this file.
 */
import { NgComponentOutlet } from '@angular/common';
import { moduleMetadata, type Meta, type StoryObj } from '@storybook/angular';
import {
  Default as DefaultExample,
  Positions as PositionsExample,
  Triggers as TriggersExample,
  Surfaces as SurfacesExample,
  RichContent as RichContentExample,
  CustomDelay as CustomDelayExample,
  Controlled as ControlledExample,
  Uncontrolled as UncontrolledExample,
  SideOffset as SideOffsetExample,
} from '../../examples/overlays/pixel-tooltip.examples';

const meta: Meta = {
  title: 'UI Kit / Overlays / PixelTooltip',
  tags: ['autodocs', 'status-stable', 'cat-overlays'],
  decorators: [moduleMetadata({ imports: [NgComponentOutlet] })],
  parameters: {
    controls: { disable: true },
    docs: {
      description: { component: 'Floating-UI-positioned tooltip that anchors a portal-rendered hint to a trigger, with hover/focus/click activation, controlled or uncontrolled open state, and configurable open/close delays.' },
    },
  },
};

export default meta;
type Story = StoryObj;

/** Default */
export const Default: Story = {
  name: 'Default',
  tags: ['example-default'],
  render: () => ({ props: { example: DefaultExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <pxl-tooltip label="Save your changes">\n      <button pxlButton>Save</button>\n    </pxl-tooltip>\n  `,\n})\nexport class Default {}' },
    },
  },
};

/** Positions */
export const Positions: Story = {
  name: 'Positions',
  tags: ['example-positions'],
  render: () => ({ props: { example: PositionsExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex flex-wrap items-center gap-6">\n      <pxl-tooltip label="Top tooltip" position="top">\n        <button pxlButton>Top</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Bottom tooltip" position="bottom">\n        <button pxlButton>Bottom</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Left tooltip" position="left">\n        <button pxlButton>Left</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Right tooltip" position="right">\n        <button pxlButton>Right</button>\n      </pxl-tooltip>\n    </div>\n  `,\n})\nexport class Positions {}' },
    },
  },
};

/** Triggers */
export const Triggers: Story = {
  name: 'Triggers',
  tags: ['example-triggers'],
  render: () => ({ props: { example: TriggersExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex flex-wrap items-center gap-6">\n      <pxl-tooltip label="Opens on hover or focus" trigger="hover">\n        <button pxlButton>Hover</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Opens on focus only" trigger="focus">\n        <button pxlButton>Focus</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Click to toggle, Escape to close" trigger="click">\n        <button pxlButton>Click</button>\n      </pxl-tooltip>\n    </div>\n  `,\n})\nexport class Triggers {}' },
    },
  },
};

/** Surfaces */
export const Surfaces: Story = {
  name: 'Surfaces',
  tags: ['example-surfaces'],
  render: () => ({ props: { example: SurfacesExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex flex-wrap items-center gap-6">\n      <pxl-tooltip label="Pixel surface" surface="pixel">\n        <button pxlButton surface="pixel">Pixel</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Linear surface" surface="linear">\n        <button pxlButton surface="linear">Linear</button>\n      </pxl-tooltip>\n    </div>\n  `,\n})\nexport class Surfaces {}' },
    },
  },
};

/** Rich content */
export const RichContent: Story = {
  name: 'Rich content',
  tags: ['example-rich-content'],
  render: () => ({ props: { example: RichContentExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <pxl-tooltip [content]="details">\n      <button pxlButton>Hover for details</button>\n    </pxl-tooltip>\n    <ng-template #details>\n      <span class="flex flex-col gap-0.5">\n        <span class="font-semibold">Keyboard shortcut</span>\n        <span class="opacity-80">Press ⌘K to open the command palette</span>\n      </span>\n    </ng-template>\n  `,\n})\nexport class RichContent {}' },
    },
  },
};

/** Custom delay */
export const CustomDelay: Story = {
  name: 'Custom delay',
  tags: ['example-custom-delay'],
  render: () => ({ props: { example: CustomDelayExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex flex-wrap items-center gap-6">\n      <pxl-tooltip label="Opens instantly" [delay]="{ open: 0, close: 0 }">\n        <button pxlButton>Instant</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Slow open, fast close" [delay]="{ open: 600, close: 0 }">\n        <button pxlButton>Slow open</button>\n      </pxl-tooltip>\n    </div>\n  `,\n})\nexport class CustomDelay {}' },
    },
  },
};

/** Controlled */
export const Controlled: Story = {
  name: 'Controlled',
  tags: ['example-controlled'],
  render: () => ({ props: { example: ControlledExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component, signal } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex items-center gap-4">\n      <pxl-tooltip [(open)]="open" label="Controlled tooltip">\n        <button pxlButton>Anchor</button>\n      </pxl-tooltip>\n      <button pxlButton tone="cyan" variant="outline" (click)="open.set(!open())">{{ open() ? \'Hide\' : \'Show\' }}</button>\n    </div>\n  `,\n})\nexport class Controlled {\n  readonly open = signal(false);\n}' },
    },
  },
};

/** Uncontrolled */
export const Uncontrolled: Story = {
  name: 'Uncontrolled',
  tags: ['example-uncontrolled'],
  render: () => ({ props: { example: UncontrolledExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <pxl-tooltip defaultOpen label="Open by default" trigger="click">\n      <button pxlButton>Click to toggle</button>\n    </pxl-tooltip>\n  `,\n})\nexport class Uncontrolled {}' },
    },
  },
};

/** Side offset */
export const SideOffset: Story = {
  name: 'Side offset',
  tags: ['example-side-offset'],
  render: () => ({ props: { example: SideOffsetExample }, template: '<ng-container *ngComponentOutlet="example" />' }),
  parameters: {
    docs: {
      source: { language: 'typescript', code: 'import { Component } from \'@angular/core\';\nimport { PixelButton, PixelTooltip } from \'@pxlkit/ui-kit-angular\';\n\n@Component({\n  imports: [PixelButton, PixelTooltip],\n  template: `\n    <div class="flex flex-wrap items-center gap-6">\n      <pxl-tooltip label="Tight (2px)" [sideOffset]="2">\n        <button pxlButton>Tight</button>\n      </pxl-tooltip>\n      <pxl-tooltip label="Roomy (16px)" [sideOffset]="16">\n        <button pxlButton>Roomy</button>\n      </pxl-tooltip>\n    </div>\n  `,\n})\nexport class SideOffset {}' },
    },
  },
};
