// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';
import { FrameworkApi, type FrameworkApiReferences } from '@/components/FrameworkApi';
import { FrameworkCode } from '@/components/FrameworkCode';

export interface PixelRotateDocsSectionProps {
  className?: string;
  /** The level of the section's heading: 2 within /docs, 1 as the component's own page. Its subsections follow one level below. */
  headingLevel?: 1 | 2;
  /** Where its related components link: their entries on /docs, or their own pages. */
  links?: 'anchors' | 'pages';
}

export const PixelRotateDocsMeta = {
  name: 'PixelRotate',
  slug: 'pixel-rotate',
  status: 'stable',
  category: 'animations',
  since: '1.6.0',
  deprecated: false,
} as const;

/** PixelRotate's API in each kit, read from its sources by `npm run docs:build`. */
const api: FrameworkApiReferences = {
  react: {
    import: "import { PixelRotate } from '@pxlkit/ui-kit';",
    components: [
      {
        name: 'PixelRotate',
        props: [
          { name: 'children', type: 'React.ReactNode', required: true, description: 'Content to rotate.' },
          { name: 'duration', type: 'number', default: '1800', description: 'Animation duration in milliseconds. Default `1800`.' },
          { name: 'repeat', type: "number | 'infinite'", default: "'infinite'", description: "Iteration count: a number or `'infinite'`. Default `'infinite'`." },
          { name: 'direction', type: "'normal' | 'reverse' | 'alternate' | 'alternate-reverse'", default: "'normal'", description: "CSS `animation-direction`. Default `'normal'`." },
          { name: 'easing', type: 'string', default: "'linear'", description: "CSS `animation-timing-function`. Default `'linear'`." },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the animation should play. Default `'mount'`." },
          { name: 'onComplete', type: '() => void', description: 'Fires after the final iteration.' },
          { name: 'className', type: 'string', description: 'Extra class names applied to the wrapping `<div>`.' },
        ],
        notes: [
          '`ref` points to `<div>`.',
        ],
      },
    ],
  },
  vue: {
    import: "import { PixelRotate } from '@pxlkit/ui-kit-vue';",
    components: [
      {
        name: 'PixelRotate',
        props: [
          { name: 'duration', type: 'number', default: '1800', description: 'Animation duration in milliseconds.' },
          { name: 'repeat', type: "number | 'infinite'", default: "'infinite'", description: "Iteration count: a number or `'infinite'`." },
          { name: 'direction', type: "'normal' | 'reverse' | 'alternate' | 'alternate-reverse'", default: "'normal'", description: 'CSS `animation-direction`.' },
          { name: 'easing', type: 'string', default: "'linear'", description: 'CSS `animation-timing-function`.' },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`, `'inView'`, or `true` / `false` to control it." },
        ],
        events: [
          { name: 'complete', description: 'After the final iteration.' },
        ],
        slots: [
          { name: 'default', description: 'Content to rotate.' },
        ],
        notes: [
          'Other attributes and listeners fall through to its root `<div>`.',
        ],
      },
    ],
  },
  angular: {
    import: "import { PixelRotate } from '@pxlkit/ui-kit-angular';",
    components: [
      {
        name: 'PixelRotate',
        selector: 'pxl-rotate',
        props: [
          { name: 'duration', type: 'number', default: '1800', accepts: 'unknown', description: 'Animation duration in milliseconds.' },
          { name: 'repeat', type: "number | 'infinite'", default: "'infinite'", accepts: "number | 'infinite' | `${number}`", description: "Iteration count: a number or `'infinite'`." },
          { name: 'direction', type: "'normal' | 'reverse' | 'alternate' | 'alternate-reverse'", default: "'normal'", description: 'CSS `animation-direction`.' },
          { name: 'easing', type: 'string', default: "'linear'", description: 'CSS `animation-timing-function`.' },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the animation plays: `'mount'`, `'hover'`, `'click'`, `'focus'`, `'inView'`, or `true` / `false` to control it." },
        ],
        events: [
          { name: 'complete', description: 'After the final iteration.' },
        ],
        notes: [
          'Projects its content (`<ng-content>`).',
        ],
      },
    ],
  },
};

export function PixelRotateDocsSection({ className, headingLevel = 2, links = 'anchors' }: PixelRotateDocsSectionProps): React.ReactElement {
  // h2, h3 and h4 within /docs; h1, h2 and h3 as the component's own page.
  const Title = headingLevel === 1 ? 'h1' : 'h2';
  const Heading = headingLevel === 1 ? 'h2' : 'h3';
  const Subheading = headingLevel === 1 ? 'h3' : 'h4';
  return (
    <section aria-labelledby={'pixel-rotate-heading'} className={className} data-status='stable'>
      <Title id='pixel-rotate-heading'>PixelRotate</Title>
      <p className="docs-lead">Full 360° rotation loop with configurable direction, duration, and trigger.</p>
      <ul className="docs-highlights">
        <li>Configurable duration, easing, repeat count, and animation direction</li>
        <li>Trigger modes: mount, hover, focus, viewport</li>
        <li>Signals the end of its last iteration: <code>onComplete</code> (React), <code>@complete</code> (Vue), <code>(complete)</code> (Angular)</li>
        <li>Respects prefers-reduced-motion automatically</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>animations</dd>
      <dt>Since</dt><dd>v1.6.0</dd>
    </dl>
    <section aria-labelledby="pixel-rotate-api">
      <Heading id="pixel-rotate-api">API</Heading>
      <FrameworkApi label={'PixelRotate API'} headingLevel={headingLevel === 1 ? 3 : 4} react={api.react} vue={api.vue} angular={api.angular} />
    </section>
    <section aria-labelledby="pixel-rotate-a11y">
      <Heading id="pixel-rotate-a11y">Accessibility</Heading>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>respects prefers-reduced-motion</code></li>
      </ul>
      <p className="docs-aria-notes">Animation is suppressed when the user has requested reduced motion.</p>
    </section>
    <section aria-labelledby="pixel-rotate-usage">
      <Heading id="pixel-rotate-usage">Usage</Heading>
      <FrameworkCode
        variant="docs"
        label={'PixelRotate usage'}
        react={`import { PixelRotate } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelRotate>
      <span>Rotate</span>
    </PixelRotate>
  );
}`}
        vue={`<script setup lang="ts">
import { PixelRotate } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelRotate>
    <span>Rotate</span>
  </PixelRotate>
</template>`}
        angular={`import { Component } from '@angular/core';
import { PixelRotate } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelRotate],
  template: \`
    <pxl-rotate>
      <span>Rotate</span>
    </pxl-rotate>
  \`,
})
export class Default {}`}
      />
    </section>
    <section aria-label="Examples">
      <Heading>Examples</Heading>
      <article className="docs-example" id="example-default">
        <Subheading>Default</Subheading>
        <FrameworkCode
          variant="docs"
          label={'Default code'}
          react={`import { PixelRotate } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelRotate>
      <span>Rotate</span>
    </PixelRotate>
  );
}`}
          vue={`<script setup lang="ts">
import { PixelRotate } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelRotate>
    <span>Rotate</span>
  </PixelRotate>
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelRotate } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelRotate],
  template: \`
    <pxl-rotate>
      <span>Rotate</span>
    </pxl-rotate>
  \`,
})
export class Default {}`}
        />
      </article>
      <article className="docs-example" id="example-reverse-direction">
        <Subheading>Reverse Direction</Subheading>
        <FrameworkCode
          variant="docs"
          label={'Reverse Direction code'}
          react={`import { PixelRotate } from '@pxlkit/ui-kit';

export function ReverseDirection() {
  return (
    <PixelRotate direction="reverse" duration={2400}>
      <span>Reverse</span>
    </PixelRotate>
  );
}`}
          vue={`<script setup lang="ts">
import { PixelRotate } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelRotate direction="reverse" :duration="2400">
    <span>Reverse</span>
  </PixelRotate>
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelRotate } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelRotate],
  template: \`
    <pxl-rotate direction="reverse" [duration]="2400">
      <span>Reverse</span>
    </pxl-rotate>
  \`,
})
export class ReverseDirection {}`}
        />
      </article>
      <article className="docs-example" id="example-hover-trigger">
        <Subheading>Hover Trigger</Subheading>
        <FrameworkCode
          variant="docs"
          label={'Hover Trigger code'}
          react={`import { PixelRotate } from '@pxlkit/ui-kit';

export function HoverTrigger() {
  return (
    <PixelRotate trigger="hover" repeat={1} duration={900}>
      <span>Hover me</span>
    </PixelRotate>
  );
}`}
          vue={`<script setup lang="ts">
import { PixelRotate } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelRotate trigger="hover" :repeat="1" :duration="900">
    <span>Hover me</span>
  </PixelRotate>
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelRotate } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelRotate],
  template: \`
    <pxl-rotate trigger="hover" [repeat]="1" [duration]="900">
      <span>Hover me</span>
    </pxl-rotate>
  \`,
})
export class HoverTrigger {}`}
        />
      </article>
    </section>
    <section aria-label="Related components">
      <Heading>Related</Heading>
      <ul className="docs-related">
        <li><a href={links === 'pages' ? '/docs/components/pixel-float' : '#pixel-float'}>PixelFloat</a></li>
        <li><a href={links === 'pages' ? '/docs/components/pixel-pulse' : '#pixel-pulse'}>PixelPulse</a></li>
        <li><a href={links === 'pages' ? '/docs/components/pixel-bounce' : '#pixel-bounce'}>PixelBounce</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelRotateDocsSection;
