// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelBounceDocsSectionProps {
  className?: string;
}

export const PixelBounceDocsMeta = {
  name: 'PixelBounce',
  slug: 'pixel-bounce',
  status: 'stable',
  category: 'animations',
  since: '1.6.0',
  deprecated: false,
} as const;

export function PixelBounceDocsSection({ className }: PixelBounceDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-bounce-heading'} className={className} data-status='stable'>
      <h2 id='pixel-bounce-heading'>PixelBounce</h2>
      <p className="docs-lead">Vertical bounce animation with damped follow-through for any inline content.</p>
      <ul className="docs-highlights">
        <li>Configurable bounce height, duration, easing, and repeat count</li>
        <li>Trigger modes: mount, hover, focus, viewport</li>
        <li>Forwards refs and merges with internal trigger observers</li>
        <li>Respects prefers-reduced-motion automatically</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>animations</dd>
      <dt>Since</dt><dd>v1.6.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-bounce-a11y">
      <h3 id="pixel-bounce-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>respects prefers-reduced-motion</code></li>
      </ul>
      <p className="docs-aria-notes">Animation is suppressed when the user has requested reduced motion.</p>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-shake">PixelShake</a></li>
        <li><a href="#pixel-pulse">PixelPulse</a></li>
        <li><a href="#pixel-float">PixelFloat</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelBounceDocsSection;
