// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelAccordionDocsSectionProps {
  className?: string;
}

export const PixelAccordionDocsMeta = {
  name: 'PixelAccordion',
  slug: 'pixel-accordion',
  status: 'stable',
  category: 'navigation',
  since: '1.0.0',
  deprecated: false,
} as const;

export function PixelAccordionDocsSection({ className }: PixelAccordionDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-accordion-heading'} className={className} data-status='stable'>
      <h2 id='pixel-accordion-heading'>PixelAccordion</h2>
      <p className="docs-lead">Vertical list of expandable disclosure items with wired aria-controls / aria-expanded / labelled regions.</p>
      <ul className="docs-highlights">
        <li>Single-open by default; opt into multi-open via `allowMultiple`</li>
        <li>First item auto-expanded unless `collapsedByDefault` is set</li>
        <li>Surface-aware typography and borders (pixel vs linear)</li>
        <li>aria-expanded + aria-controls wired per header for assistive tech</li>
        <li>SSR-safe and tree-shakable; unopened panels are not rendered</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>navigation</dd>
      <dt>Since</dt><dd>v1.0.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-accordion-a11y">
      <h3 id="pixel-accordion-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>disclosure</code></li>
      </ul>
      <p className="docs-aria-notes">Each header is a native &lt;button&gt; with aria-expanded reflecting open state and aria-controls pointing at the panel id. Expanded panels are plain containers labelled by their header via aria-labelledby — no role=&quot;region&quot;, which would proliferate landmarks (and collide when several accordions share titles) — matching the WAI-ARIA disclosure pattern stacked into an accordion.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Toggles the focused item open or closed</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Toggles the focused item open or closed</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Moves focus between item headers</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-tabs">PixelTabs</a></li>
        <li><a href="#pixel-collapsible">PixelCollapsible</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelAccordionDocsSection;
