// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelStepperDocsSectionProps {
  className?: string;
}

export const PixelStepperDocsMeta = {
  name: 'PixelStepper',
  slug: 'pixel-stepper',
  status: 'stable',
  category: 'navigation',
  since: '1.9.0',
  deprecated: false,
} as const;

export function PixelStepperDocsSection({ className }: PixelStepperDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-stepper-heading'} className={className} data-status='stable'>
      <h2 id='pixel-stepper-heading'>PixelStepper</h2>
      <p className="docs-lead">Multi-step progress indicator with completed/active/pending/error/loading states, horizontal or vertical orientation, and full keyboard navigation.</p>
      <ul className="docs-highlights">
        <li>Compound API (PixelStepper + PixelStepper.Step) keeps step content declarative and easy to reorder.</li>
        <li>Per-step states (completed, active, pending, error, loading) with tone-mapped indicators and connectors.</li>
        <li>Horizontal or vertical orientation with roving focus, Arrow/Home/End keys, and Enter/Space activation.</li>
        <li>Optional onStepClick handler with allowNextStepsSelect gate so future steps stay locked until allowed.</li>
        <li>Surface-aware (pixel/linear) and size-aware (sm/md/lg), inheriting kit-wide tokens and focus rings.</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>navigation</dd>
      <dt>Since</dt><dd>v1.9.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-stepper-a11y">
      <h3 id="pixel-stepper-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>progress-steps</code></li>
      </ul>
      <p className="docs-aria-notes">The root renders role=&quot;group&quot; with a configurable ariaLabel (defaults to &quot;Progress steps&quot;). Each step carries an aria-label combining its position (&quot;Step N of M&quot;), its label, and its state (current/completed/error). The active step is marked with aria-current=&quot;step&quot;. Steps that are not clickable (no onStepClick, or future steps when allowNextStepsSelect is false) are removed from the tab sequence via tabIndex=-1. Indicators and connectors are aria-hidden so screen readers announce only the step label and state.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Moves focus into/out of the stepper; only clickable steps participate in the tab sequence.</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>ArrowRight</kbd></td>
            <td>Focuses the next clickable step.</td>
            <td>orientation=&quot;horizontal&quot;</td>
          </tr>
          <tr>
            <td><kbd>ArrowLeft</kbd></td>
            <td>Focuses the previous clickable step.</td>
            <td>orientation=&quot;horizontal&quot;</td>
          </tr>
          <tr>
            <td><kbd>ArrowDown</kbd></td>
            <td>Focuses the next clickable step.</td>
            <td>orientation=&quot;vertical&quot;</td>
          </tr>
          <tr>
            <td><kbd>ArrowUp</kbd></td>
            <td>Focuses the previous clickable step.</td>
            <td>orientation=&quot;vertical&quot;</td>
          </tr>
          <tr>
            <td><kbd>Home</kbd></td>
            <td>Focuses the first clickable step.</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>End</kbd></td>
            <td>Focuses the last clickable step.</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Activates the focused step (when clickable).</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Activates the focused step (when clickable).</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-labelledby="pixel-stepper-usage">
      <h3 id="pixel-stepper-usage">Usage</h3>
      <pre className="docs-code"><code>{`import { useState } from 'react';
import { PixelStepper } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelStepper active={1}>
      <PixelStepper.Step label="Account" description="Create your account" />
      <PixelStepper.Step label="Profile" description="Add some details" />
      <PixelStepper.Step label="Confirm" description="Review and submit" />
    </PixelStepper>
  );
}
`}</code></pre>
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <pre className="docs-code"><code>{`export function Default() {
  return (
    <PixelStepper active={1}>
      <PixelStepper.Step label="Account" description="Create your account" />
      <PixelStepper.Step label="Profile" description="Add some details" />
      <PixelStepper.Step label="Confirm" description="Review and submit" />
    </PixelStepper>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-interactive">
        <h4>Interactive</h4>
        <pre className="docs-code"><code>{`export function Interactive() {
  const [active, setActive] = useState(0);
  const total = 4;
  return (
    <div className="space-y-3">
      <PixelStepper active={active} onStepClick={setActive}>
        <PixelStepper.Step label="Plan" description="Pick a tier" />
        <PixelStepper.Step label="Billing" description="Payment method" />
        <PixelStepper.Step label="Confirm" description="Review charges" />
        <PixelStepper.Step label="Done" description="All set" />
      </PixelStepper>
      <div className="flex gap-2">
        <button
          type="button"
          className="text-xs px-2 py-1 border border-retro-border"
          onClick={() => setActive((i) => Math.max(0, i - 1))}
        >
          Back
        </button>
        <button
          type="button"
          className="text-xs px-2 py-1 border border-retro-border"
          onClick={() => setActive((i) => Math.min(total - 1, i + 1))}
        >
          Next
        </button>
      </div>
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-vertical">
        <h4>Vertical</h4>
        <pre className="docs-code"><code>{`export function Vertical() {
  return (
    <PixelStepper active={1} orientation="vertical">
      <PixelStepper.Step label="Upload" description="Pick a file" />
      <PixelStepper.Step label="Process" description="Running checks" loading />
      <PixelStepper.Step label="Publish" description="Make it live" />
    </PixelStepper>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-states">
        <h4>States</h4>
        <pre className="docs-code"><code>{`export function States() {
  return (
    <PixelStepper active={2}>
      <PixelStepper.Step label="Created" completed />
      <PixelStepper.Step label="Validated" completed />
      <PixelStepper.Step label="Signing" loading />
      <PixelStepper.Step label="Failed" error />
      <PixelStepper.Step label="Done" />
    </PixelStepper>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-sizes">
        <h4>Sizes</h4>
        <pre className="docs-code"><code>{`export function Sizes() {
  return (
    <div className="space-y-6">
      <PixelStepper active={1} size="sm">
        <PixelStepper.Step label="One" />
        <PixelStepper.Step label="Two" />
        <PixelStepper.Step label="Three" />
      </PixelStepper>
      <PixelStepper active={1} size="md">
        <PixelStepper.Step label="One" />
        <PixelStepper.Step label="Two" />
        <PixelStepper.Step label="Three" />
      </PixelStepper>
      <PixelStepper active={1} size="lg">
        <PixelStepper.Step label="One" />
        <PixelStepper.Step label="Two" />
        <PixelStepper.Step label="Three" />
      </PixelStepper>
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-surfaces">
        <h4>Surfaces</h4>
        <pre className="docs-code"><code>{`export function Surfaces() {
  return (
    <div className="grid grid-cols-1 gap-6">
      <PixelStepper active={1} surface="pixel" ariaLabel="Pixel stepper">
        <PixelStepper.Step label="Start" />
        <PixelStepper.Step label="Build" />
        <PixelStepper.Step label="Ship" />
      </PixelStepper>
      <PixelStepper active={1} surface="linear" ariaLabel="Linear stepper">
        <PixelStepper.Step label="Start" />
        <PixelStepper.Step label="Build" />
        <PixelStepper.Step label="Ship" />
      </PixelStepper>
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-allow-next-steps-select">
        <h4>Allow next steps</h4>
        <pre className="docs-code"><code>{`export function AllowNextStepsSelect() {
  const [active, setActive] = useState(1);
  return (
    <PixelStepper active={active} onStepClick={setActive} allowNextStepsSelect>
      <PixelStepper.Step label="Intro" description="Welcome" />
      <PixelStepper.Step label="Details" description="Tell us more" />
      <PixelStepper.Step label="Review" description="Almost there" />
      <PixelStepper.Step label="Finish" description="Complete" />
    </PixelStepper>
  );
}`}</code></pre>
      </article>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-tabs">PixelTabs</a></li>
        <li><a href="#pixel-progress">PixelProgress</a></li>
        <li><a href="#pixel-breadcrumb">PixelBreadcrumb</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelStepperDocsSection;
