// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';
import { FrameworkApi, type FrameworkApiReferences } from '@/components/FrameworkApi';
import { FrameworkCode } from '@/components/FrameworkCode';

export interface PixelTypewriterDocsSectionProps {
  className?: string;
}

export const PixelTypewriterDocsMeta = {
  name: 'PixelTypewriter',
  slug: 'pixel-typewriter',
  status: 'stable',
  category: 'animations',
  since: '1.6.0',
  deprecated: false,
} as const;

/** PixelTypewriter's API in each kit, read from its sources by `npm run docs:build`. */
const api: FrameworkApiReferences = {
  react: {
    import: "import { PixelTypewriter } from '@pxlkit/ui-kit';",
    components: [
      {
        name: 'PixelTypewriter',
        props: [
          { name: 'label', type: 'string', description: 'Label (text) to type out. Canonical prop.' },
          { name: 'text', type: 'string', deprecated: 'Use `label` instead. Retained as alias for one minor.' },
          { name: 'speed', type: 'number', default: '60', description: 'Milliseconds between each character. Default `60`.' },
          { name: 'delay', type: 'number', default: '0', description: 'Delay before typing starts, in milliseconds. Default `0`.' },
          { name: 'cursor', type: 'boolean', default: 'true', description: 'Show a blinking caret while writing. Default `true`.' },
          { name: 'tone', type: "'green' | 'cyan' | 'gold' | 'red' | 'purple' | 'pink' | 'neutral' | 'inherit'", default: "'green'", description: "Tone token applied to the text color, in monospace; `'inherit'` keeps the font and colour of the text around it. Default `'green'`." },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the animation should play. Default `'mount'`." },
          { name: 'onComplete', type: '() => void', description: 'Fires once the full string is rendered.' },
          { name: 'className', type: 'string', description: 'Extra class names applied to the wrapping `<span>`.' },
        ],
        notes: [
          '`ref` points to `<span>`.',
        ],
      },
    ],
  },
  vue: {
    import: "import { PixelTypewriter } from '@pxlkit/ui-kit-vue';",
    components: [
      {
        name: 'PixelTypewriter',
        props: [
          { name: 'label', type: 'string', description: 'Label (text) to type out. Canonical prop.' },
          { name: 'text', type: 'string', deprecated: 'Use `label` instead. Retained as alias for one minor.' },
          { name: 'speed', type: 'number', default: '60', description: 'Milliseconds between each character.' },
          { name: 'delay', type: 'number', default: '0', description: 'Delay before typing starts, in milliseconds.' },
          { name: 'cursor', type: 'boolean', default: 'true', description: 'Show a blinking caret while writing.' },
          { name: 'tone', type: "'green' | 'cyan' | 'gold' | 'red' | 'purple' | 'pink' | 'neutral' | 'inherit'", default: "'green'", description: "Tone token applied to the text color, in monospace; `'inherit'` keeps the font and colour of the text around it." },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the typing plays: `'mount'`, `'hover'`, `'click'`, `'focus'`, `'inView'`, or `true` / `false` to control it." },
        ],
        events: [
          { name: 'complete', description: 'Once the full string is rendered (at once under reduced motion, then only once).' },
        ],
        notes: [
          'Other attributes and listeners fall through to its root `<span>`.',
        ],
      },
    ],
  },
  angular: {
    import: "import { PixelTypewriter } from '@pxlkit/ui-kit-angular';",
    components: [
      {
        name: 'PixelTypewriter',
        selector: 'pxl-typewriter',
        props: [
          { name: 'label', type: 'string', description: 'Label (text) to type out. Canonical input.' },
          { name: 'text', type: 'string', deprecated: 'Use `label` instead. Retained as alias for one minor.' },
          { name: 'speed', type: 'number', default: '60', accepts: 'unknown', description: 'Milliseconds between each character.' },
          { name: 'delay', type: 'number', default: '0', accepts: 'unknown', description: 'Delay before typing starts, in milliseconds.' },
          { name: 'cursor', type: 'boolean', default: 'true', accepts: 'unknown', description: 'Show a blinking caret while writing.' },
          { name: 'tone', type: "'green' | 'cyan' | 'gold' | 'red' | 'purple' | 'pink' | 'neutral' | 'inherit'", default: "'green'", description: "Tone token applied to the text color, in monospace; `'inherit'` keeps the font and colour of the text around it." },
          { name: 'trigger', type: "'mount' | 'hover' | 'click' | 'focus' | 'inView' | boolean", default: "'mount'", description: "When the typing plays: `'mount'`, `'hover'`, `'click'`, `'focus'`, `'inView'`, or `true` / `false` to control it." },
        ],
        events: [
          { name: 'complete', description: 'Once the full string is rendered (at once under reduced motion, then only once).' },
        ],
      },
    ],
  },
};

export function PixelTypewriterDocsSection({ className }: PixelTypewriterDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-typewriter-heading'} className={className} data-status='stable'>
      <h2 id='pixel-typewriter-heading'>PixelTypewriter</h2>
      <p className="docs-lead">Types out a string one character at a time with an optional blinking caret.</p>
      <ul className="docs-highlights">
        <li>Configurable speed, delay, and blinking caret</li>
        <li>Tone-aware text color via shared tone tokens</li>
        <li>Animation trigger modes: mount, view, hover, click</li>
        <li>Signals when the full text is typed: <code>onComplete</code> (React), <code>@complete</code> (Vue), <code>(complete)</code> (Angular)</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>animations</dd>
      <dt>Since</dt><dd>v1.6.0</dd>
    </dl>
    <section aria-labelledby="pixel-typewriter-api">
      <h3 id="pixel-typewriter-api">API</h3>
      <FrameworkApi label={'PixelTypewriter API'} react={api.react} vue={api.vue} angular={api.angular} />
    </section>
    <section aria-labelledby="pixel-typewriter-a11y">
      <h3 id="pixel-typewriter-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>respects prefers-reduced-motion</code></li>
      </ul>
      <p className="docs-aria-notes">Caret and the character-by-character animation are aria-hidden; the complete string is exposed to assistive tech from the first render via a visually hidden span. When the user prefers reduced motion, the typing animation is skipped: the full text renders immediately and the completion event fires once.</p>
    </section>
    <section aria-labelledby="pixel-typewriter-usage">
      <h3 id="pixel-typewriter-usage">Usage</h3>
      <FrameworkCode
        variant="docs"
        label={'PixelTypewriter usage'}
        react={`import { PixelTypewriter } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelTypewriter text="Hello, pxlkit." />;
}`}
        vue={`<script setup lang="ts">
import { PixelTypewriter } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelTypewriter text="Hello, pxlkit." />
</template>`}
        angular={`import { Component } from '@angular/core';
import { PixelTypewriter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTypewriter],
  template: \`<pxl-typewriter text="Hello, pxlkit." />\`,
})
export class Default {}`}
      />
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <FrameworkCode
          variant="docs"
          label={'Default code'}
          react={`import { PixelTypewriter } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelTypewriter text="Hello, pxlkit." />;
}`}
          vue={`<script setup lang="ts">
import { PixelTypewriter } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelTypewriter text="Hello, pxlkit." />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelTypewriter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTypewriter],
  template: \`<pxl-typewriter text="Hello, pxlkit." />\`,
})
export class Default {}`}
        />
      </article>
      <article className="docs-example" id="example-fast-cyan">
        <h4>Fast (cyan)</h4>
        <FrameworkCode
          variant="docs"
          label={'Fast (cyan) code'}
          react={`import { PixelTypewriter } from '@pxlkit/ui-kit';

export function FastCyan() {
  return <PixelTypewriter text="Typing fast in cyan..." speed={30} tone="cyan" />;
}`}
          vue={`<script setup lang="ts">
import { PixelTypewriter } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelTypewriter text="Typing fast in cyan..." :speed="30" tone="cyan" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelTypewriter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTypewriter],
  template: \`<pxl-typewriter text="Typing fast in cyan..." [speed]="30" tone="cyan" />\`,
})
export class FastCyan {}`}
        />
      </article>
      <article className="docs-example" id="example-no-cursor">
        <h4>No cursor</h4>
        <FrameworkCode
          variant="docs"
          label={'No cursor code'}
          react={`import { PixelTypewriter } from '@pxlkit/ui-kit';

export function NoCursor() {
  return <PixelTypewriter text="No blinking caret here." cursor={false} tone="gold" />;
}`}
          vue={`<script setup lang="ts">
import { PixelTypewriter } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelTypewriter text="No blinking caret here." :cursor="false" tone="gold" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelTypewriter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTypewriter],
  template: \`<pxl-typewriter text="No blinking caret here." [cursor]="false" tone="gold" />\`,
})
export class NoCursor {}`}
        />
      </article>
      <article className="docs-example" id="example-on-view">
        <h4>On view</h4>
        <FrameworkCode
          variant="docs"
          label={'On view code'}
          react={`import { PixelTypewriter } from '@pxlkit/ui-kit';

export function OnView() {
  return <PixelTypewriter text="Types when scrolled into view." trigger="inView" tone="purple" />;
}`}
          vue={`<script setup lang="ts">
import { PixelTypewriter } from '@pxlkit/ui-kit-vue';
</script>

<template>
  <PixelTypewriter text="Types when scrolled into view." trigger="inView" tone="purple" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelTypewriter } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelTypewriter],
  template: \`<pxl-typewriter text="Types when scrolled into view." trigger="inView" tone="purple" />\`,
})
export class OnView {}`}
        />
      </article>
    </section>
    </section>
  );
}

export default PixelTypewriterDocsSection;
