// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelStatCardDocsSectionProps {
  className?: string;
}

export const PixelStatCardDocsMeta = {
  name: 'PixelStatCard',
  slug: 'pixel-stat-card',
  status: 'stable',
  category: 'cards',
  since: '1.0.0',
  deprecated: false,
} as const;

export function PixelStatCardDocsSection({ className }: PixelStatCardDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-stat-card-heading'} className={className} data-status='stable'>
      <h2 id='pixel-stat-card-heading'>PixelStatCard</h2>
      <p className="docs-lead">Compact metric card surfacing a label, value, optional icon and trend line for dashboards and KPI grids.</p>
      <ul className="docs-highlights">
        <li>Seven tone presets aligned with the pxlkit palette (green, cyan, gold, red, purple, pink, neutral).</li>
        <li>Three sizes (sm/md/lg) that scale padding, value, label and trend typography in lockstep.</li>
        <li>Icon position aware: top, left, right or bottom-left layouts without prop drilling.</li>
        <li>Surface-aware (pixel vs linear) — inherits the ambient surface context or override per-card.</li>
        <li>Pure presentational + SSR-safe — no client hooks, fully tree-shakable.</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>cards</dd>
      <dt>Since</dt><dd>v1.0.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-stat-card-a11y">
      <h3 id="pixel-stat-card-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>none</code></li>
      </ul>
      <p className="docs-aria-notes">Presentational card with no interactive affordances; relies on surrounding heading hierarchy and tone contrast tokens for legibility.</p>
    </section>
    <section aria-labelledby="pixel-stat-card-usage">
      <h3 id="pixel-stat-card-usage">Usage</h3>
      <pre className="docs-code"><code>{`import { PixelStatCard } from '@pxlkit/ui-kit'

export function Default() {
  return <PixelStatCard label="Revenue" value="$12,480" trend="+8.2% vs last week" />
}
`}</code></pre>
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <pre className="docs-code"><code>{`export function Default() {
  return <PixelStatCard label="Revenue" value="$12,480" trend="+8.2% vs last week" />
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-tones">
        <h4>Tones</h4>
        <pre className="docs-code"><code>{`export function Tones() {
  return (
    <div className="grid grid-cols-2 gap-3">
      <PixelStatCard label="Active" value="1,204" tone="green" trend="+3.1%" />
      <PixelStatCard label="Pending" value="48" tone="gold" trend="2 overdue" />
      <PixelStatCard label="Cancelled" value="12" tone="red" trend="-1 vs ayer" />
      <PixelStatCard label="Sessions" value="3.2k" tone="cyan" trend="+220 hoy" />
      <PixelStatCard label="Members" value="89" tone="purple" />
      <PixelStatCard label="Likes" value="412" tone="pink" />
      <PixelStatCard label="Drafts" value="7" tone="neutral" />
    </div>
  )
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-sizes">
        <h4>Sizes</h4>
        <pre className="docs-code"><code>{`export function Sizes() {
  return (
    <div className="flex flex-col gap-3">
      <PixelStatCard label="Small" value="$1,200" size="sm" trend="+2%" tone="cyan" />
      <PixelStatCard label="Medium" value="$8,400" size="md" trend="+5%" tone="gold" />
      <PixelStatCard label="Large" value="$24,900" size="lg" trend="+11%" tone="green" />
    </div>
  )
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-surfaces">
        <h4>Surfaces</h4>
        <pre className="docs-code"><code>{`export function Surfaces() {
  return (
    <div className="grid grid-cols-2 gap-3">
      <PixelStatCard label="Pixel" value="$4,200" surface="pixel" tone="gold" trend="+6%" />
      <PixelStatCard label="Linear" value="$4,200" surface="linear" tone="gold" trend="+6%" />
    </div>
  )
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-icon-positions">
        <h4>Icon positions</h4>
        <pre className="docs-code"><code>{`export function IconPositions() {
  const dot = <span aria-hidden="true">$</span>
  return (
    <div className="grid grid-cols-2 gap-3">
      <PixelStatCard label="Top" value="$1,200" icon={dot} iconPosition="top" tone="cyan" />
      <PixelStatCard label="Left" value="$1,200" icon={dot} iconPosition="left" tone="green" />
      <PixelStatCard label="Right" value="$1,200" icon={dot} iconPosition="right" tone="purple" />
      <PixelStatCard
        label="Bottom-left"
        value="$1,200"
        icon={dot}
        iconPosition="bottom-left"
        tone="gold"
      />
    </div>
  )
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-without-trend">
        <h4>Without trend</h4>
        <pre className="docs-code"><code>{`export function WithoutTrend() {
  return <PixelStatCard label="Total users" value="12,480" tone="cyan" />
}`}</code></pre>
      </article>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-card">PixelCard</a></li>
        <li><a href="#pixel-stat-group">PixelStatGroup</a></li>
        <li><a href="#pixel-sparkline">PixelSparkline</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelStatCardDocsSection;
