// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';
import { FrameworkCode } from '@/components/FrameworkCode';

export interface PixelDataTableDocsSectionProps {
  className?: string;
}

export const PixelDataTableDocsMeta = {
  name: 'PixelDataTable',
  slug: 'pixel-data-table',
  status: 'stable',
  category: 'data',
  since: '1.9.0',
  deprecated: false,
} as const;

export function PixelDataTableDocsSection({ className }: PixelDataTableDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-data-table-heading'} className={className} data-status='stable'>
      <h2 id='pixel-data-table-heading'>PixelDataTable</h2>
      <p className="docs-lead">TanStack-powered surface-aware data table with controlled sorting, filtering, pagination, row selection, column visibility, density, sticky header, loading skeletons and empty state.</p>
      <ul className="docs-highlights">
        <li>Fully controlled state for sorting, filtering, pagination, row selection and column visibility</li>
        <li>Built on TanStack Table with re-exported ColumnDef and createColumnHelper for typed columns</li>
        <li>Auto-injected selection column with indeterminate header checkbox when row selection is enabled</li>
        <li>Three density presets, sticky header, skeleton loading rows and configurable empty state</li>
        <li>Surface-aware (pixel or linear) with focus-ring tokens and retro design system colors</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>data</dd>
      <dt>Since</dt><dd>v1.9.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-data-table-a11y">
      <h3 id="pixel-data-table-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>table</code></li>
      </ul>
      <p className="docs-aria-notes">Renders semantic &lt;table&gt;, &lt;thead&gt;, &lt;tbody&gt;, &lt;th scope=&quot;col&quot;&gt; and aria-sort on sortable column headers. Row selection checkboxes carry aria-label &quot;Select row &#123;id&#125;&quot; and a header checkbox labelled &quot;Select all rows&quot; with indeterminate state. Loading body exposes aria-busy and a role=&quot;status&quot; with aria-live=&quot;polite&quot; announcement. Pagination buttons declare aria-label and the page counter is announced with aria-live.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Activates a sortable column header button to cycle sort direction, or the focused clickable row (onRowClick)</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Toggles the selection checkbox when focused in the selection column, or activates the focused clickable row</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Moves focus between sort buttons, selection checkboxes, clickable rows and pagination controls</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-labelledby="pixel-data-table-usage">
      <h3 id="pixel-data-table-usage">Usage</h3>
      <FrameworkCode
        variant="docs"
        label={'PixelDataTable usage'}
        react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Default() {
  return <PixelDataTable<Row> data={rows} columns={columns} />;
}`}
        vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" />
</template>`}
        angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" />\`,
})
export class Default {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
      />
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <FrameworkCode
          variant="docs"
          label={'Default code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Default() {
  return <PixelDataTable<Row> data={rows} columns={columns} />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" />\`,
})
export class Default {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-pixel-surface">
        <h4>Pixel surface</h4>
        <FrameworkCode
          variant="docs"
          label={'Pixel surface code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function PixelSurface() {
  return <PixelDataTable<Row> data={rows} columns={columns} surface="pixel" />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" surface="pixel" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" surface="pixel" />\`,
})
export class PixelSurface {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-linear-surface">
        <h4>Linear surface</h4>
        <FrameworkCode
          variant="docs"
          label={'Linear surface code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function LinearSurface() {
  return <PixelDataTable<Row> data={rows} columns={columns} surface="linear" />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" surface="linear" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" surface="linear" />\`,
})
export class LinearSurface {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-sortable">
        <h4>Sortable columns</h4>
        <FrameworkCode
          variant="docs"
          label={'Sortable columns code'}
          react={`import * as React from 'react';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Sortable() {
  const [sorting, setSorting] = React.useState<{ id: string; desc: boolean }[]>([
    { id: 'name', desc: false },
  ]);
  return (
    <PixelDataTable<Row>
      data={rows}
      columns={columns}
      sorting={sorting}
      onSortingChange={setSorting}
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

const sorting = ref([{ id: 'name', desc: false }]);
</script>

<template>
  <PixelDataTable v-model:sorting="sorting" :data="rows" :columns="columns" />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" [(sorting)]="sorting" />\`,
})
export class Sortable {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
  readonly sorting = signal([{ id: 'name', desc: false }]);
}`}
        />
      </article>
      <article className="docs-example" id="example-row-selection">
        <h4>Row selection</h4>
        <FrameworkCode
          variant="docs"
          label={'Row selection code'}
          react={`import * as React from 'react';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function RowSelection() {
  const [selection, setSelection] = React.useState<Record<string, boolean>>({});
  return (
    <PixelDataTable<Row>
      data={rows}
      columns={columns}
      rowSelection={selection}
      onRowSelectionChange={setSelection}
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

const selection = ref<Record<string, boolean>>({});
</script>

<template>
  <PixelDataTable v-model:row-selection="selection" :data="rows" :columns="columns" />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" [(rowSelection)]="selection" />\`,
})
export class RowSelection {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
  readonly selection = signal<Record<string, boolean>>({});
}`}
        />
      </article>
      <article className="docs-example" id="example-pagination">
        <h4>Pagination</h4>
        <FrameworkCode
          variant="docs"
          label={'Pagination code'}
          react={`import * as React from 'react';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Pagination() {
  const [pagination, setPagination] = React.useState({ pageIndex: 0, pageSize: 2 });
  return (
    <PixelDataTable<Row>
      data={rows}
      columns={columns}
      pagination={pagination}
      onPaginationChange={setPagination}
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

const pagination = ref({ pageIndex: 0, pageSize: 2 });
</script>

<template>
  <PixelDataTable v-model:pagination="pagination" :data="rows" :columns="columns" />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" [(pagination)]="pagination" />\`,
})
export class Pagination {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
  readonly pagination = signal({ pageIndex: 0, pageSize: 2 });
}`}
        />
      </article>
      <article className="docs-example" id="example-compact-density">
        <h4>Compact density</h4>
        <FrameworkCode
          variant="docs"
          label={'Compact density code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function CompactDensity() {
  return <PixelDataTable<Row> data={rows} columns={columns} density="compact" />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" density="compact" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" density="compact" />\`,
})
export class CompactDensity {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-comfortable-density">
        <h4>Comfortable density</h4>
        <FrameworkCode
          variant="docs"
          label={'Comfortable density code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function ComfortableDensity() {
  return <PixelDataTable<Row> data={rows} columns={columns} density="comfortable" />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" density="comfortable" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" density="comfortable" />\`,
})
export class ComfortableDensity {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-loading">
        <h4>Loading</h4>
        <FrameworkCode
          variant="docs"
          label={'Loading code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Loading() {
  return <PixelDataTable<Row> data={[]} columns={columns} loading />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="[]" :columns="columns" loading />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="[]" [columns]="columns" loading />\`,
})
export class Loading {
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-empty">
        <h4>Empty state</h4>
        <FrameworkCode
          variant="docs"
          label={'Empty state code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Empty() {
  return (
    <PixelDataTable<Row>
      data={[]}
      columns={columns}
      emptyState={<span>No records found.</span>}
    />
  );
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="[]" :columns="columns">
    <template #empty-state><span>No records found.</span></template>
  </PixelDataTable>
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`
    <pxl-data-table [data]="[]" [columns]="columns" [emptyState]="empty" />
    <ng-template #empty><span>No records found.</span></ng-template>
  \`,
})
export class Empty {
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-sticky-header">
        <h4>Sticky header</h4>
        <FrameworkCode
          variant="docs"
          label={'Sticky header code'}
          react={`import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function StickyHeader() {
  return <PixelDataTable<Row> data={rows} columns={columns} stickyHeader />;
}`}
          vue={`<script setup lang="ts">
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];
</script>

<template>
  <PixelDataTable :data="rows" :columns="columns" sticky-header />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`<pxl-data-table [data]="rows" [columns]="columns" stickyHeader />\`,
})
export class StickyHeader {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
}`}
        />
      </article>
      <article className="docs-example" id="example-clickable-rows">
        <h4>Clickable rows</h4>
        <FrameworkCode
          variant="docs"
          label={'Clickable rows code'}
          react={`import * as React from 'react';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function ClickableRows() {
  const [last, setLast] = React.useState<string>('');
  return (
    <div>
      <PixelDataTable<Row>
        data={rows}
        columns={columns}
        onRowClick={(row) => setLast(row.name)}
      />
      <p>Last clicked: {last || 'none'}</p>
    </div>
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-vue';

type Row = { id: string; name: string; role: string; status: string };

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

const last = ref('');
</script>

<template>
  <div>
    <PixelDataTable :data="rows" :columns="columns" @row-click="(row) => (last = row.name)" />
    <p>Last clicked: {{ last || 'none' }}</p>
  </div>
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDataTable, createColumnHelper, type ColumnDef } from '@pxlkit/ui-kit-angular';

interface Row {
  id: string;
  name: string;
  role: string;
  status: string;
}

const ROWS: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const COLUMNS: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

@Component({
  imports: [PixelDataTable],
  template: \`
    <div>
      <pxl-data-table [data]="rows" [columns]="columns" clickableRows (rowClick)="last.set($event.name)" />
      <p>Last clicked: {{ last() || 'none' }}</p>
    </div>
  \`,
})
export class ClickableRows {
  readonly rows = ROWS;
  readonly columns = COLUMNS;
  readonly last = signal('');
}`}
        />
      </article>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-table">PixelTable</a></li>
        <li><a href="#pixel-pagination">PixelPagination</a></li>
        <li><a href="#pixel-empty-state">PixelEmptyState</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelDataTableDocsSection;
