// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelStackDocsSectionProps {
  className?: string;
}

export const PixelStackDocsMeta = {
  name: 'PixelStack',
  slug: 'pixel-stack',
  status: 'stable',
  category: 'layout',
  since: '1.6.0',
  deprecated: false,
} as const;

export function PixelStackDocsSection({ className }: PixelStackDocsSectionProps): React.ReactElement {
  return (
    <section id={'pixel-stack'} aria-labelledby={'pixel-stack-heading'} className={className} data-status='stable'>
      <h2 id='pixel-stack-heading'>PixelStack</h2>
      <p className="docs-lead">Polymorphic flex container with token-driven gap, direction, alignment, and surface-aware transitions.</p>
      <ul className="docs-highlights">
        <li>Direction toggle between column and row flex layouts</li>
        <li>Token-based gap scale via stackGap for consistent rhythm</li>
        <li>Alignment and justification helpers including baseline and space variants</li>
        <li>Surface-aware transitions through useEffectiveSurface</li>
        <li>Polymorphic via the `as` prop to render any intrinsic element</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>layout</dd>
      <dt>Since</dt><dd>v1.6.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-stack-a11y">
      <h3 id="pixel-stack-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>polymorphic-flex-container</code></li>
      </ul>
      <p className="docs-aria-notes">Renders as &lt;div&gt; by default; inherits semantics from the `as` prop when overridden.</p>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-cluster">PixelCluster</a></li>
        <li><a href="#pixel-grid">PixelGrid</a></li>
        <li><a href="#pixel-center">PixelCenter</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelStackDocsSection;
