// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';
import { FrameworkCode } from '@/components/FrameworkCode';

export interface PixelNavigationMenuDocsSectionProps {
  className?: string;
}

export const PixelNavigationMenuDocsMeta = {
  name: 'PixelNavigationMenu',
  slug: 'pixel-navigation-menu',
  status: 'stable',
  category: 'navigation',
  since: '1.9.0',
  deprecated: false,
} as const;

export function PixelNavigationMenuDocsSection({ className }: PixelNavigationMenuDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-navigation-menu-heading'} className={className} data-status='stable'>
      <h2 id='pixel-navigation-menu-heading'>PixelNavigationMenu</h2>
      <p className="docs-lead">Accessible nav landmark with optional mega-panel submenus, keyboard navigation, and surface-aware styling.</p>
      <ul className="docs-highlights">
        <li>Horizontal or vertical orientation</li>
        <li>Optional shared viewport panel or inline per-item panels</li>
        <li>WAI-ARIA disclosure navigation: each panel follows its button in the tab order, with Arrow/Home/End/Escape keys</li>
        <li>Surface-aware via useEffectiveSurface</li>
        <li>SSR-safe, ref-forwarded nav landmark</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>navigation</dd>
      <dt>Since</dt><dd>v1.9.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-navigation-menu-a11y">
      <h3 id="pixel-navigation-menu-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>navigation</code></li>
        <li><code>disclosure</code></li>
      </ul>
      <p className="docs-aria-notes">Follows the WAI-ARIA disclosure navigation pattern, without menu roles (those are for application menus): a <code>&lt;nav&gt;</code> landmark — give it a unique <code>ariaLabel</code> when the page has more than one (WCAG 2.4.6) — holding a list of links, and of buttons with <code>aria-expanded</code> and <code>aria-controls</code> for the items with <code>content</code>. Each panel is a plain container rendered right after its button, inside the same list item, so Tab moves from the button into the open panel; the shared viewport is only drawn below the whole list. A click, or Enter / Space on the button, toggles the panel; focus alone never opens it. A mouse pointing at an item opens its panel — touch and pen pointers do not, so a tap opens it once — and the pointer leaving the menu closes that panel, unless a click on its button kept it open: a panel opened by a click stays open until a click on its button or another one, or Escape. A panel that closes while focus is inside it hands focus back to its button. An item with both an <code>href</code> and <code>content</code> is a button whose activation toggles the panel instead of navigating.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Move to the next link or button; from the button of an open panel, into the panel</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Shift+Tab</kbd></td>
            <td>Move to the previous link or button</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Toggle the panel of a button, or follow a link; invokes <code>onSelect</code></td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Toggle the panel of a button; invokes <code>onSelect</code></td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>ArrowRight</kbd></td>
            <td>Focus next item, wrapping round</td>
            <td>horizontal</td>
          </tr>
          <tr>
            <td><kbd>ArrowLeft</kbd></td>
            <td>Focus previous item, wrapping round</td>
            <td>horizontal</td>
          </tr>
          <tr>
            <td><kbd>ArrowDown</kbd></td>
            <td>Focus the first link of the open panel</td>
            <td>horizontal, on the button of an open panel</td>
          </tr>
          <tr>
            <td><kbd>ArrowDown</kbd></td>
            <td>Focus next item, wrapping round</td>
            <td>vertical</td>
          </tr>
          <tr>
            <td><kbd>ArrowUp</kbd></td>
            <td>Focus previous item, wrapping round</td>
            <td>vertical</td>
          </tr>
          <tr>
            <td><kbd>Home</kbd></td>
            <td>Focus first item</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>End</kbd></td>
            <td>Focus last item</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Escape</kbd></td>
            <td>Close the open panel; focus on its button or inside it returns to the button</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-labelledby="pixel-navigation-menu-usage">
      <h3 id="pixel-navigation-menu-usage">Usage</h3>
      <FrameworkCode
        variant="docs"
        label={'PixelNavigationMenu usage'}
        react={`import { PixelNavigationMenu } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelNavigationMenu
      items={[
        { label: 'Home', href: '#home' },
        {
          label: 'Products',
          content: (
            <div className="grid gap-2 text-sm text-retro-text">
              <a href="#analytics" className="hover:underline">Analytics</a>
              <a href="#dashboard" className="hover:underline">Dashboard</a>
              <a href="#reports" className="hover:underline">Reports</a>
            </div>
          ),
        },
        { label: 'Docs', href: '#docs' },
        { label: 'Pricing', href: '#pricing' },
      ]}
    />
  )
}`}
        vue={`<script setup lang="ts">
import { h } from 'vue';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-vue';

const items: PixelNavigationMenuItem[] = [
  { label: 'Home', href: '#home' },
  {
    label: 'Products',
    content: () =>
      h('div', { class: 'grid gap-2 text-sm text-retro-text' }, [
        h('a', { href: '#analytics', class: 'hover:underline' }, 'Analytics'),
        h('a', { href: '#dashboard', class: 'hover:underline' }, 'Dashboard'),
        h('a', { href: '#reports', class: 'hover:underline' }, 'Reports'),
      ]),
  },
  { label: 'Docs', href: '#docs' },
  { label: 'Pricing', href: '#pricing' },
];
</script>

<template>
  <PixelNavigationMenu :items="items" />
</template>`}
        angular={`import { Component, TemplateRef, computed, viewChild } from '@angular/core';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelNavigationMenu],
  template: \`
    <pxl-navigation-menu [items]="items()" />
    <ng-template #products>
      <div class="grid gap-2 text-sm text-retro-text">
        <a href="#analytics" class="hover:underline">Analytics</a>
        <a href="#dashboard" class="hover:underline">Dashboard</a>
        <a href="#reports" class="hover:underline">Reports</a>
      </div>
    </ng-template>
  \`,
})
export class Default {
  private readonly products = viewChild.required<TemplateRef<unknown>>('products');
  readonly items = computed<PixelNavigationMenuItem[]>(() => [
    { label: 'Home', href: '#home' },
    { label: 'Products', content: this.products() },
    { label: 'Docs', href: '#docs' },
    { label: 'Pricing', href: '#pricing' },
  ]);
}`}
      />
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <FrameworkCode
          variant="docs"
          label={'Default code'}
          react={`import { PixelNavigationMenu } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelNavigationMenu
      items={[
        { label: 'Home', href: '#home' },
        {
          label: 'Products',
          content: (
            <div className="grid gap-2 text-sm text-retro-text">
              <a href="#analytics" className="hover:underline">Analytics</a>
              <a href="#dashboard" className="hover:underline">Dashboard</a>
              <a href="#reports" className="hover:underline">Reports</a>
            </div>
          ),
        },
        { label: 'Docs', href: '#docs' },
        { label: 'Pricing', href: '#pricing' },
      ]}
    />
  )
}`}
          vue={`<script setup lang="ts">
import { h } from 'vue';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-vue';

const items: PixelNavigationMenuItem[] = [
  { label: 'Home', href: '#home' },
  {
    label: 'Products',
    content: () =>
      h('div', { class: 'grid gap-2 text-sm text-retro-text' }, [
        h('a', { href: '#analytics', class: 'hover:underline' }, 'Analytics'),
        h('a', { href: '#dashboard', class: 'hover:underline' }, 'Dashboard'),
        h('a', { href: '#reports', class: 'hover:underline' }, 'Reports'),
      ]),
  },
  { label: 'Docs', href: '#docs' },
  { label: 'Pricing', href: '#pricing' },
];
</script>

<template>
  <PixelNavigationMenu :items="items" />
</template>`}
          angular={`import { Component, TemplateRef, computed, viewChild } from '@angular/core';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelNavigationMenu],
  template: \`
    <pxl-navigation-menu [items]="items()" />
    <ng-template #products>
      <div class="grid gap-2 text-sm text-retro-text">
        <a href="#analytics" class="hover:underline">Analytics</a>
        <a href="#dashboard" class="hover:underline">Dashboard</a>
        <a href="#reports" class="hover:underline">Reports</a>
      </div>
    </ng-template>
  \`,
})
export class Default {
  private readonly products = viewChild.required<TemplateRef<unknown>>('products');
  readonly items = computed<PixelNavigationMenuItem[]>(() => [
    { label: 'Home', href: '#home' },
    { label: 'Products', content: this.products() },
    { label: 'Docs', href: '#docs' },
    { label: 'Pricing', href: '#pricing' },
  ]);
}`}
        />
      </article>
      <article className="docs-example" id="example-vertical">
        <h4>Vertical</h4>
        <FrameworkCode
          variant="docs"
          label={'Vertical code'}
          react={`import { PixelNavigationMenu } from '@pxlkit/ui-kit';

export function Vertical() {
  return (
    <PixelNavigationMenu
      orientation="vertical"
      items={[
        { label: 'Overview', href: '#overview' },
        { label: 'Settings', href: '#settings' },
        { label: 'Billing', href: '#billing' },
      ]}
    />
  )
}`}
          vue={`<script setup lang="ts">
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-vue';

const items: PixelNavigationMenuItem[] = [
  { label: 'Overview', href: '#overview' },
  { label: 'Settings', href: '#settings' },
  { label: 'Billing', href: '#billing' },
];
</script>

<template>
  <PixelNavigationMenu orientation="vertical" :items="items" />
</template>`}
          angular={`import { Component } from '@angular/core';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelNavigationMenu],
  template: \`<pxl-navigation-menu orientation="vertical" [items]="items" />\`,
})
export class Vertical {
  readonly items: PixelNavigationMenuItem[] = [
    { label: 'Overview', href: '#overview' },
    { label: 'Settings', href: '#settings' },
    { label: 'Billing', href: '#billing' },
  ];
}`}
        />
      </article>
      <article className="docs-example" id="example-inline-panels">
        <h4>Inline Panels</h4>
        <FrameworkCode
          variant="docs"
          label={'Inline Panels code'}
          react={`import { PixelNavigationMenu } from '@pxlkit/ui-kit';

export function InlinePanels() {
  return (
    <PixelNavigationMenu
      viewport={false}
      items={[
        { label: 'Home', href: '#home' },
        {
          label: 'Resources',
          content: (
            <div className="grid gap-2 text-sm text-retro-text">
              <a href="#guides" className="hover:underline">Guides</a>
              <a href="#api" className="hover:underline">API Reference</a>
            </div>
          ),
        },
      ]}
    />
  )
}`}
          vue={`<script setup lang="ts">
import { h } from 'vue';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-vue';

const items: PixelNavigationMenuItem[] = [
  { label: 'Home', href: '#home' },
  {
    label: 'Resources',
    content: () =>
      h('div', { class: 'grid gap-2 text-sm text-retro-text' }, [
        h('a', { href: '#guides', class: 'hover:underline' }, 'Guides'),
        h('a', { href: '#api', class: 'hover:underline' }, 'API Reference'),
      ]),
  },
];
</script>

<template>
  <PixelNavigationMenu :viewport="false" :items="items" />
</template>`}
          angular={`import { Component, TemplateRef, computed, viewChild } from '@angular/core';
import { PixelNavigationMenu, type PixelNavigationMenuItem } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelNavigationMenu],
  template: \`
    <pxl-navigation-menu [viewport]="false" [items]="items()" />
    <ng-template #resources>
      <div class="grid gap-2 text-sm text-retro-text">
        <a href="#guides" class="hover:underline">Guides</a>
        <a href="#api" class="hover:underline">API Reference</a>
      </div>
    </ng-template>
  \`,
})
export class InlinePanels {
  private readonly resources = viewChild.required<TemplateRef<unknown>>('resources');
  readonly items = computed<PixelNavigationMenuItem[]>(() => [
    { label: 'Home', href: '#home' },
    { label: 'Resources', content: this.resources() },
  ]);
}`}
        />
      </article>
    </section>
    </section>
  );
}

export default PixelNavigationMenuDocsSection;
