// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelCheckboxDocsSectionProps {
  className?: string;
}

export const PixelCheckboxDocsMeta = {
  name: 'PixelCheckbox',
  slug: 'pixel-checkbox',
  status: 'stable',
  category: 'forms',
  since: '1.0.0',
  deprecated: false,
} as const;

export function PixelCheckboxDocsSection({ className }: PixelCheckboxDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-checkbox-heading'} className={className} data-status='stable'>
      <h2 id='pixel-checkbox-heading'>PixelCheckbox</h2>
      <p className="docs-lead">Controlled boolean checkbox with a chunky pixel check mark, tone-aware fill, and optional form serialization.</p>
      <ul className="docs-highlights">
        <li>Fully controlled via checked + onChange(next: boolean)</li>
        <li>Seven tones via the shared toneMap palette</li>
        <li>Pixel and linear surface variants share the same API</li>
        <li>Hidden mirror input lets it participate in native &lt;form&gt; submissions when name is set</li>
        <li>Renders as role=&quot;checkbox&quot; with aria-checked, aria-disabled, and aria-required</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>forms</dd>
      <dt>Since</dt><dd>v1.0.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-checkbox-a11y">
      <h3 id="pixel-checkbox-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>checkbox</code></li>
      </ul>
      <p className="docs-aria-notes">Rendered as a &lt;button type=&quot;button&quot;&gt; with role=&quot;checkbox&quot; and aria-checked reflecting the boolean state. aria-disabled and aria-required mirror the disabled and required props. When a name prop is supplied a hidden &lt;input&gt; is emitted alongside so the value participates in native &lt;form&gt; submissions only while checked.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Toggles the checkbox between checked and unchecked.</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Submits the enclosing form (native &lt;button type=&quot;button&quot;&gt; behavior is keyboard-activated via Space; Enter falls back to form submission).</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Moves focus to the next focusable element in the tab order.</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-labelledby="pixel-checkbox-usage">
      <h3 id="pixel-checkbox-usage">Usage</h3>
      <pre className="docs-code"><code>{`import { useState } from 'react';
import { PixelCheckbox } from '@pxlkit/ui-kit';

export function Default() {
  const [checked, setChecked] = useState(false);
  return (
    <PixelCheckbox
      label="Accept terms"
      checked={checked}
      onChange={setChecked}
    />
  );
}
`}</code></pre>
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <pre className="docs-code"><code>{`export function Default() {
  const [checked, setChecked] = useState(false);
  return (
    <PixelCheckbox
      label="Accept terms"
      checked={checked}
      onChange={setChecked}
    />
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-checked">
        <h4>Checked</h4>
        <pre className="docs-code"><code>{`export function Checked() {
  const [checked, setChecked] = useState(true);
  return (
    <PixelCheckbox
      label="Subscribe to newsletter"
      checked={checked}
      onChange={setChecked}
    />
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-tones">
        <h4>Tones</h4>
        <pre className="docs-code"><code>{`export function Tones() {
  const [values, setValues] = useState<Record<string, boolean>>({
    neutral: true,
    green: true,
    cyan: true,
    gold: true,
    red: true,
    purple: true,
    pink: true,
  });
  return (
    <div className="space-y-2">
      <PixelCheckbox
        label="Neutral"
        tone="neutral"
        checked={values.neutral}
        onChange={(v) => setValues((s) => ({ ...s, neutral: v }))}
      />
      <PixelCheckbox
        label="Green"
        tone="green"
        checked={values.green}
        onChange={(v) => setValues((s) => ({ ...s, green: v }))}
      />
      <PixelCheckbox
        label="Cyan"
        tone="cyan"
        checked={values.cyan}
        onChange={(v) => setValues((s) => ({ ...s, cyan: v }))}
      />
      <PixelCheckbox
        label="Gold"
        tone="gold"
        checked={values.gold}
        onChange={(v) => setValues((s) => ({ ...s, gold: v }))}
      />
      <PixelCheckbox
        label="Red"
        tone="red"
        checked={values.red}
        onChange={(v) => setValues((s) => ({ ...s, red: v }))}
      />
      <PixelCheckbox
        label="Purple"
        tone="purple"
        checked={values.purple}
        onChange={(v) => setValues((s) => ({ ...s, purple: v }))}
      />
      <PixelCheckbox
        label="Pink"
        tone="pink"
        checked={values.pink}
        onChange={(v) => setValues((s) => ({ ...s, pink: v }))}
      />
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-surfaces">
        <h4>Surfaces</h4>
        <pre className="docs-code"><code>{`export function Surfaces() {
  const [pixel, setPixel] = useState(true);
  const [linear, setLinear] = useState(true);
  return (
    <div className="space-y-2">
      <PixelCheckbox
        label="Pixel surface"
        surface="pixel"
        checked={pixel}
        onChange={setPixel}
      />
      <PixelCheckbox
        label="Linear surface"
        surface="linear"
        checked={linear}
        onChange={setLinear}
      />
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-disabled">
        <h4>Disabled</h4>
        <pre className="docs-code"><code>{`export function Disabled() {
  return (
    <div className="space-y-2">
      <PixelCheckbox
        label="Disabled unchecked"
        disabled
        checked={false}
        onChange={() => {}}
      />
      <PixelCheckbox
        label="Disabled checked"
        disabled
        checked={true}
        onChange={() => {}}
      />
    </div>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-required">
        <h4>Required</h4>
        <pre className="docs-code"><code>{`export function Required() {
  const [checked, setChecked] = useState(false);
  return (
    <PixelCheckbox
      label="I agree to the terms"
      required
      checked={checked}
      onChange={setChecked}
    />
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-with-form-name">
        <h4>With form name</h4>
        <pre className="docs-code"><code>{`export function WithFormName() {
  const [checked, setChecked] = useState(true);
  return (
    <form>
      <PixelCheckbox
        label="Remember me"
        name="remember"
        value="yes"
        checked={checked}
        onChange={setChecked}
      />
    </form>
  );
}`}</code></pre>
      </article>
      <article className="docs-example" id="example-group">
        <h4>Group</h4>
        <pre className="docs-code"><code>{`export function Group() {
  const [prefs, setPrefs] = useState({
    email: true,
    sms: false,
    push: true,
  });
  return (
    <div className="space-y-2">
      <PixelCheckbox
        label="Email notifications"
        checked={prefs.email}
        onChange={(v) => setPrefs((s) => ({ ...s, email: v }))}
      />
      <PixelCheckbox
        label="SMS notifications"
        checked={prefs.sms}
        onChange={(v) => setPrefs((s) => ({ ...s, sms: v }))}
      />
      <PixelCheckbox
        label="Push notifications"
        checked={prefs.push}
        onChange={(v) => setPrefs((s) => ({ ...s, push: v }))}
      />
    </div>
  );
}`}</code></pre>
      </article>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-radio-group">PixelRadioGroup</a></li>
        <li><a href="#pixel-switch">PixelSwitch</a></li>
        <li><a href="#pixel-toggle">PixelToggle</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelCheckboxDocsSection;
