// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';

export interface PixelTestimonialCardDocsSectionProps {
  className?: string;
}

export const PixelTestimonialCardDocsMeta = {
  name: 'PixelTestimonialCard',
  slug: 'pixel-testimonial-card',
  status: 'stable',
  category: 'cards',
  since: '1.7.0',
  deprecated: false,
} as const;

export function PixelTestimonialCardDocsSection({ className }: PixelTestimonialCardDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-testimonial-card-heading'} className={className} data-status='stable'>
      <h2 id='pixel-testimonial-card-heading'>PixelTestimonialCard</h2>
      <p className="docs-lead">Surface-aware testimonial card with quote, attribution, avatar, star rating and verified badge.</p>
      <ul className="docs-highlights">
        <li>Semantic article + blockquote markup for accessible social proof</li>
        <li>Tone tokens drive avatar + accents; surface adapts borders, radii and fonts</li>
        <li>Optional star rating and VERIFIED badge for trust signals</li>
        <li>Three quote-size presets (compact / normal / long) keep card grids aligned</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>cards</dd>
      <dt>Since</dt><dd>v1.7.0</dd>
    </dl>
    <section aria-label="Props">
      <h3>Props</h3>
      <p className="docs-empty">No props documented yet.</p>
    </section>
    <section aria-labelledby="pixel-testimonial-card-a11y">
      <h3 id="pixel-testimonial-card-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>semantic blockquote + cite</code></li>
        <li><code>figure/figcaption for quote variant</code></li>
      </ul>
      <p className="docs-aria-notes">Renders as &lt;article&gt; with a &lt;blockquote&gt; for the testimonial body; verified badge exposes an aria-label.</p>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-star-rating">PixelStarRating</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelTestimonialCardDocsSection;
