// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

import * as React from 'react';
import { FrameworkApi, type FrameworkApiReferences } from '@/components/FrameworkApi';
import { FrameworkCode } from '@/components/FrameworkCode';

export interface PixelDateRangePickerDocsSectionProps {
  className?: string;
}

export const PixelDateRangePickerDocsMeta = {
  name: 'PixelDateRangePicker',
  slug: 'pixel-date-range-picker',
  status: 'stable',
  category: 'forms',
  since: '1.9.0',
  deprecated: false,
} as const;

/** PixelDateRangePicker's API in each kit, read from its sources by `npm run docs:build`. */
const api: FrameworkApiReferences = {
  react: {
    import: "import { PixelDateRangePicker } from '@pxlkit/ui-kit';",
    components: [
      {
        name: 'PixelDateRangePicker',
        props: [
          { name: 'value', type: 'DateRangeValue', description: 'The range; leave unset for an uncontrolled picker.' },
          { name: 'defaultValue', type: 'DateRangeValue', description: 'Initial range while uncontrolled.' },
          { name: 'onChange', type: '(next: DateRangeValue) => void', description: 'Called with the range after every change: its start alone after a first pick, `{}` once cleared.' },
          { name: 'min', type: 'Date', description: 'First day that can be picked.' },
          { name: 'max', type: 'Date', description: 'Last day that can be picked.' },
          { name: 'presets', type: '{ label: string; value: { from: Date; to: Date } }[]', description: 'Quick picks of whole ranges, shown above the months.' },
          { name: 'numberOfMonths', type: '1 | 2', default: '2', description: 'Months shown side by side.' },
          { name: 'surface', type: "'pixel' | 'linear'", description: 'Surface override; defaults to the nearest provider.' },
          { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Trigger height.' },
          { name: 'label', type: 'string', description: 'Label rendered above the trigger.' },
          { name: 'hint', type: 'string', description: 'Helper text below the field; hidden while `error` is set.' },
          { name: 'error', type: 'string', description: 'Error message below the field; marks the trigger invalid.' },
          { name: 'placeholder', type: 'string', default: "'Select date range'", description: 'Text shown while no range is picked.' },
          { name: 'clearable', type: 'boolean', default: 'false', description: "Adds a clear button over the trigger's end and a Clear button under the months while a range is set." },
          { name: 'name', type: 'string', description: 'Form field name — hidden inputs submit `name.from` and `name.to` as `YYYY-MM-DD`.' },
          { name: 'id', type: 'string', description: '`id` of the trigger; generated when left out.' },
          { name: 'data-testid', type: 'string', description: '`data-testid` of the trigger.' },
        ],
        notes: [
          '`ref` points to `<button>`.',
        ],
      },
    ],
  },
  vue: {
    import: "import { PixelDateRangePicker } from '@pxlkit/ui-kit-vue';",
    components: [
      {
        name: 'PixelDateRangePicker',
        props: [
          { name: 'modelValue', type: 'DateRangeValue', binding: 'v-model', description: 'The range (`v-model`); leave unset for an uncontrolled picker.' },
          { name: 'defaultValue', type: 'DateRangeValue', description: 'Initial range while uncontrolled.' },
          { name: 'min', type: 'Date', description: 'First day that can be picked.' },
          { name: 'max', type: 'Date', description: 'Last day that can be picked.' },
          { name: 'presets', type: 'PixelDateRangePickerPreset[]', description: 'Quick picks of whole ranges, shown above the months.' },
          { name: 'numberOfMonths', type: '1 | 2', default: '2', description: 'Months shown side by side.' },
          { name: 'surface', type: "'pixel' | 'linear'", description: 'Surface override; defaults to the nearest provider.' },
          { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Trigger height.' },
          { name: 'label', type: 'string', description: 'Label rendered above the trigger.' },
          { name: 'hint', type: 'string', description: 'Helper text below the field; hidden while `error` is set.' },
          { name: 'error', type: 'string', description: 'Error message below the field; marks the trigger invalid.' },
          { name: 'placeholder', type: 'string', default: "'Select date range'", description: 'Text shown while no range is picked.' },
          { name: 'clearable', type: 'boolean', default: 'false', description: "Adds a clear button over the trigger's end and a Clear button under the months while a range is set." },
          { name: 'name', type: 'string', description: 'Form field name — hidden inputs submit `name.from` and `name.to` as `YYYY-MM-DD`.' },
          { name: 'id', type: 'string', description: '`id` of the trigger; generated when left out.' },
        ],
        events: [
          { name: 'update:modelValue', payload: 'range: DateRangeValue', description: 'The range after every change: its start alone after a first pick, `{}` once cleared.' },
        ],
        notes: [
          'Other attributes and listeners go to the `<button>`.',
          'Its template ref exposes `element`: the trigger button.',
        ],
      },
    ],
  },
  angular: {
    import: "import { PixelDateRangePicker } from '@pxlkit/ui-kit-angular';",
    components: [
      {
        name: 'PixelDateRangePicker',
        selector: 'pxl-date-range-picker',
        props: [
          { name: 'value', type: 'DateRangeValue', binding: '[(value)]', description: 'The range (`[(value)]`); leave unset for an uncontrolled picker.' },
          { name: 'defaultValue', type: 'DateRangeValue', description: 'Initial range while uncontrolled.' },
          { name: 'min', type: 'Date', description: 'First day that can be picked.' },
          { name: 'max', type: 'Date', description: 'Last day that can be picked.' },
          { name: 'presets', type: 'PixelDateRangePickerPreset[]', description: 'Quick picks of whole ranges, shown above the months.' },
          { name: 'numberOfMonths', type: '1 | 2', default: '2', description: 'Months shown side by side.' },
          { name: 'surface', type: "'pixel' | 'linear'", description: 'Surface override; defaults to the nearest provider.' },
          { name: 'size', type: "'sm' | 'md' | 'lg'", default: "'md'", description: 'Trigger height.' },
          { name: 'label', type: 'string', description: 'Label rendered above the trigger.' },
          { name: 'hint', type: 'string', description: 'Helper text below the field; hidden while `error` is set.' },
          { name: 'error', type: 'string', description: 'Error message below the field; marks the trigger invalid.' },
          { name: 'placeholder', type: 'string', default: "'Select date range'", description: 'Text shown while no range is picked.' },
          { name: 'clearable', type: 'boolean', default: 'false', accepts: 'unknown', description: "Adds a clear button over the trigger's end and a Clear button under the months while a range is set." },
          { name: 'name', type: 'string', description: 'Form field name — hidden inputs submit `name.from` and `name.to` as `YYYY-MM-DD`.' },
          { name: 'id', type: 'string', description: '`id` of the trigger; generated when left out.' },
          { name: 'aria-describedby', type: 'string', description: 'Ids of more elements that describe the trigger; its hint / error is added while one shows.' },
          { name: 'data-testid', type: 'string', description: '`data-testid` of the trigger.' },
        ],
        events: [
          { name: 'valueChange', payload: 'DateRangeValue', description: 'The new `value`: the event half of `[(value)]`.' },
        ],
        notes: [
          'A form control: works with `ngModel`, `formControl` and `formControlName`, which read and write `value` (`DateRangeValue`).',
        ],
      },
    ],
  },
};

export function PixelDateRangePickerDocsSection({ className }: PixelDateRangePickerDocsSectionProps): React.ReactElement {
  return (
    <section aria-labelledby={'pixel-date-range-picker-heading'} className={className} data-status='stable'>
      <h2 id='pixel-date-range-picker-heading'>PixelDateRangePicker</h2>
      <p className="docs-lead">Accessible date range picker with one or two-month grid, hover preview, presets, and min/max constraints.</p>
      <ul className="docs-highlights">
        <li>Controlled — <code>value</code> + <code>onChange</code> (React), <code>v-model</code> (Vue), <code>[(value)]</code> or forms (Angular) — or uncontrolled with <code>defaultValue</code></li>
        <li>One or two-month calendar with hover preview while picking</li>
        <li>Auto-swap of from/to when the second pick precedes the first</li>
        <li>Optional quick-select presets and clearable trigger</li>
        <li>Surface-aware styling with FieldShell label/hint/error wiring</li>
      </ul>
    <dl className="docs-meta">
      <dt>Status</dt><dd>stable</dd>
      <dt>Category</dt><dd>forms</dd>
      <dt>Since</dt><dd>v1.9.0</dd>
    </dl>
    <section aria-labelledby="pixel-date-range-picker-api">
      <h3 id="pixel-date-range-picker-api">API</h3>
      <FrameworkApi label={'PixelDateRangePicker API'} react={api.react} vue={api.vue} angular={api.angular} />
    </section>
    <section aria-labelledby="pixel-date-range-picker-a11y">
      <h3 id="pixel-date-range-picker-a11y">Accessibility</h3>
      <p>WCAG target: <strong>2.1 AA</strong></p>
      <ul className="docs-aria-patterns">
        <li><code>two-month grid (role=grid)</code></li>
        <li><code>aria-label on day cells</code></li>
        <li><code>start/end announced</code></li>
        <li><code>presets keyboard-reachable</code></li>
        <li><code>clear button beside the trigger</code></li>
      </ul>
      <p className="docs-aria-notes">Opening moves focus to the range start, else today; Escape, a preset and picking the end return it to the trigger. The popover is a dialog named &quot;Choose date range&quot;. Each calendar panel uses role=grid with a labelled aria-live month header; day cells expose aria-selected for range edges, aria-current=&quot;date&quot; for today and aria-disabled for out-of-bound days, and one day of the two months is in the tab order. Presets render as native buttons reachable via Tab. With clearable and a range set, a native &quot;Clear range&quot; button lies over the end of the trigger, beside it rather than inside (a button cannot contain a button): it is the next tab stop, clears the range, closes an open popover and moves focus to the trigger.</p>
      <h4>Keyboard</h4>
      <table className="docs-keyboard">
        <thead>
          <tr>
            <th scope="col">Key</th>
            <th scope="col">Action</th>
            <th scope="col">When</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><kbd>ArrowLeft</kbd></td>
            <td>Move focus to the previous day</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>ArrowRight</kbd></td>
            <td>Move focus to the next day</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>ArrowUp</kbd></td>
            <td>Move focus to the previous week</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>ArrowDown</kbd></td>
            <td>Move focus to the next week</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Home</kbd></td>
            <td>Move focus to the first day of the week</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>End</kbd></td>
            <td>Move focus to the last day of the week</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>PageUp</kbd></td>
            <td>Move focus to the same day of the previous month (its last day when shorter)</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>PageDown</kbd></td>
            <td>Move focus to the same day of the next month (its last day when shorter)</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Shift+PageUp</kbd></td>
            <td>Move focus to the same day of the previous year</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Shift+PageDown</kbd></td>
            <td>Move focus to the same day of the next year</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Enter</kbd></td>
            <td>Select the focused day (start, then end)</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Space</kbd></td>
            <td>Select the focused day (start, then end)</td>
            <td><span className="docs-muted">—</span></td>
          </tr>
          <tr>
            <td><kbd>Tab</kbd></td>
            <td>Move from the trigger to its clear button while a range is set</td>
            <td>clearable</td>
          </tr>
          <tr>
            <td><kbd>Enter / Space</kbd></td>
            <td>Clear the range and focus the trigger, without opening the popover</td>
            <td>clear button focused</td>
          </tr>
        </tbody>
      </table>
    </section>
    <section aria-labelledby="pixel-date-range-picker-usage">
      <h3 id="pixel-date-range-picker-usage">Usage</h3>
      <FrameworkCode
        variant="docs"
        label={'PixelDateRangePicker usage'}
        react={`import { useState } from 'react';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit';

export function Default() {
  const [range, setRange] = useState<DateRangeValue>({});
  return (
    <PixelDateRangePicker
      label="Date range"
      value={range}
      onChange={setRange}
      placeholder="Select date range"
    />
  );
}`}
        vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-vue';

const range = ref<DateRangeValue>({});
</script>

<template>
  <PixelDateRangePicker v-model="range" label="Date range" placeholder="Select date range" />
</template>`}
        angular={`import { Component, signal } from '@angular/core';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelDateRangePicker],
  template: \`<pxl-date-range-picker label="Date range" placeholder="Select date range" [(value)]="range" />\`,
})
export class Default {
  readonly range = signal<DateRangeValue>({});
}`}
      />
    </section>
    <section aria-label="Examples">
      <h3>Examples</h3>
      <article className="docs-example" id="example-default">
        <h4>Default</h4>
        <p>The calendar renders when the popover opens, in the browser: a server render holds the trigger alone, so no current month or today&#39;s mark can differ from the browser&#39;s.</p>
        <FrameworkCode
          variant="docs"
          label={'Default code'}
          react={`import { useState } from 'react';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit';

export function Default() {
  const [range, setRange] = useState<DateRangeValue>({});
  return (
    <PixelDateRangePicker
      label="Date range"
      value={range}
      onChange={setRange}
      placeholder="Select date range"
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-vue';

const range = ref<DateRangeValue>({});
</script>

<template>
  <PixelDateRangePicker v-model="range" label="Date range" placeholder="Select date range" />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelDateRangePicker],
  template: \`<pxl-date-range-picker label="Date range" placeholder="Select date range" [(value)]="range" />\`,
})
export class Default {
  readonly range = signal<DateRangeValue>({});
}`}
        />
      </article>
      <article className="docs-example" id="example-with-presets">
        <h4>With Presets</h4>
        <FrameworkCode
          variant="docs"
          label={'With Presets code'}
          react={`import { useState } from 'react';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit';

export function WithPresets() {
  const [range, setRange] = useState<DateRangeValue>({});
  const today = new Date();
  const start = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  const last7 = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6);
  const last30 = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 29);
  const next7 = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7);
  return (
    <PixelDateRangePicker
      label="Reporting period"
      value={range}
      onChange={setRange}
      clearable
      presets={[
        { label: 'Last 7 days', value: { from: last7, to: start } },
        { label: 'Last 30 days', value: { from: last30, to: start } },
        { label: 'Next 7 days', value: { from: start, to: next7 } },
      ]}
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-vue';

const range = ref<DateRangeValue>({});
const today = new Date();
const start = new Date(today.getFullYear(), today.getMonth(), today.getDate());
const last7 = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6);
const last30 = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 29);
const next7 = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7);
const presets = [
  { label: 'Last 7 days', value: { from: last7, to: start } },
  { label: 'Last 30 days', value: { from: last30, to: start } },
  { label: 'Next 7 days', value: { from: start, to: next7 } },
];
</script>

<template>
  <PixelDateRangePicker v-model="range" label="Reporting period" clearable :presets="presets" />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelDateRangePicker],
  template: \`<pxl-date-range-picker label="Reporting period" clearable [presets]="presets" [(value)]="range" />\`,
})
export class WithPresets {
  readonly range = signal<DateRangeValue>({});
  private readonly today = new Date();
  private readonly start = new Date(this.today.getFullYear(), this.today.getMonth(), this.today.getDate());
  readonly presets = [
    {
      label: 'Last 7 days',
      value: { from: new Date(this.today.getFullYear(), this.today.getMonth(), this.today.getDate() - 6), to: this.start },
    },
    {
      label: 'Last 30 days',
      value: { from: new Date(this.today.getFullYear(), this.today.getMonth(), this.today.getDate() - 29), to: this.start },
    },
    {
      label: 'Next 7 days',
      value: { from: this.start, to: new Date(this.today.getFullYear(), this.today.getMonth(), this.today.getDate() + 7) },
    },
  ];
}`}
        />
      </article>
      <article className="docs-example" id="example-single-month">
        <h4>Single Month</h4>
        <FrameworkCode
          variant="docs"
          label={'Single Month code'}
          react={`import { useState } from 'react';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit';

export function SingleMonth() {
  const [range, setRange] = useState<DateRangeValue>({});
  return (
    <PixelDateRangePicker
      label="Single-month view"
      hint="Compact one-month calendar"
      value={range}
      onChange={setRange}
      numberOfMonths={1}
      clearable
    />
  );
}`}
          vue={`<script setup lang="ts">
import { ref } from 'vue';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-vue';

const range = ref<DateRangeValue>({});
</script>

<template>
  <PixelDateRangePicker
    v-model="range"
    label="Single-month view"
    hint="Compact one-month calendar"
    :number-of-months="1"
    clearable
  />
</template>`}
          angular={`import { Component, signal } from '@angular/core';
import { PixelDateRangePicker, type DateRangeValue } from '@pxlkit/ui-kit-angular';

@Component({
  imports: [PixelDateRangePicker],
  template: \`
    <pxl-date-range-picker
      label="Single-month view"
      hint="Compact one-month calendar"
      [numberOfMonths]="1"
      clearable
      [(value)]="range"
    />
  \`,
})
export class SingleMonth {
  readonly range = signal<DateRangeValue>({});
}`}
        />
      </article>
    </section>
    <section aria-label="Related components">
      <h3>Related</h3>
      <ul className="docs-related">
        <li><a href="#pixel-date-picker">PixelDatePicker</a></li>
        <li><a href="#pixel-calendar-grid">PixelCalendarGrid</a></li>
        <li><a href="#pixel-popover">PixelPopover</a></li>
      </ul>
    </section>
    </section>
  );
}

export default PixelDateRangePickerDocsSection;
