// AUTO-GENERATED by scripts/build-docs/generate-docs-page.ts
// Do NOT edit by hand. Re-run `tsx scripts/build-docs/generate-docs-page.ts`.
// Source manifest: see <Component>.manifest.ts beside the implementation.

export const USAGE_SNIPPETS: Record<string, string> = {
  'pixel-accordion': `import { PixelAccordion } from '@pxlkit/ui-kit';

const SAMPLE_ITEMS = [
  {
    id: 'overview',
    title: 'Overview',
    content: 'Introductory section that opens by default.',
  },
  {
    id: 'details',
    title: 'Details',
    content: 'Secondary section with extended copy.',
  },
  {
    id: 'faq',
    title: 'FAQ',
    content: 'Common questions and short answers.',
  },
];

export function Default() {
  return <PixelAccordion items={SAMPLE_ITEMS} />;
}
`,
  'pixel-alert': `import { PixelAlert } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelAlert
      title="Something went wrong"
      message="Your session expired. Please sign in again to continue."
    />
  );
}
`,
  'pixel-alert-dialog': `import { useState } from 'react';
import { PixelAlertDialog } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <div>
      <button type="button" onClick={() => setOpen(true)}>
        Open alert dialog
      </button>
      <PixelAlertDialog
        open={open}
        onOpenChange={setOpen}
        title="Save changes?"
        description="Your edits will be applied to the live document."
        actionLabel="Save"
        onAction={() => setOpen(false)}
      />
    </div>
  );
}
`,
  'pixel-area-chart': `import { PixelAreaChart } from '@pxlkit/ui-kit';

const sample = [
  { x: 'Mon', y: 12 },
  { x: 'Tue', y: 18 },
  { x: 'Wed', y: 9 },
  { x: 'Thu', y: 24 },
  { x: 'Fri', y: 16 },
  { x: 'Sat', y: 21 },
  { x: 'Sun', y: 14 },
];

export function Default() {
  return <PixelAreaChart data={sample} />;
}
`,
  'pixel-avatar': `import { PixelAvatar } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelAvatar name="Joangel De La Rosa" />;
}
`,
  'pixel-avatar-group': `import { PixelAvatarGroup } from '@pxlkit/ui-kit';
import { PixelAvatar } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelAvatarGroup aria-label="3 team members">
      <PixelAvatar name="Joangel De La Rosa" />
      <PixelAvatar name="Ana Lopez" />
      <PixelAvatar name="Carlos Diaz" />
    </PixelAvatarGroup>
  );
}
`,
  'pixel-badge': `import { PixelBadge } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelBadge>NEW</PixelBadge>;
}
`,
  'pixel-badge-group': `import { PixelBadgeGroup } from '@pxlkit/ui-kit';
import { PixelBadge } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelBadgeGroup aria-label="Tags">
      <PixelBadge tone="cyan">react</PixelBadge>
      <PixelBadge tone="green">typescript</PixelBadge>
      <PixelBadge tone="gold">design</PixelBadge>
    </PixelBadgeGroup>
  );
}
`,
  'pixel-bar-chart': `import { PixelBarChart } from '@pxlkit/ui-kit';

const sample = [
  { x: 'Mon', y: 12 },
  { x: 'Tue', y: 18 },
  { x: 'Wed', y: 9 },
  { x: 'Thu', y: 24 },
  { x: 'Fri', y: 16 },
  { x: 'Sat', y: 21 },
  { x: 'Sun', y: 14 },
];

export function Default() {
  return <PixelBarChart data={sample} />;
}
`,
  'pixel-bare-button': `import { PixelBareButton } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelBareButton>Bare button</PixelBareButton>;
}
`,
  'pixel-bare-input': `import * as React from 'react';
import { PixelBareInput } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelBareInput placeholder="Type something" />;
}
`,
  'pixel-bare-textarea': `import { useState } from 'react';
import { PixelBareTextarea } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelBareTextarea placeholder="Write something..." rows={4} />;
}
`,
  'pixel-bento': `import { PixelBento, PixelBentoCell } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelBento columns={3} gap={4}>
      <PixelBentoCell span="2x2" kind="feature" tone="cyan">
        <strong>Feature</strong>
        <span>Spans 2x2 with a feature layout.</span>
      </PixelBentoCell>
      <PixelBentoCell span="1x1" kind="stat" tone="green">
        <strong>42</strong>
        <span>Stats</span>
      </PixelBentoCell>
      <PixelBentoCell span="1x1" kind="compact" tone="gold">
        <span>Compact</span>
      </PixelBentoCell>
      <PixelBentoCell span="2x1" kind="feature" tone="purple">
        <strong>Wide</strong>
        <span>Spans 2x1.</span>
      </PixelBentoCell>
      <PixelBentoCell span="1x1" kind="media" tone="neutral">
        <div className="h-full w-full bg-retro-surface" />
      </PixelBentoCell>
    </PixelBento>
  );
}
`,
  'pixel-bento-cell': `import { PixelBento } from '@pxlkit/ui-kit';
import { PixelBentoCell } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelBento columns={3} gap={4}>
      <PixelBentoCell kind="feature" tone="neutral" span="2x1">
        <h3 className="text-sm font-semibold">Feature cell</h3>
        <p className="text-sm text-retro-muted">Span 2x1 with feature layout.</p>
      </PixelBentoCell>
      <PixelBentoCell kind="stat" tone="cyan" span="1x1">
        <span className="text-xs text-retro-muted">Active</span>
        <strong className="text-2xl">128</strong>
      </PixelBentoCell>
      <PixelBentoCell kind="compact" tone="green" span="1x1">
        <span className="text-sm">Compact</span>
      </PixelBentoCell>
    </PixelBento>
  );
}
`,
  'pixel-bounce': `import { PixelBounce } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelBounce>
      <span>Bounce</span>
    </PixelBounce>
  );
}
`,
  'pixel-box': `import { PixelBox } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelBox tone="neutral" variant="solid" padding="md">
      <p className="text-sm text-retro-muted">Surface-aware container box.</p>
    </PixelBox>
  );
}
`,
  'pixel-breadcrumb': `import { PixelBreadcrumb } from '@pxlkit/ui-kit';

const TRAIL = [
  { label: 'Home', href: '/' },
  { label: 'Docs', href: '/docs' },
  { label: 'Components', href: '/docs/components' },
  { label: 'Breadcrumb', active: true },
];

export function Default() {
  return <PixelBreadcrumb items={TRAIL} />;
}
`,
  'pixel-button': `import { PixelButton } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelButton>Click me</PixelButton>;
}
`,
  'pixel-calendar-grid': `import React, { useState } from 'react'
import { PixelCalendarGrid } from '@pxlkit/ui-kit'

export function Default() {
  const [value, setValue] = useState<Date | null>(null)
  return <PixelCalendarGrid value={value} onChange={setValue} />
}
`,
  'pixel-card': `import { PixelCard } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelCard title="Project Atlas">
      <p>Compact dossier on the Atlas migration. Status nominal.</p>
    </PixelCard>
  );
}
`,
  'pixel-carousel': `import { PixelCarousel } from '@pxlkit/ui-kit';

function Slide({ label, tone }: { label: string; tone: string }) {
  return (
    <div
      className="flex h-32 items-center justify-center border border-retro-border bg-retro-surface text-retro-text"
      style={{ background: tone }}
    >
      <span className="text-xs">{label}</span>
    </div>
  );
}

export function Default() {
  return (
    <PixelCarousel aria-label="Featured items">
      <PixelCarousel.Item>
        <Slide label="Slide 1" tone="rgba(14,165,233,0.15)" />
      </PixelCarousel.Item>
      <PixelCarousel.Item>
        <Slide label="Slide 2" tone="rgba(168,85,247,0.15)" />
      </PixelCarousel.Item>
      <PixelCarousel.Item>
        <Slide label="Slide 3" tone="rgba(34,197,94,0.15)" />
      </PixelCarousel.Item>
    </PixelCarousel>
  );
}
`,
  'pixel-center': `import { PixelCenter } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelCenter>
      <p className="text-sm text-retro-muted">
        Centered content with the default max-width and page gutter.
      </p>
    </PixelCenter>
  );
}
`,
  'pixel-checkbox': `import { useState } from 'react';
import { PixelCheckbox } from '@pxlkit/ui-kit';

export function Default() {
  const [checked, setChecked] = useState(false);
  return (
    <PixelCheckbox
      label="Accept terms"
      checked={checked}
      onChange={setChecked}
    />
  );
}
`,
  'pixel-chip': `import { useState } from 'react';
import { PixelChip } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelChip label="React" />;
}
`,
  'pixel-chip-group': `import React, { useState } from 'react';
import { PixelChipGroup } from '@pxlkit/ui-kit';
import { PixelChip } from '@pxlkit/ui-kit';

// PixelChipGroup reads \`value\` off each child via children inspection; the chip
// component itself forwards unknown attrs, so we use a tiny shim here so the
// example reads naturally without leaking a \`value\` prop into PixelChipProps.
const Chip = PixelChip as unknown as React.ComponentType<
  React.ComponentProps<typeof PixelChip> & { value: string }
>;

export function Default() {
  const [value, setValue] = useState<string[]>(['react']);
  return (
    <PixelChipGroup value={value} onChange={setValue} aria-label="Frameworks">
      <Chip value="react" label="React" tone="cyan" />
      <Chip value="vue" label="Vue" tone="green" />
      <Chip value="svelte" label="Svelte" tone="gold" />
    </PixelChipGroup>
  );
}
`,
  'pixel-cluster': `import React from 'react';
import { PixelCluster } from '@pxlkit/ui-kit';

function Chip({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded border border-retro-border px-2 py-1 text-xs text-retro-fg">
      {children}
    </span>
  );
}

export function Default() {
  return (
    <PixelCluster>
      <Chip>react</Chip>
      <Chip>typescript</Chip>
      <Chip>tailwind</Chip>
      <Chip>next</Chip>
      <Chip>vite</Chip>
    </PixelCluster>
  );
}
`,
  'pixel-code-inline': `import { PixelCodeInline } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelCodeInline>npm install</PixelCodeInline>;
}
`,
  'pixel-collapsible': `import { PixelCollapsible } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelCollapsible label="Show details">
      <p className="text-xs text-retro-muted">
        Hidden content revealed when the header is toggled.
      </p>
    </PixelCollapsible>
  );
}
`,
  'pixel-color-input': `import { useState } from 'react';
import { PixelColorInput } from '@pxlkit/ui-kit';

export function Default() {
  const [value, setValue] = useState<string>('#06b6d4');
  return (
    <PixelColorInput
      label="Brand color"
      value={value}
      onChange={setValue}
    />
  );
}
`,
  'pixel-color-swatch': `import { PixelColorSwatch } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelColorSwatch name="cyan" cssVar="--color-retro-cyan" />;
}
`,
  'pixel-combobox': `import { useState } from 'react';
import { PixelCombobox } from '@pxlkit/ui-kit';

const FRUITS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
  { value: 'elderberry', label: 'Elderberry' },
  { value: 'fig', label: 'Fig' },
  { value: 'grape', label: 'Grape' },
];

const GROUPED = [
  { value: 'us', label: 'United States', group: 'Americas' },
  { value: 've', label: 'Venezuela', group: 'Americas' },
  { value: 'mx', label: 'Mexico', group: 'Americas' },
  { value: 'es', label: 'Spain', group: 'Europe' },
  { value: 'fr', label: 'France', group: 'Europe' },
  { value: 'de', label: 'Germany', group: 'Europe' },
  { value: 'jp', label: 'Japan', group: 'Asia' },
  { value: 'kr', label: 'South Korea', group: 'Asia' },
];

export function Default() {
  return (
    <PixelCombobox
      label="Fruit"
      options={FRUITS}
      placeholder="Pick a fruit"
      hint="Type to filter"
    />
  );
}
`,
  'pixel-command': `import { useState } from 'react';
import { PixelCommand } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open command palette
      </button>
      <PixelCommand
        open={open}
        onOpenChange={setOpen}
        groups={[
          {
            heading: 'Actions',
            items: [
              {
                id: 'new-file',
                label: 'New file',
                shortcut: 'Ctrl+N',
                onSelect: () => setOpen(false),
              },
              {
                id: 'open-file',
                label: 'Open file…',
                shortcut: 'Ctrl+O',
                onSelect: () => setOpen(false),
              },
              {
                id: 'save',
                label: 'Save',
                shortcut: 'Ctrl+S',
                onSelect: () => setOpen(false),
              },
            ],
          },
          {
            heading: 'Navigation',
            items: [
              {
                id: 'go-home',
                label: 'Go to home',
                keywords: ['dashboard', 'start'],
                onSelect: () => setOpen(false),
              },
              {
                id: 'go-settings',
                label: 'Go to settings',
                keywords: ['preferences', 'config'],
                onSelect: () => setOpen(false),
              },
            ],
          },
        ]}
      />
    </>
  );
}
`,
  'pixel-container': `import { PixelContainer } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelContainer>
      <p className="text-sm text-retro-muted">Default container — section landmark, xl max-width, lg rhythm.</p>
    </PixelContainer>
  );
}
`,
  'pixel-data-table': `import * as React from 'react';
import {
  PixelDataTable,
  createColumnHelper,
  type ColumnDef,
} from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
  { id: '4', name: 'Dan', role: 'Engineer', status: 'active' },
  { id: '5', name: 'Eve', role: 'Designer', status: 'idle' },
];

const ch = createColumnHelper<Row>();

const columns: ColumnDef<Row, unknown>[] = [
  ch.accessor('name', { header: 'Name' }) as ColumnDef<Row, unknown>,
  ch.accessor('role', { header: 'Role' }) as ColumnDef<Row, unknown>,
  ch.accessor('status', { header: 'Status' }) as ColumnDef<Row, unknown>,
];

export function Default() {
  return <PixelDataTable<Row> data={rows} columns={columns} />;
}
`,
  'pixel-date-picker': `import { useState } from 'react';
import { PixelDatePicker } from '@pxlkit/ui-kit';

export function Default() {
  const [date, setDate] = useState<Date | null>(null);
  return (
    <PixelDatePicker
      label="Pick a date"
      value={date}
      onChange={setDate}
      placeholder="Select date"
    />
  );
}
`,
  'pixel-date-range-picker': `import { useState } from 'react';
import { PixelDateRangePicker, DateRangeValue } from '@pxlkit/ui-kit';

export function Default() {
  const [range, setRange] = useState<DateRangeValue>({});
  return (
    <PixelDateRangePicker
      label="Date range"
      value={range}
      onChange={setRange}
      placeholder="Select date range"
    />
  );
}
`,
  'pixel-divider': `import { PixelDivider } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelDivider />;
}
`,
  'pixel-drawer': `import { useState } from 'react';
import { PixelDrawer } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open drawer
      </button>
      <PixelDrawer open={open} onOpenChange={setOpen} title="Settings">
        <PixelDrawer.Header>
          <span>Settings</span>
          <button type="button" onClick={() => setOpen(false)}>
            Close
          </button>
        </PixelDrawer.Header>
        <PixelDrawer.Body>
          <p>Drawer content goes here.</p>
        </PixelDrawer.Body>
        <PixelDrawer.Footer>
          <button type="button" onClick={() => setOpen(false)}>
            Done
          </button>
        </PixelDrawer.Footer>
      </PixelDrawer>
    </>
  );
}
`,
  'pixel-dropdown': `import { useState } from 'react';
import { PixelDropdown } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelDropdown
      label="Actions"
      items={[
        { value: 'edit', label: 'Edit' },
        { value: 'duplicate', label: 'Duplicate' },
        { value: 'archive', label: 'Archive' },
      ]}
      onSelect={() => {}}
    />
  );
}
`,
  'pixel-empty-state': `import { PixelEmptyState } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelEmptyState
      title="No results found"
      description="Try adjusting your filters or search terms to find what you are looking for."
    />
  );
}
`,
  'pixel-equal-height-grid': `import { PixelEqualHeightGrid } from '@pxlkit/ui-kit';

function Card({ title, body }: { title: string; body: string }) {
  return (
    <div className="border border-retro-border p-4">
      <h3 className="text-sm font-semibold text-retro-fg">{title}</h3>
      <p className="text-sm text-retro-muted">{body}</p>
      <div className="mt-2 text-xs text-retro-muted">Footer</div>
    </div>
  );
}

export function Default() {
  return (
    <PixelEqualHeightGrid cols={3} gap={4}>
      <Card title="One" body="Short copy." />
      <Card title="Two" body="A longer body that forces the row to grow taller than the first card." />
      <Card title="Three" body="Medium length copy here." />
    </PixelEqualHeightGrid>
  );
}
`,
  'pixel-fade-in': `import { PixelFadeIn } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelFadeIn>
      <div style={{ padding: 16, background: '#111', color: '#fff' }}>
        Fades in on mount
      </div>
    </PixelFadeIn>
  );
}
`,
  'pixel-feature-card': `import { PixelFeatureCard } from '@pxlkit/ui-kit';

const PixelIcon = (
  <svg viewBox="0 0 8 8" shapeRendering="crispEdges" fill="currentColor" className="h-4 w-4">
    <rect x="3" y="0" width="2" height="8" />
    <rect x="0" y="3" width="8" height="2" />
  </svg>
);

export function Default() {
  return (
    <PixelFeatureCard
      title="Realtime sync"
      description="Push every keystroke to peers via WebSockets — under 50ms p95."
    />
  );
}
`,
  'pixel-file-upload': `import { useState } from 'react';
import { PixelFileUpload } from '@pxlkit/ui-kit';

export function Default() {
  const [files, setFiles] = useState<File[]>([]);
  return (
    <PixelFileUpload
      label="Upload files"
      hint="PNG or JPG, up to 5 MB each"
      value={files}
      onChange={setFiles}
      accept="image/*"
      multiple
      maxSize={5 * 1024 * 1024}
      maxFiles={5}
    />
  );
}
`,
  'pixel-flicker': `import { PixelFlicker } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelFlicker>
      <span>OPEN 24/7</span>
    </PixelFlicker>
  );
}
`,
  'pixel-float': `import { PixelFloat } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelFloat>
      <span>Float</span>
    </PixelFloat>
  );
}
`,
  'pixel-form': `'use client';

import { useForm } from 'react-hook-form';
import { PixelForm } from '@pxlkit/ui-kit';
import { PixelInput } from '@pxlkit/ui-kit';

type DefaultValues = {
  username: string;
  email: string;
};

export function Default() {
  const form = useForm<DefaultValues>({
    defaultValues: { username: '', email: '' },
  });

  return (
    <PixelForm
      form={form}
      onSubmit={(data) => {
        // eslint-disable-next-line no-console
        console.log('submit', data);
      }}
    >
      <PixelForm.Field
        name="username"
        rules={{ required: 'Username is required' }}
        render={({ field }) => (
          <PixelForm.Item>
            <PixelForm.Label>Username</PixelForm.Label>
            <PixelForm.Control>
              <PixelInput placeholder="pxlhero" {...field} />
            </PixelForm.Control>
            <PixelForm.Description>Your retro alias.</PixelForm.Description>
            <PixelForm.Message />
          </PixelForm.Item>
        )}
      />

      <PixelForm.Field
        name="email"
        rules={{
          required: 'Email is required',
          pattern: { value: /.+@.+\\..+/, message: 'Enter a valid email' },
        }}
        render={({ field }) => (
          <PixelForm.Item>
            <PixelForm.Label>Email</PixelForm.Label>
            <PixelForm.Control>
              <PixelInput type="email" placeholder="hero@pxlkit.xyz" {...field} />
            </PixelForm.Control>
            <PixelForm.Message />
          </PixelForm.Item>
        )}
      />
    </PixelForm>
  );
}
`,
  'pixel-glitch': `import { PixelGlitch } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelGlitch>
      <span className="text-2xl font-bold">SYSTEM ONLINE</span>
    </PixelGlitch>
  );
}
`,
  'pixel-grid': `import React from 'react';
import { PixelGrid } from '@pxlkit/ui-kit';

function Cell({ children }: { children: React.ReactNode }) {
  return (
    <div className="border border-retro-border bg-retro-surface p-3 text-sm text-retro-fg">
      {children}
    </div>
  );
}

export function Default() {
  return (
    <PixelGrid cols={3} gap={4}>
      <Cell>One</Cell>
      <Cell>Two</Cell>
      <Cell>Three</Cell>
      <Cell>Four</Cell>
      <Cell>Five</Cell>
      <Cell>Six</Cell>
    </PixelGrid>
  );
}
`,
  'pixel-hero-media': `import { PixelHeroMedia } from '@pxlkit/ui-kit';

const Placeholder = ({ label }: { label: string }) => (
  <div className="flex h-full w-full items-center justify-center bg-gradient-to-br from-cyan-500/20 to-purple-500/20 text-xs font-mono text-retro-muted">
    {label}
  </div>
);

export function Default() {
  return (
    <PixelHeroMedia ratio="16/10">
      <Placeholder label="16:10 media" />
    </PixelHeroMedia>
  );
}
`,
  'pixel-hero-section': `import React from 'react'
import { PixelHeroSection } from '@pxlkit/ui-kit'

export function Default() {
  return (
    <PixelHeroSection
      eyebrow="Introducing"
      headline="Pixel-perfect retro UI for modern web"
      subline="A component kit that brings cinematic, terminal-grade interfaces to React apps."
      primaryCta={<button type="button">Get started</button>}
      secondaryCta={<button type="button">View docs</button>}
    />
  )
}
`,
  'pixel-icon-frame': `import { PixelIconFrame } from '@pxlkit/ui-kit';

const Glyph = () => (
  <span style={{ fontFamily: 'monospace', fontWeight: 700 }}>{'>_'}</span>
);

const Dot = () => (
  <span style={{ width: 6, height: 6, borderRadius: 9999, background: 'currentColor', display: 'inline-block' }} />
);

export function Default() {
  return <PixelIconFrame icon={<Glyph />} />;
}
`,
  'pixel-input': `import { useState } from 'react';
import { PixelInput } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelInput
      label="Username"
      placeholder="hero@pxlkit.xyz"
      hint="Your retro alias"
    />
  );
}
`,
  'pixel-input-group': `import { PixelInputGroup } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelInputGroup aria-label="Website URL">
      <input aria-label="Protocol" defaultValue="https://" className="bg-transparent px-2 outline-none" />
      <input aria-label="Domain name" defaultValue="pxlkit" className="bg-transparent px-2 outline-none" />
      <input aria-label="Top-level domain" defaultValue=".xyz" className="bg-transparent px-2 outline-none" />
    </PixelInputGroup>
  );
}
`,
  'pixel-kbd': `import { PixelKbd } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelKbd>Enter</PixelKbd>;
}
`,
  'pixel-menubar': `import { PixelMenubar, type PixelMenubarMenu } from '@pxlkit/ui-kit';

const menus: PixelMenubarMenu[] = [
  {
    label: 'File',
    items: [
      { value: 'new', label: 'New', shortcut: 'Ctrl+N' },
      { value: 'open', label: 'Open…', shortcut: 'Ctrl+O' },
      { value: 'sep-1', label: '', separator: true },
      {
        value: 'recent',
        label: 'Open Recent',
        submenu: [
          { value: 'r1', label: 'project-alpha.pxl' },
          { value: 'r2', label: 'project-beta.pxl' },
        ],
      },
      { value: 'sep-2', label: '', separator: true },
      { value: 'save', label: 'Save', shortcut: 'Ctrl+S' },
      { value: 'quit', label: 'Quit', shortcut: 'Ctrl+Q' },
    ],
  },
  {
    label: 'Edit',
    items: [
      { value: 'undo', label: 'Undo', shortcut: 'Ctrl+Z' },
      { value: 'redo', label: 'Redo', shortcut: 'Ctrl+Y', disabled: true },
      { value: 'sep-3', label: '', separator: true },
      { value: 'cut', label: 'Cut', shortcut: 'Ctrl+X' },
      { value: 'copy', label: 'Copy', shortcut: 'Ctrl+C' },
      { value: 'paste', label: 'Paste', shortcut: 'Ctrl+V' },
    ],
  },
  {
    label: 'View',
    items: [
      { value: 'zoom-in', label: 'Zoom In', shortcut: 'Ctrl++' },
      { value: 'zoom-out', label: 'Zoom Out', shortcut: 'Ctrl+-' },
    ],
  },
];

export function Default() {
  return <PixelMenubar menus={menus} />;
}
`,
  'pixel-modal': `import { useState } from 'react';
import { PixelModal } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <PixelButton onClick={() => setOpen(true)}>Open modal</PixelButton>
      <PixelModal open={open} onClose={() => setOpen(false)} title="Default modal">
        <p>This is a minimal modal with title and body content.</p>
      </PixelModal>
    </>
  );
}
`,
  'pixel-mouse-parallax': `import { PixelMouseParallax } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <div className="relative h-64 w-full overflow-hidden rounded border border-retro-border bg-retro-bg">
      <PixelMouseParallax strength={20}>
        <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded bg-retro-cyan/20 px-4 py-2 text-sm text-retro-cyan">
          Follows the cursor
        </div>
      </PixelMouseParallax>
    </div>
  );
}
`,
  'pixel-multi-select': `import React from 'react';
import { PixelMultiSelect } from '@pxlkit/ui-kit';

const OPTIONS = [
  { value: 'react', label: 'React' },
  { value: 'vue', label: 'Vue' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'solid', label: 'Solid' },
  { value: 'angular', label: 'Angular', disabled: true },
];

export function Default() {
  const [value, setValue] = React.useState<string[]>(['react']);
  return (
    <PixelMultiSelect
      label="Frameworks"
      options={OPTIONS}
      value={value}
      onChange={setValue}
      placeholder="Pick frameworks…"
    />
  );
}
`,
  'pixel-navigation-menu': `import React from 'react'
import { PixelNavigationMenu } from '@pxlkit/ui-kit'

export function Default() {
  return (
    <PixelNavigationMenu
      items={[
        { label: 'Home', href: '#home' },
        {
          label: 'Products',
          content: (
            <div className="grid gap-2 text-sm text-retro-text">
              <a href="#analytics" className="hover:underline">Analytics</a>
              <a href="#dashboard" className="hover:underline">Dashboard</a>
              <a href="#reports" className="hover:underline">Reports</a>
            </div>
          ),
        },
        { label: 'Docs', href: '#docs' },
        { label: 'Pricing', href: '#pricing' },
      ]}
    />
  )
}
`,
  'pixel-number-input': `import { useState } from 'react';
import { PixelNumberInput } from '@pxlkit/ui-kit';

export function Default() {
  const [value, setValue] = useState<number>(5);
  return (
    <PixelNumberInput
      label="Quantity"
      value={value}
      onChange={setValue}
      min={0}
      max={100}
    />
  );
}
`,
  'pixel-otp-input': `import React from 'react'
import { PixelOTPInput } from '@pxlkit/ui-kit'

export function Default() {
  const [value, setValue] = React.useState('')
  return <PixelOTPInput length={6} value={value} onChange={setValue} />
}
`,
  'pixel-pagination': `import { useState } from 'react';
import { PixelPagination } from '@pxlkit/ui-kit';

export function Default() {
  const [page, setPage] = useState(1);
  return <PixelPagination page={page} total={10} onChange={setPage} />;
}
`,
  'pixel-parallax-group': `import { PixelParallaxGroup } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelParallaxGroup
      style={{ height: 240, background: '#0b0b0f', color: '#e5e7eb' }}
    >
      <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center' }}>
        Parallax viewport
      </div>
    </PixelParallaxGroup>
  );
}
`,
  'pixel-parallax-layer': `import { PixelParallaxLayer } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelParallaxLayer speed={0.5} axis="y">
      <div style={{ padding: 24, background: '#111', color: '#fff' }}>
        Scroll to see this layer move at half speed.
      </div>
    </PixelParallaxLayer>
  );
}
`,
  'pixel-password-input': `import { useState } from 'react';
import { PixelPasswordInput } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelPasswordInput label="Password" placeholder="Enter password" />;
}
`,
  'pixel-popover': `import { useState } from 'react';
import { PixelPopover } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <PixelPopover open={open} onOpenChange={setOpen}>
      <PixelPopover.Trigger>
        <button type="button">Open popover</button>
      </PixelPopover.Trigger>
      <PixelPopover.Content aria-labelledby="popover-title">
        <h3 id="popover-title" className="font-bold mb-1">
          Popover
        </h3>
        <p className="text-sm">Floating content anchored to the trigger.</p>
      </PixelPopover.Content>
    </PixelPopover>
  );
}
`,
  'pixel-portal': `import React from 'react'
import { PixelPortal } from '@pxlkit/ui-kit'

export function Default() {
  return (
    <PixelPortal>
      <div>Portaled content (renders into document.body after mount)</div>
    </PixelPortal>
  )
}
`,
  'pixel-pricing-card': `import { PixelPricingCard } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelPricingCard
      tone="cyan"
      name="Starter"
      description="Everything you need to ship your first project."
      price={{ amount: '$19', period: '/mo' }}
      features={[
        { label: '10 projects' },
        { label: 'Basic analytics' },
        { label: 'Email support' },
        { label: 'Priority support', included: false },
      ]}
    />
  );
}
`,
  'pixel-progress': `import { PixelProgress } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelProgress value={60} label="HP" />;
}
`,
  'pixel-pulse': `import { PixelPulse } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelPulse>
      <span>Pulse</span>
    </PixelPulse>
  );
}
`,
  'pixel-radio-group': `import { useState } from 'react';
import { PixelRadioGroup } from '@pxlkit/ui-kit';

const PLANS = [
  { value: 'free', label: 'Free' },
  { value: 'pro', label: 'Pro' },
  { value: 'team', label: 'Team' },
];

export function Default() {
  const [value, setValue] = useState('free');
  return (
    <PixelRadioGroup
      label="Plan"
      value={value}
      options={PLANS}
      onChange={setValue}
    />
  );
}
`,
  'pixel-ribbon': `import React from 'react';
import { PixelRibbon } from '@pxlkit/ui-kit';

function Container({ children }: { children: React.ReactNode }) {
  return (
    <div className="relative inline-block border-2 border-retro-border bg-retro-bg/60 p-8 text-retro-text">
      <div>Card content</div>
      {children}
    </div>
  );
}

export function Default() {
  return (
    <Container>
      <PixelRibbon>New</PixelRibbon>
    </Container>
  );
}
`,
  'pixel-rotate': `import { PixelRotate } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelRotate>
      <span>Rotate</span>
    </PixelRotate>
  );
}
`,
  'pixel-scroll-area': `import { PixelScrollArea } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelScrollArea aria-label="Sample scrollable region" maxHeight={160}>
      <div className="space-y-2 p-3">
        {Array.from({ length: 12 }).map((_, i) => (
          <p key={i} className="text-sm text-retro-muted">
            Scroll item {i + 1}
          </p>
        ))}
      </div>
    </PixelScrollArea>
  );
}
`,
  'pixel-section': `import { PixelSection } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelSection title="Overview" subtitle="Key metrics for this period.">
      <p className="text-sm text-retro-muted">
        Section content goes here. Wrap any layout block.
      </p>
    </PixelSection>
  );
}
`,
  'pixel-section-header': `import { PixelSectionHeader } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelSectionHeader
      eyebrow="Section"
      title="Build pixel-perfect interfaces"
      description="A retro-cinematic component kit with surface awareness and rhythm tokens."
    />
  );
}
`,
  'pixel-segmented': `import { useState } from 'react';
import { PixelSegmented } from '@pxlkit/ui-kit';

const VIEWS = [
  { value: 'grid', label: 'Grid' },
  { value: 'list', label: 'List' },
  { value: 'kanban', label: 'Kanban' },
];

export function Default() {
  const [value, setValue] = useState('grid');
  return (
    <PixelSegmented
      label="View"
      value={value}
      options={VIEWS}
      onChange={setValue}
    />
  );
}
`,
  'pixel-select': `import { useState } from 'react';
import { PixelSelect } from '@pxlkit/ui-kit';

const FRUITS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
];

const REGIONS = [
  { value: 'us', label: 'United States' },
  { value: 've', label: 'Venezuela' },
  { value: 'es', label: 'Spain' },
  { value: 'mx', label: 'Mexico' },
];

export function Default() {
  return (
    <PixelSelect
      label="Fruit"
      options={FRUITS}
      placeholder="Pick a fruit"
      hint="Choose your favorite"
    />
  );
}
`,
  'pixel-shake': `import { PixelShake } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelShake>
      <span>Shake on mount</span>
    </PixelShake>
  );
}
`,
  'pixel-sheet': `import { useState } from 'react';
import { PixelSheet } from '@pxlkit/ui-kit';

export function Default() {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button type="button" onClick={() => setOpen(true)}>
        Open sheet
      </button>
      <PixelSheet
        open={open}
        onOpenChange={setOpen}
        title="Quick actions"
        description="Pick an action below"
      >
        <p>Sheet content goes here.</p>
        <button type="button" onClick={() => setOpen(false)}>
          Close
        </button>
      </PixelSheet>
    </>
  );
}
`,
  'pixel-sidebar': `import { PixelSidebar } from '@pxlkit/ui-kit';

const sections = [
  {
    title: 'Workspace',
    items: [
      { id: 'dashboard', label: 'Dashboard', active: true },
      { id: 'projects', label: 'Projects', badge: { label: '4', tone: 'cyan' as const } },
      { id: 'tasks', label: 'Tasks' },
    ],
  },
  {
    title: 'Account',
    items: [
      { id: 'settings', label: 'Settings' },
      { id: 'billing', label: 'Billing', badge: { label: 'NEW', tone: 'green' as const } },
    ],
  },
];

export function Default() {
  return (
    <div style={{ height: 320 }}>
      <PixelSidebar sections={sections} header={<span className="text-xs text-retro-text">pxlkit</span>} />
    </div>
  );
}
`,
  'pixel-skeleton': `import { PixelSkeleton } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelSkeleton width="12rem" height="1rem" />;
}
`,
  'pixel-slide-in': `import { PixelSlideIn } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelSlideIn>
      <div style={{ padding: 16, background: '#111', color: '#fff' }}>
        Slides in from below on mount
      </div>
    </PixelSlideIn>
  );
}
`,
  'pixel-slider': `import { useState } from 'react';
import { PixelSlider } from '@pxlkit/ui-kit';

export function Default() {
  const [value, setValue] = useState(40);
  return (
    <PixelSlider
      label="Volume"
      value={value}
      onChange={setValue}
    />
  );
}
`,
  'pixel-sparkline': `import { PixelSparkline } from '@pxlkit/ui-kit';

const sample = [
  { x: 'Mon', y: 12 },
  { x: 'Tue', y: 18 },
  { x: 'Wed', y: 9 },
  { x: 'Thu', y: 24 },
  { x: 'Fri', y: 16 },
  { x: 'Sat', y: 21 },
  { x: 'Sun', y: 14 },
];

export function Default() {
  return <PixelSparkline data={sample} />;
}
`,
  'pixel-spinner': `import React from 'react'
import { PixelSpinner } from '@pxlkit/ui-kit'

export function Default() {
  return <PixelSpinner />
}
`,
  'pixel-split-button': `import { PixelSplitButton } from '@pxlkit/ui-kit';

const exportOptions = [
  { value: 'png', label: 'Export as PNG' },
  { value: 'svg', label: 'Export as SVG' },
  { value: 'json', label: 'Export icon code' },
];

export function Default() {
  return (
    <PixelSplitButton
      label="Export"
      options={exportOptions}
      onPrimary={() => {}}
      onSelect={() => {}}
    />
  );
}
`,
  'pixel-stack': `import { PixelStack } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelStack gap={4}>
      <div className="text-sm text-retro-muted">First item</div>
      <div className="text-sm text-retro-muted">Second item</div>
      <div className="text-sm text-retro-muted">Third item</div>
    </PixelStack>
  );
}
`,
  'pixel-star-rating': `import { PxlKitIcon } from '@pxlkit/core';
import { Heart } from '@pxlkit/gamification';
import { PixelStarRating } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelStarRating value={4} />;
}
`,
  'pixel-stat-card': `import { PixelStatCard } from '@pxlkit/ui-kit'

export function Default() {
  return <PixelStatCard label="Revenue" value="$12,480" trend="+8.2% vs last week" />
}
`,
  'pixel-stat-group': `import { PixelStatGroup } from '@pxlkit/ui-kit';
import { PixelStatCard } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelStatGroup aria-label="Key metrics">
      <PixelStatCard label="Users" value="1,284" />
      <PixelStatCard label="Revenue" value="$12.4k" />
      <PixelStatCard label="Active" value="312" />
    </PixelStatGroup>
  );
}
`,
  'pixel-stepper': `import { useState } from 'react';
import { PixelStepper } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelStepper active={1}>
      <PixelStepper.Step label="Account" description="Create your account" />
      <PixelStepper.Step label="Profile" description="Add some details" />
      <PixelStepper.Step label="Confirm" description="Review and submit" />
    </PixelStepper>
  );
}
`,
  'pixel-switch': `import { useState } from 'react';
import { PixelSwitch } from '@pxlkit/ui-kit';

export function Default() {
  const [on, setOn] = useState(false);
  return <PixelSwitch label="Enable notifications" checked={on} onChange={setOn} />;
}
`,
  'pixel-table': `import * as React from 'react';
import { PixelTable, type PixelTableSortState } from '@pxlkit/ui-kit';

type Row = {
  id: string;
  name: string;
  role: string;
  status: string;
};

const rows: Row[] = [
  { id: '1', name: 'Alice', role: 'Engineer', status: 'active' },
  { id: '2', name: 'Bob', role: 'Designer', status: 'idle' },
  { id: '3', name: 'Carol', role: 'PM', status: 'active' },
];

const baseColumns = [
  { key: 'name', header: 'Name' },
  { key: 'role', header: 'Role' },
  { key: 'status', header: 'Status' },
];

export function Default() {
  return <PixelTable<Row> columns={baseColumns} data={rows} />;
}
`,
  'pixel-tabs': `import { useState } from 'react';
import { PixelTabs } from '@pxlkit/ui-kit';
import type { TabItem } from '@pxlkit/ui-kit';

const ITEMS: TabItem[] = [
  { id: 'overview', label: 'Overview', content: <p>High-level summary of the project.</p> },
  { id: 'activity', label: 'Activity', content: <p>Recent events and commits.</p> },
  { id: 'settings', label: 'Settings', content: <p>Configuration for this workspace.</p> },
];

export function Default() {
  return <PixelTabs items={ITEMS} defaultTab="overview" />;
}
`,
  'pixel-testimonial-card': `import { PixelTestimonialCard } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelTestimonialCard
      quote="pxlkit dropped the polish ceiling. Our marketing site felt like a product launch in a week."
      name="Marisol Quintero"
      role="Head of Design"
      company="Northbeam"
      stars={5}
      verified
    />
  );
}
`,
  'pixel-text-link': `import { PixelTextLink } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelTextLink href="https://pxlkit.dev">Read the docs</PixelTextLink>;
}
`,
  'pixel-textarea': `import { useState } from 'react';
import { PixelTextarea } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelTextarea
      label="Notes"
      placeholder="Write something..."
      hint="Up to 280 characters."
    />
  );
}
`,
  'pixel-timeline': `import { PixelTimeline, PixelTimelineItem } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelTimeline active={1}>
      <PixelTimelineItem title="Order placed" time="09:00">
        Confirmation email sent.
      </PixelTimelineItem>
      <PixelTimelineItem title="Packed" time="11:20">
        At the warehouse.
      </PixelTimelineItem>
      <PixelTimelineItem title="Shipped" time="—">
        Awaiting carrier pickup.
      </PixelTimelineItem>
    </PixelTimeline>
  );
}
`,
  'pixel-toast': `import { PixelToast } from '@pxlkit/ui-kit';
import type { ToastItem } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

const noop = () => {};

const baseToast = (overrides: Partial<ToastItem> = {}): ToastItem => ({
  id: 'demo',
  title: 'Saved',
  message: 'Your changes have been persisted.',
  tone: 'cyan',
  duration: 0,
  ...overrides,
});

export function Default() {
  return <PixelToast toast={baseToast()} onDismiss={noop} />;
}
`,
  'pixel-toggle': `import { useState } from 'react';
import { PixelToggle } from '@pxlkit/ui-kit';

export function Default() {
  const [pressed, setPressed] = useState(false);
  return (
    <PixelToggle value="bold" pressed={pressed} onPressedChange={setPressed}>
      Bold
    </PixelToggle>
  );
}
`,
  'pixel-toggle-group': `import { useState } from 'react';
import { PixelToggle, PixelToggleGroup } from '@pxlkit/ui-kit';

export function Default() {
  const [value, setValue] = useState<string>('left');
  return (
    <PixelToggleGroup
      type="single"
      value={value}
      onChange={setValue}
      aria-label="Text alignment"
    >
      <PixelToggle value="left">Left</PixelToggle>
      <PixelToggle value="center">Center</PixelToggle>
      <PixelToggle value="right">Right</PixelToggle>
    </PixelToggleGroup>
  );
}
`,
  'pixel-tooltip': `import { useState } from 'react';
import { PixelTooltip } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelTooltip label="Save your changes">
      <PixelButton>Save</PixelButton>
    </PixelTooltip>
  );
}
`,
  'pixel-two-column': `import { PixelTwoColumn } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelTwoColumn
      left={<div className="text-sm text-retro-muted">Left column</div>}
      right={<div className="text-sm text-retro-muted">Right column</div>}
    />
  );
}
`,
  'pixel-typewriter': `import { PixelTypewriter } from '@pxlkit/ui-kit';

export function Default() {
  return <PixelTypewriter text="Hello, pxlkit." />;
}
`,
  'pixel-zoom-in': `import { PixelZoomIn } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PixelZoomIn>
      <div style={{ padding: 16, background: '#0EA5E9', color: '#fff', borderRadius: 8 }}>
        Zoom in content
      </div>
    </PixelZoomIn>
  );
}
`,
  'pxl-kit-button': `import { PxlKitButton } from '@pxlkit/ui-kit';

const StarIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden>
    <path d="M12 2l3.09 6.26L22 9.27l-5 4.87L18.18 22 12 18.56 5.82 22 7 14.14l-5-4.87 6.91-1.01L12 2z" />
  </svg>
);

const PlusIcon = () => (
  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden>
    <path d="M12 5v14M5 12h14" />
  </svg>
);

export function Default() {
  return <PxlKitButton label="Favorite" icon={<StarIcon />} />;
}
`,
  'pxl-kit-locale-provider': `import { PxlKitLocaleProvider } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PxlKitLocaleProvider locale="en">
      <p>Hello, world!</p>
    </PxlKitLocaleProvider>
  );
}
`,
  'pxl-kit-surface-provider': `import { PxlKitSurfaceProvider } from '@pxlkit/ui-kit';

export function Default() {
  return (
    <PxlKitSurfaceProvider surface="pixel">
      <p>Nested PxlKit components default to the pixel surface.</p>
    </PxlKitSurfaceProvider>
  );
}
`,
  'pxl-kit-toast-provider': `import React from 'react';
import { PxlKitToastProvider, useToast } from '@pxlkit/ui-kit';
import { PixelButton } from '@pxlkit/ui-kit';

function TriggerRow({ children }: { children: React.ReactNode }) {
  return <div className="flex flex-wrap gap-2">{children}</div>;
}

function DefaultTriggers() {
  const { toast } = useToast();
  return (
    <TriggerRow>
      <PixelButton size="sm" onClick={() => toast({ title: 'Saved', message: 'Your changes were persisted.' })}>
        Push toast
      </PixelButton>
    </TriggerRow>
  );
}

export function Default() {
  return (
    <PxlKitToastProvider>
      <DefaultTriggers />
    </PxlKitToastProvider>
  );
}
`,
};
